[WFLY-8559] Implement test coverage for DWM
wildfly/wildfly pull request #10066
Opened 2017-05-16 14:23 UTC by LittleJohnII

upstream issue
https://issues.jboss.org/browse/WFLY-8559

eap7 issue
https://issues.jboss.org/browse/EAP7-495

previously seen in this PR
https://github.com/wildfly/wildfly/pull/9953/

then removed based on this issue and now reintroduced to manualmode module as suggested
https://issues.jboss.org/browse/WFLY-8716

contains some commented out checks (TODOs) due to this
https://issues.jboss.org/browse/WFLY-8779

All checks pass for me. I wasn't able to reproduce the Windows failures from PR 9953 (Win 2k12 R2, latest Oracle JDK), all looked clean, but since there have been many changes, I suspect the issues were fixed.

2017-05-16 21:29 UTC, ctomc requested changes

2017-05-16 21:29 UTC, ctomc commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/LongWork.java
> +        log.info("Finishing work " + name + " after " +
please remove all debugging log

2017-05-17 06:49 UTC, rsvoboda commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/DwmWatermarkTestCase.java
> +        Thread.sleep(LongWork.WORK_TIMEOUT + 100); // wait for the scheduled work to start and finish, so it doesn't mess up our statistics for other tests
@LittleJohnII Need for Thread.sleep indicates that you can't find-out when the work is done and get notified ?

Why is this "safety sleep" in reality needed ?

Another thing is that I don't like @InSequence. Why is the TestCase designed to need it, each @Test should be isolated - e.g. for running just -Dtest=TestCase#test.

2017-05-17 08:13 UTC, LittleJohnII commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/LongWork.java
> +        Logger log = Logger.getLogger(this.getClass().getCanonicalName());
Agreed, tried to make a static field out of it, but am seeing this: https://gist.github.com/LittleJohnII/6f69b239bd87c9d50177063d3d6f17e5

@maeste I don't think I'm doing anything wrong, is there a reason for the exception?

2017-05-17 08:13 UTC, LittleJohnII commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/DwmWatermarkTestCase.java
> +        Thread.sleep(LongWork.WORK_TIMEOUT + 100); // wait for the scheduled work to start and finish, so it doesn't mess up our statistics for other tests
@ctomc I removed all logging as requested, I'll push when the sleep change is ready.

@rsvoboda The InSequence is only really needed for Watermark test. I removed it from the other tests. The reason Watermark test needs it is that it is a workaround for a specific behavior of thread pools that needs to be documented (and is not a bug), I guess @maeste could explain that in detail if need be. There is a different way to work around it, but this is much easier. Running any test method separately works without issues, the two existing methods in Watermark test only influence themselves when run in certain order.

Regarding the sleep, yes, I don't know when exactly the work finishes, that's why it's there. I'm not against removing it, I just don't have a different solution that I'm sure will work.

I tried to keep the sleep to minimum (only while the work is being executed) and I can further cut it by lowering the work duration. I can get it from <60 sec for the three classes to <20 sec.

How should I proceed?

2017-05-17 08:42 UTC, maeste commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/LongWork.java
> +        Logger log = Logger.getLogger(this.getClass().getCanonicalName());
JGroup is not able to deserialize the logger class, it's a class loading issue.

2017-05-17 10:19 UTC, rsvoboda commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/DwmWatermarkTestCase.java
> +        Thread.sleep(LongWork.WORK_TIMEOUT + 100); // wait for the scheduled work to start and finish, so it doesn't mess up our statistics for other tests
If the sleep stays there it must be configurable (search for timeout.factor used in TS, I don't know exact details) as the timeout can be insufficient on some slow/legacy machines we still have to use. 

@ctomc can you please comment on suggested steps to make the PR mergeable ?

2017-05-18 15:07 UTC, LittleJohnII commented
I pushed changes - redundant logging has been removed, other small fixes (such as java ee version in application.xml) are also in. What remains is the `Logger` creation at each `run()` in work classes - I'll file an issue for that, and the `Thread.sleep()` - although I've added the timeout factor workaround.

2017-05-25 09:12 UTC, jmartisk commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/AbstractDwmTestCase.java
> +        properties.put(Context.INITIAL_CONTEXT_FACTORY, "org.jboss.naming.remote.client.InitialContextFactory");
Please use `org.wildfly.naming.client.WildFlyInitialContextFactory` instead

2017-05-30 09:29 UTC, kabir commented
@LittleJohnII Needs a 7.x PR to get considered

2017-05-30 09:44 UTC, LittleJohnII commented
@kabir yes, I've been reminded a few days ago by @jmartisk . It's in the works, but I'm currently stuck on https://issues.jboss.org/browse/WFLY-8843 for both upstream and downstream. I'll create the PR and put a comment here when the tests no longer hang.

2017-06-05 08:53 UTC, LittleJohnII commented
Worked around WFLY-8843 and created downstream PR https://github.com/jbossas/jboss-eap7/pull/1935. Tests pass for me.

2017-06-15 22:28 UTC, merged