[WFLY-8524] Use equals to compare owner in OwnableReentrantLock
wildfly/wildfly pull request #10211
Opened 2017-06-19 14:31 UTC by tadamski

2017-06-19 17:10 UTC, pferraro requested changes

2017-06-19 17:10 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/tx/OwnableReentrantLock.java
> +        if (owner == null) {
I suggest utilizing https://github.com/wildfly/wildfly-common/blob/master/src/main/java/org/wildfly/common/Assert.java#L69

2017-06-19 17:10 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/tx/OwnableReentrantLock.java
> +            if (owner.equals(this.owner)) {
Since we don't know the implementation of the owner object, I suggest using java.util.Objects.equals(owner, this.owner) to avoid a potential NPE.

2017-06-19 17:10 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/tx/OwnableReentrantLock.java
>      public boolean tryLock(long timeValue, TimeUnit timeUnit, Object owner) {
Add not-null assertion for owner, as we did for lock(...).

2017-06-19 17:10 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/tx/OwnableReentrantLock.java
>      public void unlock(Object owner) {
Add not-null assertion for owner, as we did for lock(...).

2017-06-19 21:02 UTC, tadamski commented
fixed

2017-06-19 23:16 UTC, pferraro requested changes

2017-06-19 23:16 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/tx/OwnableReentrantLock.java
> +            if (!owner.equals(this.owner)) {
You'll want to use Objects.equals(...) here as well, for the same reason as above.

2017-06-20 06:03 UTC, tadamski commented on ejb3/src/main/java/org/jboss/as/ejb3/tx/OwnableReentrantLock.java
> +            if (!owner.equals(this.owner)) {
sorry, missed that

2017-06-21 10:57 UTC, pferraro approved these changes

2017-11-07 00:07 UTC, stuartwdouglas approved these changes

2017-11-07 10:40 UTC, merged