WFLY-9004 Artemis leaks JGroups channels on reload
wildfly/wildfly pull request #10250
Opened 2017-06-27 17:12 UTC by rhusar

Jira
https://issues.jboss.org/browse/WFLY-9004

2017-06-27 17:13 UTC, rhusar commented
@pferraro Please review; this fixes the leak, but let me know if you think we should do this another way..

2017-06-27 20:48 UTC, pferraro requested changes

2017-06-27 20:48 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ForkChannelBroadcastEndpoint.java
> +        channel.close(true);
Future-proof this by using JChannel.close().

2017-06-27 20:48 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/DiscoveryGroupAdd.java
> +        final BroadcastEndpointFactory endpointFactory = new ForkChannelBroadcastEndpointFactory(channel, channelName);
While the channel is question is a ForkChannel by default, it is not necessarily so.  Thus the name of this class isn't quite appropriate.

2017-06-27 20:48 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ForkChannelBroadcastEndpointFactory.java
> +public class ForkChannelBroadcastEndpointFactory extends ChannelBroadcastEndpointFactory {
See above comment regarding the name.  The logic for closing the channel would be the same regardless of implementation.

2017-06-28 15:43 UTC, rhusar commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ForkChannelBroadcastEndpoint.java
> +        channel.close(true);
That would not fix the problem; firstly the wrapper uses a reference counter and only closes the channel when last consumer of the channel closes, but mainly we need to trigger org.apache.activemq.artemis.api.core.jgroups.JChannelWrapper#close which removes the reference from its internal structure.

2017-06-28 18:15 UTC, merged