[WFLY-9004] Artemis leaks JGroups channels on reload
wildfly/wildfly pull request #10319
Opened 2017-07-18 09:09 UTC by jmesnil

Refactor messaging-activemq subsystem code to create channels on demand
every time Artemis creates a JGroupsBroadcastEndpoint.

The ActiveMQServerServices track only the channels created by the discovery
groups since they can be referenced by Artemis RA (when the RA is using
JGroups to discover the Artemis servers).

2017-07-19 14:01 UTC, jmesnil commented
@pferraro Could you review this PR please?

I changed the messaging-activemq subsystem so that it creates/closes channel every time that Artemis requests it (instead to have the channels created when the server is started).
Do you see any issue with that new behaviour?
Would there be any difference if the channel is a regular channel or a `ForkChannel`?

2017-07-20 12:49 UTC, pferraro requested changes

2017-07-20 12:49 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastEndpointFactory.java
> +    private final Map<String, JChannel> channels;
Does this map serve any purpose?  Doesn't the JChannelManager already manage channel sharing by multiple endpoints?

2017-07-20 12:49 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
> +                        config = DiscoveryGroupAdd.createDiscoveryGroupConfiguration(name, entry.getValue(), channelFactory, channelName, channels);
@jmesnil Question - the intention of the previous logic seems to be that only 1 JGroups channel would be created for every unique channel name between the broadcast group and discovery groups.
This change moves the creation of the channel to the endpoint and defers the management of channel sharing between multiple endpoints to the JChannelManager.  I think that makes sense.  Ideally, a JChannel should be closed by the same object that created it.
However, this seems to render the Map<String, JChannel> in ActiveMQServerService obsolete.  Can we remove this?  The channels created by discovery group endpoints are added to this map and removed on close, but I don't see anything that ever reads from this map.

2017-07-20 12:49 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupAdd.java
> +        final BroadcastEndpointFactory endpointFactory = new JGroupsBroadcastEndpointFactory(channelName, channelFactory, new HashMap<>());
This map seems to serve no purpose other than to make JGroupsBroadcastEndpointFactory happy.

2017-07-20 12:55 UTC, pferraro commented
@jmesnil In general, I think this change makes sense.  I like that the same object that creates the channel closes it.  In the case where the ChannelFactory is a ForkChannelFactory, JChannel will still be created on startup (a ForkChannelFactory is built on top of a JChannel), but the fork channels will not be created until ActiveMQ request them from the endpoint.

2017-07-20 13:28 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
> +                        config = DiscoveryGroupAdd.createDiscoveryGroupConfiguration(name, entry.getValue(), channelFactory, channelName, channels);
You are right about the intent of the previous logic. However I was not matching Artemis expectations (which creates channels as it needs it without sharing them between its broadcast and discovery groups).

I'm not sure there is a correct use case for sharing the same channel name between discovery groups. The discovery groups would only differ by their `refresh-timeout` and `initial-wait-timeout`attributes. I don't see a compelling use case for this but it's technically acceptable...

2017-07-20 13:30 UTC, jmesnil commented
@pferraro thanks for the review. I'll change the `JGroupsBroadcastEndpointFactory` to get rid of that ugly empty Map to make it more readable that only channels created by discovery groups needs to be accessed by the Artemis RA.

2017-07-20 13:46 UTC, pferraro requested changes

2017-07-20 13:46 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastEndpointFactory.java
> +                synchronized (JGroupsBroadcastEndpointFactory.class) {
Why the funky synchronization on both the instance and the parent class?

2017-07-20 13:46 UTC, pferraro commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastEndpointFactory.java
> +                synchronized (JGroupsBroadcastEndpointFactory.class) {
Why is this synchronized on the class?  Does this need to be synchronized at all?

2017-07-21 08:50 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastEndpointFactory.java
> +                synchronized (JGroupsBroadcastEndpointFactory.class) {
fixed

2017-07-21 08:50 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/JGroupsBroadcastEndpointFactory.java
> +                synchronized (JGroupsBroadcastEndpointFactory.class) {
fixed

2017-07-21 14:41 UTC, merged