[WFLY-9386] Several tests need FilePermission for standalone/tmp/auth…
wildfly/wildfly pull request #10541
Opened 2017-09-26 16:38 UTC by treblereel

… to pass with security manager
JIRA:  https://issues.jboss.org/browse/WFLY-9386

2017-11-08 00:03 UTC, stuartwdouglas requested changes
I don't think this is necessarily the best solution. What do the errors look like? We are likely missing a privileged block somewhere.

2017-11-09 22:05 UTC, bstansberry commented
@stuartwdouglas The error stack is shown in the JIRA. It's not a @RunAsClient test so a ModelControllerClient running inside the server is trying to make a remote connection.

The call actually is in a privileged block, so the AccessControlContext passed to PrivilegedSaslClient and thus to doPrivileged must be restricting this.

I'm somewhat doubtful the client's read of the file should be done in a privileged manner. It's reading a file that some remote endpoint told it to read and will then report the file contents back to that endpoint. It's not obvious that the client should always do that.

OTOH, you could argue that if a thread has a "connect" permission that implies it can do whatever is necessary.

Also, I figure this used to work or this would have been among the many other similar permissions already added to these tests.

@dmlloyd FYI.

2018-03-17 22:26 UTC, dmlloyd approved these changes

2018-03-17 22:26 UTC, dmlloyd commented
I think this is probably fine.  We can always fix it later anyway.

2018-03-19 23:03 UTC, merged