[WFLY-9415] Add test cases to cover EJB client clustered session creation
wildfly/wildfly pull request #10566
Opened 2017-10-03 21:03 UTC by rachmatowicz

This PR adds in some test cases to cover EJB client clustered SFSB session creation. 

For details, see: https://issues.jboss.org/browse/WFLY-9415

2017-11-07 00:22 UTC, stuartwdouglas approved these changes

2017-11-07 02:20 UTC, stuartwdouglas requested changes
It looks like these cause CI failures

2018-02-05 14:23 UTC, kabir commented
@rachmatowicz looks like there could be some problems with this one?

2018-02-22 01:01 UTC, stuartwdouglas commented
Closing for now, as this has CI failures and compilation errors, and has not been updated in months. If this is updated feel free to reopen.

2018-02-22 01:01 UTC, closed without merging

2018-03-01 16:28 UTC, rhusar commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/proxycontext/ClientStatefulSessionCreationTestCase.java
> +public class ClientStatefulSessionCreationTestCase extends ClusterAbstractTestCase {
AbstractClusteringTestCase

2018-03-01 16:28 UTC, rhusar commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/proxycontext/ClientStatefulSessionCreationTestCase.java
> +@RunAsClient
Remove RunAsClient