[WFLY-9433] apply InfiniteOrPositiveValidators to messaging attributes allow valid value -1
wildfly/wildfly pull request #10577
Opened 2017-10-11 07:34 UTC by soul2zimate

https://issues.jboss.org/browse/WFLY-9433
applied for configuration parameters in:

ActiveMQClient.java
public static final long DEFAULT_CLIENT_FAILURE_CHECK_PERIOD_INVM = -1;
public static final long DEFAULT_CONNECTION_TTL_INVM = -1;
public static final int DEFAULT_CONSUMER_MAX_RATE = -1;
public static final int DEFAULT_CONFIRMATION_WINDOW_SIZE = -1;
public static final int DEFAULT_PRODUCER_MAX_RATE = -1;
public static final int DEFAULT_THREAD_POOL_MAX_SIZE = -1;

ActiveMQDefaultConfiguration.java
private static long DEFAULT_CONNECTION_TTL_OVERRIDE = -1;
private static int DEFAULT_JOURNAL_POOL_FILES = -1;
private static long DEFAULT_CONNECTION_TTL_OVERRIDE = -1;
private static int DEFAULT_JOURNAL_PERF_BLAST_PAGES = -1;
private static long DEFAULT_SERVER_DUMP_INTERVAL = -1;
private static long DEFAULT_MEMORY_MEASURE_INTERVAL = -1;
private static int DEFAULT_BRIDGE_INITIAL_CONNECT_ATTEMPTS = -1;
private static int DEFAULT_BRIDGE_RECONNECT_ATTEMPTS = -1;
private static int DEFAULT_BRIDGE_PRODUCER_WINDOW_SIZE = -1;
private static int DEFAULT_CLUSTER_INITIAL_CONNECT_ATTEMPTS = -1;
private static int DEFAULT_CLUSTER_RECONNECT_ATTEMPTS = -1;
private static int DEFAULT_HAPOLICY_BACKUP_REQUEST_RETRIES = -1;
private static int DEFAULT_GROUPING_HANDLER_GROUP_TIMEOUT = -1;

2017-10-12 02:45 UTC, soul2zimate commented
retest this please

2017-11-13 01:03 UTC, soul2zimate commented
retest this please

2017-11-20 13:59 UTC, jmesnil requested changes
Could you move the InfiniteOrPositiveValidators in the org.wildfly.extension.messaging.activemq package please?
This will prevent to import from `...jms.bridge` in the main messaging-activemq package.

Apart from that, it looks good to me, thanks!

2017-11-21 02:10 UTC, soul2zimate commented
I moved it into package org.wildfly.extension.messaging.activemq

2017-11-21 08:45 UTC, jmesnil approved these changes
Thanks!

2017-12-01 01:00 UTC, merged