WFLY-9436 Test suite misses any sort of smoke test for JSR-77 management bean availability
wildfly/wildfly pull request #10579
Opened 2017-10-12 08:40 UTC by ChesterSVK

Created simple JSR77 test for MBean functionality.
JIRA :
https://issues.jboss.org/browse/WFLY-9436

2017-10-18 15:29 UTC, rhusar requested changes
Always make sure to reference Jira ID in the SCM commit message.

2017-10-25 11:09 UTC, kabir commented
This is ok to test

2017-11-07 23:46 UTC, stuartwdouglas requested changes
This test fails.

2017-11-09 11:07 UTC, ChesterSVK commented
Fixed

2017-11-22 09:10 UTC, ChesterSVK commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jsr77/Jsr77TestCase.java
> +package org.jboss.as.test.integration.jsr77;
Added

2017-11-30 22:38 UTC, bstansberry commented
retest this please

2017-12-11 22:58 UTC, merged