Test case for WFCORE-1392
wildfly/wildfly pull request #10671
Opened 2017-11-23 14:22 UTC by TomasHofman

Test case for WFCORE-1392: Undeploy doesn't remove Data content if server is in --admin-only mode

https://issues.jboss.org/browse/WFLY-9568
WFCORE-1392 PR: https://github.com/wildfly/wildfly-core/pull/2954

2017-11-26 21:46 UTC, stuartwdouglas requested changes
This test appears to be broken

2017-11-27 15:01 UTC, TomasHofman commented
I forgot to mention, the test will wail until wildfly/wildfly-core#2954 is merged and integrated. I you prefer I can close this for now and reopen after the dependend PR is resolved.

2017-11-27 19:00 UTC, bstansberry commented
Any test for this must be part of the PR in core. It shouldn't be necessary to test this kind of thing using full WF.

2017-11-28 11:02 UTC, TomasHofman commented
For some reason I thought deployment subsystem in not really functional in wf-core. Of course wrong, gonna move this into core.

2017-11-28 11:02 UTC, closed without merging