WFLY-9710 Add Undertow specific buffer pool
wildfly/wildfly pull request #10768
Opened 2018-01-19 03:29 UTC by stuartwdouglas

2018-01-19 22:54 UTC, bstansberry commented on undertow/src/main/java/org/wildfly/extension/undertow/ByteBufferPoolDefinition.java
> +            final PathAddress address = PathAddress.pathAddress(operation.get(OP_ADDR));
final PathAddress address = context.getCurrentAddress();

2018-01-19 22:56 UTC, bstansberry commented on undertow/src/main/java/org/wildfly/extension/undertow/ByteBufferPoolDefinition.java
> +            final int bufferSize = bufferSizeModel.isDefined() ? bufferSizeModel.asInt() : defaultBufferSize;
no need to change this but just fyi this and the others can be

final int bufferSize = bufferSizeModel.asInt(defaultBufferSize);

2018-01-19 23:01 UTC, bstansberry requested changes

2018-01-19 23:01 UTC, bstansberry commented on undertow/src/main/java/org/wildfly/extension/undertow/ListenerResourceDefinition.java
> +            .setAlternatives(Constants.BYTE_BUFFER_POOL)
Is this left over from an earlier draft?

2018-02-05 12:56 UTC, kabir commented
Retest this please

2018-02-05 15:47 UTC, kabir commented
Retest this please

2018-02-13 17:16 UTC, kabir commented
@stuartwdouglas merge conflicts

2018-03-05 21:35 UTC, stuartwdouglas commented
Retest this please

2018-03-06 22:44 UTC, stuartwdouglas commented
Retest this please

2018-03-26 21:39 UTC, stuartwdouglas commented
Retest this please

2018-03-27 00:05 UTC, stuartwdouglas commented
This just implements the pools themselves, it does not change the config to make them default, as there are compatibility issues with older servers in mixed domain. I am not sure if we should just:
1) Leave this PR as is for now, and have the option of Undertow pools but XNIO still the default
2) Change the defaults, and potentially cause issues for mixed domain scenarios
3) Attempt to transform the Undertow pools to XNIO ones for older servers
4) Something else??

2018-04-11 10:24 UTC, kabir commented
@stuartwdouglas I don't think we should magically try to change the undertow pools into xnio ones for older servers.

I've not looked at the PR in any detail, mainly at your list of options, but I think we should keep the option to have xnio pools. If it is desired, the undertow ones should be made default. For transformers/mixed-domain we should reject the usage of the undertow pools. Typically the way this works is that people have a 'current' profile, and if they also need to support older HCs where new things in the 'current' profile cannot be transformed, they create an 'old' profile containing stuff that can be understood on the older HCs. This is what the DomainAdjusters in the mixed-domain testsuite do (e.g. for transformation to 6.x they remove the undertow subsystem completely and add the old web subsystem).

2018-04-11 10:36 UTC, stuartwdouglas commented
At the moment this PR just adds the option of using undertow pools, the XNIO ones stay as the default.

2018-04-12 16:12 UTC, jstourac approved these changes

2018-04-24 08:36 UTC, kabir commented
@stuartwdouglas once this is rebased (and community docs added, if it makes sense) it should be good to go

2018-04-30 09:43 UTC, kabir commented
@stuartwdouglas ^^

2018-05-01 09:36 UTC, kabir requested changes
@stuartwdouglas For completeness we should have test that the reject transformation works for both 7.1.0 and 7.0.0. 

I realise this conflicts with https://github.com/wildfly/wildfly/pull/10996#pullrequestreview-116526428 so perhaps a followup PR containing these two PRs and an extra commit to add the tests for both could work?

Also it is missing community docs.

2018-05-03 09:48 UTC, merged