[WFLY-9122] Fixed Dwm servers not in manual mode
wildfly/wildfly pull request #10765
Opened 2018-01-18 15:00 UTC by LittleJohnII

https://issues.jboss.org/browse/WFLY-9122

The dwm servers are no longer always started and should not disrupt other tests.

2018-01-18 21:20 UTC, bstansberry commented
this is ok to test

@maeste Please approve

2018-01-19 23:16 UTC, bstansberry commented
The Windows failure is in the Dwm tests so I assume it is related.

2018-01-24 09:39 UTC, LittleJohnII commented
It's definitely related. I'm looking into it, but it may take some time.

2018-02-05 15:51 UTC, kabir commented
@LittleJohnII Please @mention me when done. I've added the fixme label to not have to keep looking at this PR until that happens

2018-03-06 14:00 UTC, LittleJohnII commented
Finally got around to this.

@kabir the PR is fixed.

The issues on Windows were due to configuration from previous tests not being cleaned up properly. `File.renameTo(String)` fails on Windows if the target exists.

This time, the Linux run failed due to timeout. Is it reasonable to retest this?

2018-03-21 21:46 UTC, stuartwdouglas requested changes

2018-03-22 06:06 UTC, LittleJohnII commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/jca/workmanager/distributed/AbstractDwmTestCase.java
> - * as indicated by the @author tags. See the copyright.txt file in the
That wasn't intentional. Fixed, thanks.

2018-03-28 09:25 UTC, stuartwdouglas approved these changes

2018-03-28 23:28 UTC, merged