[WFLY-6463] Added tests for multiple @MailSessionDefinition
wildfly/wildfly pull request #10887
Opened 2018-02-15 11:40 UTC by honza-kasik

JIRA link: https://issues.jboss.org/browse/WFLY-6463
Added test for `@Repeatable` support which allows using multiple annotations of same type on one place. This test tests that use of multiple `@MailSessionDefinition` annotation is allowed and working properly.

2018-02-15 14:59 UTC, ctomc requested changes
This belongs into ee8 testsuite module. 
not separate one

2018-02-19 07:25 UTC, honza-kasik commented on testsuite/integration/mail/src/test/java/org/jboss/as/test/integration/MailServlet.java
> +            sendMessage(session1, "session1@something.test", "test@test.test", "Hello", "session1");
Thanks for revies @ctomc! Before I started, I took a look at [1], where the direct interaction with resource created by using annotation is made. Is this case different?

[1] https://github.com/wildfly/wildfly/blob/master/testsuite/integration/ee8-temp/src/test/java/org/wildfly/test/integration/ee8/commonannotations13/datasourcedefinition/RepeatableDataSourceDefinitionTestCase.java

2018-02-20 12:49 UTC, ctomc commented on testsuite/integration/mail/src/test/java/org/jboss/as/test/integration/MailServlet.java
> +            sendMessage(session1, "session1@something.test", "test@test.test", "Hello", "session1");
Yeah, I am not big fan of that and it should get removed.
Only "good" thing about that case there is that it mocks the whole thing behind the scenes. 
But it should be fixed to not test anything beyond injection.

2018-02-21 14:31 UTC, ctomc commented
I've modified this test and included it as part of https://github.com/wildfly/wildfly/pull/10920

this PR can be closed.

2018-02-21 16:57 UTC, jamezp commented
I'm closing this based on the comments and the repeatable annotations are tested in #10920.

2018-02-21 16:57 UTC, closed without merging