WFLY-9911 Move dependency managment under separate bom
wildfly/wildfly pull request #10942
Opened 2018-02-26 16:00 UTC by ctomc

https://issues.jboss.org/browse/WFLY-9911

2018-02-26 23:47 UTC, stuartwdouglas commented
Failures look related

2018-03-13 19:38 UTC, stuartwdouglas requested changes
This needs a rebase and for the failures to be fixed

2018-03-13 19:38 UTC, stuartwdouglas commented on testsuite/integration/pom.xml
> +       <!-- <dependency>
If things are no longer needed they should be removed and not commented out.

2018-03-20 10:34 UTC, kabir commented
@ctomc needs a rebase

2018-03-28 06:25 UTC, stuartwdouglas approved these changes

2018-03-28 16:01 UTC, merged