[JBEAP-14246] - EJBCLIENT-295 - Annotated EJB Client Interceptor bein…
wildfly/wildfly pull request #11033
Opened 2018-03-20 13:16 UTC by adamecp

JIRA issue [EJBCLIENT-295 - Annotated EJB Client Interceptor being called more than once](https://issues.jboss.org/browse/JBEAP-14246)

EJB Client interceptor handleInvocation and handleInvocationResult are being invoked 4 times instead of once. Reproducer attached uses @ClientInterceptors and the standalone client invokes the EJB once.

2018-03-20 21:24 UTC, stuartwdouglas requested changes
It does not look like this test is actually testing anything, just logging some output. There does not appear to be any sort of check that an interceptor is only invoked once.

2018-03-20 21:24 UTC, stuartwdouglas commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/AnnotatedEJBClientInterceptorTestCase.java
> +            Assert.fail(t.getMessage());
There is no need to do this, just let the exception leave the test method. That way if someone is trying to debug a failing test they have a whole exception stack to work with, and not just a message.

2018-03-20 21:24 UTC, stuartwdouglas commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/AnnotatedEJBClientInterceptorTestCase.java
> +        return remoteClass.cast(getInitialContext("localhost", 8080, null, null).lookup(myContext));
This should not be hard coded. You should use '@ArquillianResource URL url;' to inject a URL with the correct host and port.

2018-03-20 21:24 UTC, stuartwdouglas commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/ClientInterceptor.java
> +    log.info("In the client interceptor handleInvocation : " + this.getClass().getName() + " " + context.getViewClass() + " " + context.getLocator());
Logging should be done at debug level or lower, normal test execution should produce no log output.

2018-03-20 21:24 UTC, stuartwdouglas commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/TestSLSB.java
> +	context.getContextData().put("ClientInterceptorInvoked", clientInterceptor);
What is the purpose of this? you just pulled it out of the same map key?

2018-03-20 21:24 UTC, stuartwdouglas commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/TestSLSB.java
> +	log.info(String.format("clientInterceptorInvoked: %b %s", (clientInterceptor!=null), clientInterceptor));
should be debug

2018-03-20 21:24 UTC, stuartwdouglas commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/interceptor/annotatedejbclient/TestSLSB.java
> +	log.info("Test Invoked");
should be debug

2018-03-20 21:24 UTC, stuartwdouglas commented
This is ok to test

2018-03-22 15:55 UTC, adamecp commented
@stuartwdouglas Thanks for review. I progressed your comments.

2018-03-23 04:05 UTC, stuartwdouglas commented
Retest this please

2018-03-26 07:40 UTC, adamecp commented
@stuartwdouglas Thanks for review. I rewrite it. Now checkstyle is ok.

2018-03-26 09:07 UTC, stuartwdouglas commented
Retest this please

2018-03-26 23:38 UTC, merged