[WFLY-10069] Remove all slf4j dependencies from WildFly
wildfly/wildfly pull request #11049
Opened 2018-03-22 12:03 UTC by jmesnil

With WFCORE-3703, all SLF4J dependencies are declared in WildFly Core

JIRA: https://issues.jboss.org/browse/WFLY-10069

2018-03-22 12:03 UTC, jmesnil commented
This PR can merged after the component upgrade for wildfly-core that will incorporate https://github.com/wildfly/wildfly-core/pull/3182

2018-03-22 14:02 UTC, rsvoboda requested changes

2018-03-22 14:02 UTC, rsvoboda commented on feature-pack/src/main/resources/modules/system/layers/base/org/slf4j/ext/main/module.xml
> -        <property name="jboss.api" value="deprecated"/>
This was deprecated in EAP 7.1.0.
For EAP 6.4.0 and 7.0.0 it was public module.

This cannot be removed now

2018-03-22 14:45 UTC, rsvoboda commented on feature-pack/src/main/resources/modules/system/layers/base/org/slf4j/ext/main/module.xml
> -        <property name="jboss.api" value="deprecated"/>
ah, it's move of slf4j stuff to wf-core, not total removal. Ignore my comment please.

https://github.com/wildfly/wildfly-core/pull/3182/files#diff-0267876148955d4bc36a55f5c9fae951R25

2018-03-22 15:26 UTC, jamezp commented
@mkouba Does Weld still use `ch.qos.cal10n`?

2018-03-22 15:45 UTC, mkouba commented
@jamezp No, it doesn't.. for a long time.

2018-03-22 16:37 UTC, jamezp approved these changes

2018-03-29 09:33 UTC, gaol commented
Looks like the slf4j artifacts are back again at [component-matrix/pom.xml](https://github.com/wildfly/wildfly/blob/master/component-matrix/pom.xml#L219-L222) when fixing https://issues.jboss.org/browse/WFLY-9911

2018-03-29 21:28 UTC, kabir commented
Retest this please

2018-03-29 21:29 UTC, kabir commented
@jmesnil needs a rebase

2018-03-30 10:05 UTC, jmesnil commented
retest this please

2018-04-03 16:12 UTC, merged