WFLY-9648 Expose configuration for non-blocking initial state transfer for replicated/distributed caches
wildfly/wildfly pull request #11069
Opened 2018-03-28 18:08 UTC by pferraro

https://issues.jboss.org/browse/WFLY-9648

Also, WFLY-9764 Fix description of state transfer chunk-size
https://issues.jboss.org/browse/WFLY-9648

Design: wildfly/wildfly-proposals#11

2018-03-28 22:01 UTC, rhusar requested changes

2018-03-28 22:01 UTC, rhusar commented on clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_6_0.xsd
> +  ~ Copyright 2011, Red Hat, Inc., and individual contributors
2018*

2018-04-03 11:41 UTC, kabir commented
@pferraro adding the 'hold' label until @mvinkler has done Test Dev

2018-04-17 21:30 UTC, rhusar approved these changes

2018-05-02 13:15 UTC, tommaso-borgato commented
Test Plan is complete

2018-05-11 20:10 UTC, merged