[WFLY-10209] changes made to use -secmgr flag and revised jboss-modul…
wildfly/wildfly pull request #11114
Opened 2018-04-11 20:28 UTC by rsearls

…es settings

https://issues.jboss.org/browse/WFLY-10209

2018-04-12 11:45 UTC, rsearls commented on feature-pack/src/main/resources/content/bin/appclient.bat
> +echo(!JAVA_OPTS! | findstr /r /c:"-Dsecmgr" > nul
I used ./bin/domain.sh and ./bin/standalone.sh as the model when upgrading wsconsume and wsprovide with the secmgr changes.

2018-04-12 23:16 UTC, stuartwdouglas commented
Failure is unrelated and should be fixed by https://github.com/wildfly/wildfly/pull/11120

2018-04-16 08:50 UTC, marekkopecky commented on feature-pack/src/main/resources/content/bin/appclient.sh
> +# remove -secmgr from JAVA_OPTS. This flag must reside in a different location
+1, [standalone.sh](https://github.com/wildfly/wildfly-core/blob/master/core-feature-pack/src/main/resources/content/bin/standalone.sh) script doesn't contain removing `-secmgr` from `JAVA_OPTS`

2018-04-16 08:55 UTC, marekkopecky commented on feature-pack/src/main/resources/content/bin/appclient.bat
> +echo(!JAVA_OPTS! | findstr /r /c:"-Dsecmgr" > nul
domain and standalone scripts don't use `-Dsecmgr` option, these scripts uses only `-secmg` option or `SECMGR` env property, see [script sources on wf-core github repo](https://github.com/wildfly/wildfly-core/tree/master/core-feature-pack/src/main/resources/content/bin), for example: there is some explanation [here](https://github.com/wildfly/wildfly-core/blob/master/core-feature-pack/src/main/resources/content/bin/standalone.bat#L40)

2018-05-10 19:42 UTC, n1hility commented
retest this please

2018-05-10 23:59 UTC, rsearls commented
Testing complete.  All is good.

2018-05-11 08:31 UTC, marekkopecky requested changes
According to the @jamezp 's [jira comment](https://issues.jboss.org/browse/WFLY-10242?focusedCommentId=13561804&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13561804), we should not allow -secmgr in the JAVA_OPTS. It's not a valid JVM argument ...

2018-05-11 12:19 UTC, rsearls commented
This issue appears to remain under discussion.  There is no clear agreement yet.  I suggest allowing this
PR to be merged so that jbossws-cxf can remain working.  In the future a new PR can be posted with agreed upon changes to these scripts.  Any changes to jbossws-cxf scripts will require corresponding changes in the jbossws-cxf and its testsuite.

2018-05-11 13:16 UTC, marekkopecky commented
> I suggest allowing this PR to be merged so that jbossws-cxf can remain working

This PR updates only appclient scripts ... can you please explain, how this appclient change can fix jbossws-cxf? Maybe also @asoldano can provide some details ...

2018-05-11 16:31 UTC, rsearls commented
jbossws-cxf has testsuite tests for appclient, wsconsume an wsprovide, that is what I was referring to.

2018-05-11 16:39 UTC, jamezp submitted a review, later dismissed
I don't think we should allow `-secmgr` to be in the `JAVA_OPTS`. The other scripts do not allow that as it's a JBoss Modules only argument. It's not a valid JVM argument.

2018-05-11 16:53 UTC, rsearls commented
I suggest we move this discussion into the jira so we can have a record of it.
https://issues.jboss.org/browse/WFLY-10209

2018-05-14 08:58 UTC, marekkopecky commented
Hi Rebecca, 

I check the discussion on https://issues.jboss.org/browse/WFLY-10242

Thank you for your new changes, this PR basically fixes WFLY-10209, WFLY-10242 and WFLY-10241 for .sh and .bat scripts.

I have two comments:

* AFAICS changes in appclient.* are useless, but AFAIK these changes doesn't cause any regression  ...
* PowerShell scripts needs to be updated too (@dmlloyd point this out earlier on this PR). I hope Process-Script-Parameter function from common.ps1 script (located in wf-core) could be usefull here.

2018-05-14 17:33 UTC, rsearls commented
Were is the source code for common.ps1?

2018-05-14 17:44 UTC, dmlloyd commented
https://github.com/wildfly/wildfly-core/blob/master/core-feature-pack/src/main/resources/content/bin/common.ps1

2018-05-14 19:04 UTC, rsearls commented
Squashed current changes to unify handling of -secmgr flag in jbossws related scripts.  This PR is now dependent on PR https://github.com/wildfly/wildfly-core/pull/3301.  A function was added to common.ps1
that appclient.ps1 now calls.

2018-05-15 05:54 UTC, marekkopecky commented
`wsconsume.ps1` and `wsprovide.ps1` scripts needs to be updated too ...

2018-05-16 08:16 UTC, marekkopecky commented
Hi Rebecca,

I checked wsconsume.ps1 script on Windows machines. It seems that `-secmgr` option and `SECMGR` env property doesn't enable security manager. Can you please check it?

Basically, I use this without any policy file, I expect AccessControlException, but scripts ends without AccessControlException:
```
.\wsconsume.ps1 -secmgr  https://raw.githubusercontent.com/jbossws/jbossws-cxf/master/modules/testsuite/shared-tests/src/test/resources/jaxws/smoke/tools/wsdl/TestServiceSoap12.wsdl
```
```
$env:SECMGR = "true"
.\wsconsume.ps1 https://raw.githubusercontent.com/jbossws/jbossws-cxf/master/modules/testsuite/shared-tests/src/test/resources/jaxws/smoke/tools/wsdl/TestServiceSoap12.wsdl
```

2018-05-27 01:20 UTC, rsearls commented
The issues raised have been address however the current push of code changes is dependent on 
https://issues.jboss.org/browse/WFCORE-3892
PR: https://github.com/wildfly/wildfly-core/pull/3327

2018-06-04 10:01 UTC, marekkopecky commented on feature-pack/src/main/resources/content/bin/appclient.conf.bat
> +if not "x%JAVA_OPTS%" == "x" {
This duplicates line 15 of appclient.conf.bat

2018-06-04 10:12 UTC, marekkopecky commented on feature-pack/src/main/resources/content/bin/appclient.sh
> -        # MacOS does not support -server flag
Is there some reason for removing MacOS support?

2018-06-04 11:42 UTC, marekkopecky commented
@rsearls I try to start wsconsume.ps1 script with this PR and https://github.com/wildfly/wildfly-core/pull/3327

wsconsume.ps1 doesn't work for me, can you please check it?
```
PS C:\Users\Administrator\playground\wfly.18\wildfly\bin> .\wsconsume.ps1 https://raw.githubusercontent.com/jbossws/jbossws-cxf/master/modules/testsuite/shared-tests/src/test/resources/
jaxws/smoke/tools/wsdl/TestServiceSoap12.wsdl
Start-WildFly-Process : Cannot bind argument to parameter 'programArguments' because it is an empty string.
At C:\Users\Administrator\playground\wfly.18\wildfly\bin\wsconsume.ps1:22 char:41
+ Start-WildFly-Process -programArguments $PROG_ARGS
+                                         ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-WildFly-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Start-WildFly-Process

PS C:\Users\Administrator\playground\wfly.18\wildfly\bin>
```

2018-06-04 17:33 UTC, rsearls commented
Please don't do any testing of  wildfly/wildfly#11114  until the following 3 WFCORE PRs have been merged.
WFCORE-3830, https://github.com/wildfly/wildfly-core/pull/3333; 
WFCORE-3825, https://github.com/wildfly/wildfly-core/pull/3334;
WFCORE-3892, https://github.com/wildfly/wildfly-core/pull/3327;

2018-08-02 12:05 UTC, kabir commented
@rsearls @asoldano what is the status of this? I see that a lot of the core PRs have not been merged yet

2018-08-02 12:06 UTC, kabir commented
@rsearls @asoldano Adding the hold label to avoid having to look at this again and again. Please @mention me when all is in order

2018-08-02 12:29 UTC, rsearls commented
Waiting for access to Windows machine to test and fix reported issue with one pending PR.  Other PRs may rely on it.

2018-08-09 14:00 UTC, rsearls commented
This PR is no longer dependent on WFCORE-3830, #3333; or WFCORE-3825, #3334;
It is dependent only on WFCORE-3892, #3327;

Here is an Win env with #11114 and #3327 to show these changes work.
rdesktop -g 90% 10.33.144.121 -0 -u Administrator -p admin -k en-us

2018-08-10 07:08 UTC, marekkopecky commented on feature-pack/src/main/resources/content/bin/appclient.sh
> -        # MacOS does not support -server flag
@rsearls ^^^

2018-08-10 09:10 UTC, marekkopecky commented
@rsearls Basically, this PR should fix these 3 jiras, right?
* https://issues.jboss.org/browse/WFLY-10209
* https://issues.jboss.org/browse/WFLY-10241
* https://issues.jboss.org/browse/WFLY-10242

2018-08-10 12:19 UTC, marekkopecky commented
I prepare WF based on this PR and https://github.com/wildfly/wildfly-core/pull/3327/ (all changes with this PR and https://github.com/wildfly/wildfly-core/pull/3327/ included)

I test ps1 and bat scripts on Windows:

```
PS C:\Users\Administrator\playground\wfly.22\wildfly\bin> .\wsconsume.bat -h
WSConsumeTask is a cmd line tool that generates portable JAX-WS artifacts from a WSDL file.

usage: wsconsume.bat [options] <wsdl-url>
...
```
```
PS C:\Users\Administrator\playground\wfly.22\wildfly\bin> .\wsprovide.bat -h
WSProvideTask generates portable JAX-WS artifacts for an endpoint implementation.

usage: wsprovide.bat [options] <endpoint class name>
...
```
```
PS C:\Users\Administrator\playground\wfly.22\wildfly\bin> .\appclient.bat -h
Calling "C:\Users\Administrator\playground\wfly.22\wildfly\bin\appclient.conf.bat"
05:10:44,252 INFO  [org.jboss.modules] (main) JBoss Modules version 1.8.5.Final
The appclient script starts an application client which can be used to test and access the deployed EJBs.
Usage: appclient [args...]
...
```
```
PS C:\Users\Administrator\playground\wfly.22\wildfly\bin> .\wsconsume.ps1 -h
Start-WildFly-Process : Cannot bind argument to parameter 'programArguments' because it is an empty string.
At C:\Users\Administrator\playground\wfly.22\wildfly\bin\wsconsume.ps1:22 char:41
+ Start-WildFly-Process -programArguments $PROG_ARGS
+                                         ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-WildFly-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Start-WildFly-Process
```
```
PS C:\Users\Administrator\playground\wfly.22\wildfly\bin> .\wsprovide.ps1 -h
Start-WildFly-Process : Cannot bind argument to parameter 'programArguments' because it is an empty string.
At C:\Users\Administrator\playground\wfly.22\wildfly\bin\wsprovide.ps1:22 char:41
+ Start-WildFly-Process -programArguments $PROG_ARGS
+                                         ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-WildFly-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Start-WildFly-Process
```
```
PS C:\Users\Administrator\playground\wfly.22\wildfly\bin> .\appclient.ps1 -h
Jbossws-Get-Java-Arguments : Cannot process argument transformation on parameter 'javaOpts'. Cannot convert value to type System.String.
At C:\Users\Administrator\playground\wfly.22\wildfly\bin\appclient.ps1:26 char:119
+ ...   -entryModule "org.jboss.as.appclient"  -javaOpts $JAVA_OPTS -server ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Jbossws-Get-Java-Arguments], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Jbossws-Get-Java-Arguments

Start-WildFly-Process : Cannot bind argument to parameter 'programArguments' because it is null.
At C:\Users\Administrator\playground\wfly.22\wildfly\bin\appclient.ps1:28 char:41
+ Start-WildFly-Process -programArguments $PROG_ARGS
+                                         ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Start-WildFly-Process], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Start-WildFly-Process
```

@rsearls Can you please double check?

2018-08-10 18:29 UTC, rsearls commented
$PROG_ARGS  issue fixed

2018-08-21 20:50 UTC, jamezp commented on feature-pack/src/main/resources/content/bin/appclient.bat
> +    set outParam=%outParam% "%~1"
Should this be `set "outParam=%outParam% %~1"`. Quoting the entire `set`.

2018-08-21 20:50 UTC, jamezp commented on feature-pack/src/main/resources/content/bin/appclient.bat
> +set SERVER_OPTS=%outParam%
This may need to be `set "SERVER_OPTS=%outParam%"`.

2018-08-21 20:50 UTC, jamezp commented on feature-pack/src/main/resources/content/bin/wsconsume.bat
> +echo(%JAVA_OPTS% | findstr /r /c:"-Djava.security.manager" > nul && (
If the `EnabledDelayedExpansion` is set a `!` needs to be used instead of `%`.

2018-08-21 20:50 UTC, jamezp commented on feature-pack/src/main/resources/content/bin/wsconsume.bat
> +set SERVER_OPTS=%*
_Maybe_ this needs to be quoted. `set "%SERVER_OPTS%=%*"`. I'm not 100% certain though.

2018-08-21 20:50 UTC, jamezp commented on feature-pack/src/main/resources/content/bin/wsprovide.bat
> +set SERVER_OPTS=%*
Same comment about maybe needing to be quoted. I know Windows can be picky about spaces which is why I think we generally quote the sets.

2018-10-18 18:56 UTC, jamezp commented
I'm closing this based on https://issues.jboss.org/browse/WFLY-10209?focusedCommentId=13650216&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13650216 and https://issues.jboss.org/browse/WFLY-10241?focusedCommentId=13650190&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13650190

Sorry for all the confusion around this @rsearls. I may be missing something, but IMO we don't need the `wsconsume` and `wsproduce` scripts to run under the security manager. The `appclient` and `standalone` scripts already do.

2018-10-18 18:56 UTC, closed without merging