[WFLY-9818] xts adding element to enable async endpoints registration
wildfly/wildfly pull request #11123
Opened 2018-04-13 08:51 UTC by ochaloup

https://issues.jboss.org/browse/WFLY-9818

this is for .NET integration with Narayana WS-AT. The related Narayana jira is here:
https://issues.jboss.org/browse/JBTM-2928

The content of this PR is enabling the new WS endpoints needed for WS-AT async handling. The endpoints are registred if new element `<async-registration enabled="true" />` is added under the XTS subsystem.

I will be really glad for any comment about the subsystem change where the new element is added (I'm not sure about the best practices in this area). Thanks.

2018-04-13 21:40 UTC, stuartwdouglas commented
Looks like this does not compile

2018-04-16 07:53 UTC, ochaloup commented
@stuartwdouglas ouch, sorry and thanks. My last time refactoring, caused by fixing my IDE order of imports changes, caused I forgot to apply local-copy code additions. Now it should be working.

2018-04-25 09:53 UTC, ochaloup commented
@stuartwdouglas how should I proceed about get review and possibly this get merged? would you give me hint who can I ask for looking at the code? Thanks!

2018-05-21 08:09 UTC, ochaloup commented
The issue should be verified. @kabir is there something more to do for this PR would be mergable? Thanks.

2018-06-04 06:28 UTC, ochaloup commented
hi @kabir , as the WFLY 13 was released can you, please, reconsider merging of these changes to the WFLY? Or what is the missing part for this could be merged? Many thanks.

2018-06-07 08:20 UTC, ochaloup commented
I've rebased to stay up to date.

2018-06-07 10:37 UTC, kabir commented on xts/src/main/java/org/jboss/as/xts/XTSSubsystemParser.java
> +    private void parseAsyncRegistrationElement(XMLExtendedStreamReader reader, ModelNode subsystem) throws XMLStreamException {
You need to throw an error about an unexpected error if the namespace version is < 2.1

2018-06-07 10:39 UTC, kabir commented on xts/src/main/java/org/jboss/as/xts/XTSSubsystemParser.java
> +    private interface AtribbuteProcessor<T, R> {
Nitpick: Typo

2018-06-07 10:43 UTC, kabir commented on xts/src/main/java/org/jboss/as/xts/XTSSubsystemTransformers.java
>             TransformationDescription.Tools.register(builder.build(), subsystem, ModelVersion.create(1, 1, 0));
You also need to transform for the attribute for old version 2.1.0. I recommend looking for usage of ChainedTransformationDescriptionBuilder to make it easier to add transformers in one place going forward.

2018-06-07 10:46 UTC, kabir requested changes
@ochaloup I've (finally) reviewed this. You are missing transformation to 2.0.0, as mentioned. Then you need to improve the transformers tests to:
* Test for transformation to 2.0.0
* The existing transformer tests, and the new one then need to test:
** a config that should work
** a config that is expected to be rejected (see usage of FailedOperationTransformationConfig in tests)

If you are not familiar with this stuff you can ask me

2018-06-13 12:49 UTC, ochaloup commented
@kabir thanks for the review and pointing me to the missing pieces. I tried to provide what you asked me for. As you pointed out I'm not much familiar with this. I will be glad for your further feedback.
Anyway I updated the transformer and tuned the tests a bit. Please, let me know. Thank you.

2018-06-22 08:49 UTC, kabir commented
Retest this please

2018-06-25 08:34 UTC, merged