[JBEAP-14561] - fix appclient boot service deps and test case
wildfly/wildfly pull request #11215
Opened 2018-05-14 05:47 UTC by baranowb

Upstream: https://issues.jboss.org/browse/WFLY-10333
7.1.x: https://issues.jboss.org/browse/JBEAP-14561

Upstream:
7.1.x: https://github.com/jbossas/jboss-eap7/pull/2645

2018-05-15 01:56 UTC, stuartwdouglas approved these changes

2018-05-15 05:01 UTC, stuartwdouglas requested changes
This should be under a WFLY JIRA, not JBEAP

2018-05-16 05:34 UTC, stuartwdouglas approved these changes

2018-05-21 02:51 UTC, gaol commented
Retest failed please

2018-05-21 14:11 UTC, merged