[WFLY-10475] JSF installer module definitions are not synced with JSF…
wildfly/wildfly pull request #11316
Opened 2018-06-05 17:25 UTC by treblereel

JIRA: https://issues.jboss.org/browse/WFLY-10475

2018-06-06 12:53 UTC, kabir commented
@fjuma Please approve

2018-06-06 14:18 UTC, fjuma requested changes

2018-06-06 14:18 UTC, fjuma commented on jsf/multi-jsf-installer/src/main/resources/mojarra-injection-module.xml
> +        <module name="org.jboss.as.ee"/>
The "org.jboss.as.ee" dependency is already listed below.

2018-06-06 14:18 UTC, fjuma commented on jsf/multi-jsf-installer/src/main/resources/myfaces-injection-module.xml
> +<module xmlns="urn:jboss:module:1.8" name="org.jboss.as.jsf-injection" slot="${jsf-impl-name}-${jsf-version}">
Dependencies on the "org.jboss.as.jsf" module and on the "org.jboss.weld.api" module should be added to the dependencies in this file as well.

2018-06-06 14:18 UTC, fjuma commented on jsf/multi-jsf-installer/src/main/resources/mojarra-injection-module.xml
> +        <module name="org.jboss.as.ee"/>
The "org.jboss.as.ee" module dependency is already listed below.

2018-06-06 17:12 UTC, fjuma approved these changes
Thanks @treblereel!

2018-06-07 08:43 UTC, merged

2018-07-19 03:46 UTC, erickdeoliveiraleal commented
there's some differences in module.xml between myfaces and mojarra.
eg.:  <module name="org.jboss.weld.core"/>
        <module name="org.jboss.weld.spi"/>
        <module name="javax.faces.api"/>
is it right? when wildfly starts it complains about.

> Using deployment classloader to load proxy classes for module com.sun.jsf-impl:myfaces-2.3.1. Package-private access will not work. To fix this the module should declare dependencies on [org.jboss.weld.core, org.jboss.weld.spi]