[WFLY-10550] rovide a profile to run enforcer rule for downstream projects
wildfly/wildfly pull request #11342
Opened 2018-06-12 08:33 UTC by gaol

Jira: https://issues.jboss.org/browse/WFLY-10550

Added a profile `enforce-product` to check redhat dependencies

This is an enhancement mainly for downstream product usage. It is disabled by default in upstream, which means it won't affect community builds at all.

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

2018-06-12 12:49 UTC, kabir requested changes
@gaol I am pretty sure this also needs adding to galleon-pack and servlet-galleon-pack. Also, since you have something to fix there is a typo in the commit message :)

2018-06-13 03:44 UTC, gaol commented
@kabir Thank you for the review. I updated it with galleon-pack and servlet-galleon-pack, and fixed the typo in the commit message. :smile:

2018-06-13 08:35 UTC, kabir commented
@gaol I thought of something since I was going through the CD13 pom yesterday. There are several unproductised dependencies, but these are generally for test dependencies and in some cases provided dependencies. Does the BanVersionDependenciesRule take that into account?

2018-06-13 08:52 UTC, gaol commented
@kabir The BanVersionDependenciesRule won't skip test and provided dependencies by default, so it will ban such dependencies if they are not productised.

I add the rule into the `*-pack` modules which are the distributions, and I think there are no such dependencies in those modules.

I don't think it is time to enable this rule for `CD13` branch yet, because I think there are no productised dependencies yet. The main purpose will be targeting the CP stream.

2018-06-13 08:56 UTC, kabir commented
@gaol right, so there isn't any rush since we're effectively targetting 14. @aloubyansky has some idea of perhaps doing this more in Galleon for the galleon pack varieties, so let's see what he comes up with

2018-06-19 13:50 UTC, merged