[WFLY-6224] Fix exception handling in StatefulSessionSynchronizationInterceptor to avoid IllegalStateException
wildfly/wildfly pull request #11469
Opened 2018-07-30 14:50 UTC by rachmatowicz

This pull request does the following:
* adjusts the exception handling in StatefulSessionSynchronizationInterceptor to take account of how an exception can effect the way in which a stateful session bean cache instance is released

Wildfly JIRA: https://issues.jboss.org/browse/WFLY-6224
EAP JIRA: https://issues.jboss.org/browse/JBEAP-3432

2018-07-30 20:44 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulSessionSynchronizationInterceptor.java
> +                } catch (Error e) {
Since exception handling is the same for both Error and Throwable, you should combine these into a multi-catch:
catch (Error | Throwable e) { ... }

2018-07-31 08:17 UTC, kabir commented
@rachmatowicz adding the fixme label until @pferraro 's concerns have been addressed. Also, who from QE should be pinged?

2018-07-31 15:05 UTC, rhusar commented
@rachmatowicz Could the 2 cluster test case now be enabled? If not, what are the remaining issues?

2018-08-02 16:40 UTC, rachmatowicz commented
@kabir who can be pinged in QE is @tommaso-borgato , who has taken over from Michal Winkler for clustering QE.

As for testing, I have run the branch against the 2 cluster test case variants in the wildfly testsuite (NonTxClientEJBForwardingTestCase, ..., which are currently disabled). Those tests passed. 

I also ran the branch against a (distributed) SmartFrog failover test; those tests passed as well. The only other test which would be worth running is the (distributed) SmartFrog version of the 2-cluster test case; this is in fact the test case which highlighted these errors in the first place.

2018-08-02 16:43 UTC, rhusar requested changes

2018-08-02 16:43 UTC, rhusar commented on ejb3/src/main/java/org/jboss/as/ejb3/component/stateful/StatefulSessionSynchronizationInterceptor.java
> +                    throw t ;
Extraneous space.

2018-08-02 22:31 UTC, rachmatowicz commented
Fixed a space error and re-enabled execution of the test case. After discussion with Paul, we opted to leave the catch clauses as they are.

2018-08-03 01:16 UTC, pferraro commented
> As for testing, I have run the branch against the 2 cluster test case variants in the wildfly testsuite (NonTxClientEJBForwardingTestCase, ..., which are currently disabled). Those tests passed.

@rachmatowicz Can you re-enable those tests as part of this PR?

2018-08-03 08:51 UTC, tommaso-borgato commented
@rachmatowicz at the moment 2clusters tests are broken because of this issue: [WFLY-9896](https://issues.jboss.org/browse/WFLY-9896);
Anyway I run [perflab_eap-7x-failover-ejb-2clusters-ejbremote-shutdown-repl-async](https://jenkins.hosts.mwqe.eng.bos.redhat.com/hudson/job/perflab_eap-7x-failover-ejb-2clusters-ejbremote-shutdown-repl-async/) with your version (run 36) and latest Wildfly master branch version (run 38) and the errors observed are almost the same in type and number but being them about 4000 in number it is hard to tell precisely; I am not sure it helps because of this "JBREM000308: Authentication failed" affecting the client; what more I can do is to setup the 2 cluster on my local machine (the error should vanish) but it would take more time and I wouldn't be able to do a proper test with failover and many clients firing simultaneously; but if it helps I can do it; let me know

2018-08-03 13:17 UTC, rachmatowicz commented
OK, there were two test failures relating to the 2-cluster tests. I'm going to re-disable the 2-cluster tests and start to debug the remaining errors, which are almost certainly a separate issue.  

I'm also going to change the logging  that occurs during the test because, given the test setup, it is almost impossible to know which cluster topology changes are occurring before the test starts and which are occurring during the test.

2018-08-03 13:57 UTC, rhusar commented
@rachmatowicz Yeah, I am afraid the test will need to stay disabled. Regarding logs, all that logging should be in the debug logs.

2018-08-03 14:43 UTC, rachmatowicz commented
I have disabled the 2-cluster tests, as it seems there are other issues which this test case presents that need to be addressed. I have also changed  the logging levels as it is very difficult to know which topology changes occur before the test has started and which occur during the test.

2018-08-03 14:56 UTC, rhusar approved these changes

2018-08-08 20:39 UTC, merged