[WFLY-10949] IllegalArgumentException when get jdbc driver info if xa-datasource-class is not defined
wildfly/wildfly pull request #11618
Opened 2018-08-30 02:51 UTC by gaol

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

Jira: https://issues.jboss.org/browse/WFLY-10949

Checking whether the `driver-xa-datasource-class-name` is defined when run command:
`/subsystem=datasources:get-installed-driver(driver-name=xxx)`

2018-09-03 04:43 UTC, gaol commented
@maeste could you please review? Thanks. :)

2018-09-03 07:41 UTC, maeste approved these changes

2018-09-11 19:45 UTC, kabir requested changes

2018-09-11 19:45 UTC, kabir commented on testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/mgmt/datasource/DataSourceOperationsUnitTestCase.java
> +        } finally {
@gaol You should probably test that 'driver-xa-datasource-class-name' equals "" as well?

2018-09-12 07:38 UTC, gaol commented
@kabir that makes sense, thanks. I updated it. :)

2018-11-07 16:47 UTC, jamezp approved these changes

2018-11-09 00:49 UTC, merged