[WFLY-11005]: Requires connectors for broadcast-group resource.
wildfly/wildfly pull request #11660
Opened 2018-09-12 11:53 UTC by ehsavoie

Making connectors required.
Jira: https://issues.jboss.org/browse/WFLY-11005

2018-09-18 09:45 UTC, kabir requested changes
@ehsavoie This needs a model version bump as you are changing the model and 14.0.0.Final was released with these as not required.

BTW I haven't checked in detail, but I think I saw one of the Jiras linked to from WFLY-11005 mentioning that this also needs doing for DiscoveryGroup.

2018-09-20 16:07 UTC, pferraro commented
@ehsavoie The problem with the current broadcast/discovery group resources is they have ambiguous requirement specifications.  Really, they each need to be split into 2 different resources.  This is the goal of https://issues.jboss.org/browse/WFLY-10339.
I don't think you can/should make the jgroups-cluster and socket-bindings required as these are mutually exclusive attributes.

2018-09-20 20:05 UTC, ehsavoie commented
@pferraro being required but also alternatives means that only one has to be defined thus I don't see how that would block WFLY-10339 transformation since I expect those resources either to have socket-binding or jgroups-cluster. But maybe we should focus on WFLY-10339 before doing this one

2018-09-20 22:29 UTC, pferraro commented
> being required but also alternatives means that only one has to be defined
Ok, that's good to know. In that case, there's no issue, but given that I'm planning to address WFLY-10339 for WF15, this PR should be made redundant soon.

2018-09-24 16:13 UTC, kabir commented
@ehsavoie @pferraro Adding the hold label after skimming the discussion. If I am wrong please let me know

2018-09-26 09:39 UTC, jmesnil requested changes

2018-09-26 09:39 UTC, jmesnil commented on legacy/messaging/src/main/java/org/jboss/as/messaging/logging/MessagingLogger.java
> +    @Message(id = 89, value = "Can not migrate discovery group %s. as no network configuration is properly defined.")
should be `discovery group %s as no` (no dots)

2018-09-26 09:39 UTC, jmesnil commented on legacy/messaging/src/main/java/org/jboss/as/messaging/logging/MessagingLogger.java
> +    @Message(id = 90, value = "Can not migrate broadcast group %s. as no network configuration is properly defined.")
idem

2018-09-26 09:39 UTC, jmesnil commented on legacy/messaging/src/test/java/org/jboss/as/messaging/test/MigrateTestCase.java
> +        System.out.println("Response " + response);
must be removed

2018-09-26 09:39 UTC, jmesnil commented on legacy/messaging/src/test/java/org/jboss/as/messaging/test/MigrateTestCase.java
> +        // 3 warnings about broadcast-group not migrated because they don't have a proper network configuration.
Which are the 3 broadcast-groups that can not be migrated?

There is `groupA` and `groupB` (that uses `group-address` & `group-port` attributes) but `groupS` and `groupT` looks fine.

2018-09-26 09:39 UTC, jmesnil commented on legacy/messaging/src/test/java/org/jboss/as/messaging/test/MigrateTestCase.java
> +        // 3 warnings about discovery-group not migrated because they don't have a proper network configuration.
same remark

2018-09-26 09:39 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/BroadcastGroupDefinition.java
> +            .setRequired(true)
You should also `.setMinSize(1)` so that an empty list is not accepted

2018-10-02 08:17 UTC, jmesnil approved these changes

2019-02-26 17:46 UTC, bstansberry commented
@ehsavoie @jmesnil Early in WF 17 work lets either close this or rebase it and do anything needed to get the 'hold' label removed.

2019-02-26 21:09 UTC, ehsavoie commented
This should be closed as we discussed it during the f2f. I'll keep it until WF16 is out

2019-07-30 18:21 UTC, jamezp commented
I'm closing this based on the comments. If I'm understanding this incorrectly please rebase and reopen.

2019-07-30 18:21 UTC, closed without merging