[WFLY-9106]: Hard-code default values in messaging-activemq subsystem.
wildfly/wildfly pull request #11672
Opened 2018-09-17 12:54 UTC by ehsavoie

Replacing ActiveMQClient., ActiveMQDefaultConfiguration default values usage by hardcoded values in the messaging subsystem.

JIRA: https://issues.jboss.org/browse/WFLY-9106

2018-09-17 16:48 UTC, kabir submitted a review, later dismissed
@ehsavoie There is a checkstyle problem

2018-09-19 10:19 UTC, kabir commented
[amq-master.txt](https://github.com/wildfly/wildfly/files/2396553/amq-master.txt)
[amq-pull.txt](https://github.com/wildfly/wildfly/files/2396555/amq-pull.txt)
@ehsavoie amq-master.txt contains a r-r-d for the subsystem built from master. amq-pull.txt contains r-r-d built from this PR. There are some differences.

{code}
$diff -u amq-master.txt amq-pull.txt 
--- amq-master.txt	2018-09-19 11:06:06.000000000 +0100
+++ amq-pull.txt	2018-09-19 11:04:39.000000000 +0100
@@ -1120,7 +1120,7 @@
                             "expressions-allowed" => true,
                             "required" => false,
                             "nillable" => true,
-                            "default" => 10485760,
+                            "default" => 10485760L,
                             "unit" => "BYTES",
                             "min" => 1024L,
                             "max" => 9223372036854775807L,
@@ -1273,7 +1273,7 @@
                             "expressions-allowed" => true,
                             "required" => false,
                             "nillable" => true,
-                            "default" => -1,
+                            "default" => 10,
                             "access-type" => "read-write",
                             "storage" => "configuration",
                             "restart-required" => "all-services"
@@ -2241,7 +2241,7 @@
                                         "expressions-allowed" => true,
                                         "required" => false,
                                         "nillable" => true,
-                                        "default" => 1.0,
+                                        "default" => big decimal 1,
                                         "access-type" => "read-write",
                                         "storage" => "configuration",
                                         "restart-required" => "all-services"
@@ -2600,7 +2600,7 @@
                                             "expressions-allowed" => true,
                                             "required" => false,
                                             "nillable" => true,
-                                            "default" => 5000L,
+                                            "default" => 5000,
                                             "unit" => "MILLISECONDS",
                                             "access-type" => "read-write",
                                             "storage" => "configuration",
@@ -2691,7 +2691,7 @@
                                                         "expressions-allowed" => true,
                                                         "required" => false,
                                                         "nillable" => true,
-                                                        "default" => 30000L,
+                                                        "default" => 30000,
                                                         "unit" => "MILLISECONDS",
                                                         "access-type" => "read-write",
                                                         "storage" => "configuration",
@@ -2834,7 +2834,7 @@
                                                         "expressions-allowed" => true,
                                                         "required" => false,
                                                         "nillable" => true,
-                                                        "default" => 30000L,
+                                                        "default" => 30000,
                                                         "unit" => "MILLISECONDS",
                                                         "access-type" => "read-write",
                                                         "storage" => "configuration",
@@ -2892,7 +2892,7 @@
                                             "expressions-allowed" => true,
                                             "required" => false,
                                             "nillable" => true,
-                                            "default" => 30000L,
+                                            "default" => 30000,
                                             "unit" => "MILLISECONDS",
                                             "access-type" => "read-write",
                                             "storage" => "configuration",
@@ -3145,7 +3145,7 @@
                                             "expressions-allowed" => true,
                                             "required" => false,
                                             "nillable" => true,
-                                            "default" => 30000L,
+                                            "default" => 30000,
                                             "unit" => "MILLISECONDS",
                                             "access-type" => "read-write",
                                             "storage" => "configuration",
@@ -3275,7 +3275,7 @@
                                             "expressions-allowed" => true,
                                             "required" => false,
                                             "nillable" => true,
-                                            "default" => 5000L,
+                                            "default" => 5000,
                                             "unit" => "MILLISECONDS",
                                             "access-type" => "read-write",
                                             "storage" => "configuration",
@@ -4089,7 +4089,7 @@
                                         "expressions-allowed" => true,
                                         "required" => false,
                                         "nillable" => true,
-                                        "default" => 1.0,
+                                        "default" => big decimal 1,
                                         "access-type" => "read-write",
                                         "storage" => "configuration",
                                         "restart-required" => "all-services"
@@ -5441,7 +5441,7 @@
                                         "expressions-allowed" => true,
                                         "required" => false,
                                         "nillable" => true,
-                                        "default" => 1.0,
+                                        "default" => big decimal 1,
                                         "access-type" => "read-write",
                                         "storage" => "configuration",
                                         "restart-required" => "all-services"
@@ -5916,7 +5916,7 @@
                                         "expressions-allowed" => true,
                                         "required" => false,
                                         "nillable" => true,
-                                        "default" => 1.0,
+                                        "default" => big decimal 1,
                                         "access-type" => "read-write",
                                         "storage" => "configuration",
                                         "restart-required" => "all-services"
@@ -5991,7 +5991,7 @@
                                         "expressions-allowed" => true,
                                         "required" => false,
                                         "nillable" => true,
-                                        "default" => 2000L,
+                                        "default" => 2000,
                                         "unit" => "MILLISECONDS",
                                         "access-type" => "read-write",
                                         "storage" => "configuration",
@@ -7534,7 +7534,7 @@
                             "expressions-allowed" => true,
                             "required" => false,
           [...]

2018-09-19 11:42 UTC, ehsavoie commented
1. Please note that the type of the attribute is LONG 
2. is wrong
3. it is correct, please note that we set the value to 10 in our configurations
4. 'big decimal 1' just looks weird :) can't agree more but it is the type defined in the subsystem BIG_DECIMAL. I could use a simple double value for it.

2018-09-20 12:02 UTC, jmesnil commented
failures are related to the PR

2018-09-20 12:22 UTC, jmesnil requested changes
I don't understand why the model version and XSD had to change to replace Artemis constants with hard-code values?

2018-09-20 12:36 UTC, ehsavoie commented on galleon-pack/src/main/resources/feature_groups/messaging-activemq-ha.xml
> -            <param name="journal-pool-files" value="10"/>
this value is the default one, so removing it makes sense

2018-09-20 13:12 UTC, ehsavoie commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
> +        ResourceTransformationDescriptionBuilder server = subsystem.addChildResource(MessagingExtension.SERVER_PATH);
ok

2018-09-20 13:12 UTC, ehsavoie commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
> +            .setDefaultValue(new ModelNode(new SimpleString("activemq.management").toString()))
ok

2018-09-20 13:13 UTC, ehsavoie commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
> -    private static final ModelVersion CURRENT_MODEL_VERSION = VERSION_4_0_0;
Ok, will do the version bump in a separate PR

2018-09-21 07:15 UTC, ehsavoie commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingExtension.java
> -    private static final ModelVersion CURRENT_MODEL_VERSION = VERSION_4_0_0;
Ok, will do the version bump in a separate PR https://github.com/wildfly/wildfly/pull/11678

2018-09-21 07:16 UTC, ehsavoie commented
Everything should be fixed

2018-09-26 08:59 UTC, jmesnil approved these changes

2018-09-26 15:11 UTC, kabir commented
@ehsavoie needs a rebase

2018-09-28 14:01 UTC, merged