[WFLY-10796] Warning about JSF version 'NONE' is shown in logs
wildfly/wildfly pull request #11683
Opened 2018-09-24 18:15 UTC by treblereel

JIRA: https://issues.jboss.org/browse/WFLY-10796

2018-09-25 09:59 UTC, kabir commented
@fjuma please approve

2018-09-25 14:00 UTC, fjuma requested changes
@treblereel Thanks for working on this. From the description in the JIRA, it sounds like the deployment isn't trying to specify a custom JSF version so the warning message should not occur. Are you able to see what is causing the warning message to be displayed? It doesn't get displayed for a regular JSF WAR so must be related to the reproducer being an EAR.

2018-09-25 14:39 UTC, kabir commented
@treblereel @fjuma I am adding the hold label while the investigation happens. Ping me when this can be merged

2018-10-24 17:24 UTC, fjuma approved these changes

2018-10-30 17:42 UTC, merged