WFLY-9447 NPE in ejb client and clean shutdown
wildfly/wildfly pull request #11699
Opened 2018-09-26 22:09 UTC by rhusar

Jira
https://issues.jboss.org/browse/WFLY-9447

2018-09-27 10:18 UTC, rhusar commented
@pferraro Please approve.

2018-09-27 11:59 UTC, pferraro requested changes
One minor nitpick, but otherwise looks good.

2018-09-27 11:59 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/deployment/DeploymentRepositoryService.java
> +    public DeploymentRepository getValue() throws IllegalStateException, IllegalArgumentException {
You can drop these from the throws clause.  Not only are they not thrown, but they are RuntimeExceptions.

2018-09-27 11:59 UTC, pferraro commented on ejb3/src/main/java/org/jboss/as/ejb3/deployment/DeploymentRepositoryService.java
> +public class DeploymentRepositoryService implements DeploymentRepository, Service<DeploymentRepository> {
:+1: Excellent.  WF has too many poorly encapsulated services that expose the Service interface to consumers.

2018-09-27 16:30 UTC, pferraro approved these changes

2018-09-27 22:08 UTC, merged

2018-10-05 10:12 UTC, tommaso-borgato commented
@rhusar I re-run the affected test and the error does not occur any more

2018-10-05 10:18 UTC, rhusar commented
@tommaso-borgato Great, thanks.