[WFLY-11197] Add capability to bean-validation; use it in JSF and JPA…
wildfly/wildfly pull request #11752
Opened 2018-10-17 01:14 UTC by bstansberry

… to make module dependency optional

https://issues.jboss.org/browse/WFLY-11197

2018-10-17 16:18 UTC, bstansberry commented on jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
> +            if (!ValidationMode.NONE.equals(pu.getValidationMode()) && css.hasCapability("org.wildfly.bean-validation")) {
I'm going to correct this to deal with ValidationMode.CALLBACK

2018-10-17 19:36 UTC, fjuma approved these changes

2018-10-18 23:29 UTC, jamezp approved these changes

2018-10-18 23:30 UTC, jamezp commented
@bstansberry Are we still doing the capability registry for all these?

2018-10-19 12:55 UTC, scottmarlow commented on jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
> +                    // In any case the hasCapability check above that accompanied this comment
From the current JPA 2.2 spec, it sounds like the persistence provider would do any validation, I don't think we need the null check:

3.6.1.1 Enabling Automatic Validation

The validation-mode element of the persistence.xml file determines whether the automatic
lifecycle event validation is in effect. The values of the validation-mode element are AUTO,
CALLBACK, NONE. The default validation mode is AUTO.

If the application creates the entity manager factory using the Persistence.createEntityMan-
agerFactory method, the validation mode can be specified using the javax.persis-
tence.validation.mode map key, which will override the value specified (or defaulted) in the
persistence.xml file. The map values for this key are "auto", "callback", "none".

If the auto validation mode is specified by the validation-mode element or the javax.persis-
tence.validation.mode property, or if neither the validation-mode element nor the
javax.persistence.validation.mode property is specified, and a Bean Validation provider
is present in the environment, the persistence provider must perform the automatic validation of entities
as described in section 3.6.1.2. If no Bean Validation provider is present in the environment, no lifecy-
cle event validation takes place.

If the callback validation mode is specified by the validation-mode element or the javax.per-
sistence.validation.mode property, the persistence provider must perform the lifecycle event
validation as described in section 3.6.1.2. It is an error if there is no Bean Validation provider present in
the environment, and the provider must throw the PersistenceException if the javax.per-
sistence.validation.mode property value "callback" has been passed to the Persis-
tence.createEntityManagerFactory method.

If the none validation mode is specified by the validation-mode element or the javax.per-
sistence.validation.mode property, the persistence provider must not perform lifecycle event
validation.
"

2018-10-19 13:00 UTC, scottmarlow commented on jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
> +                    // In any case the hasCapability check above that accompanied this comment
Other than the unneeded null check, I think the rest is fine.

2018-10-19 13:05 UTC, scottmarlow requested changes
remove null check.

2018-10-19 13:05 UTC, scottmarlow commented on jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitServiceHandler.java
> +                if (validatorFactory == null && ValidationMode.CALLBACK.equals(pu.getValidationMode())) {
remove unneeded null check and comment, see below comment about how validation factory is only passed in to persistence provider if its available in the environment.

2018-10-19 17:55 UTC, merged