[WFLY-11179]:  Messaging http-acceptor should expose a capability and use it to control dependencies.
wildfly/wildfly pull request #11796
Opened 2018-10-31 16:21 UTC by ehsavoie

* Adding a capability and a requirement on http-upgrade-registry

JIRA: https://issues.jboss.org/browse/WFLY-11179

2018-11-01 16:18 UTC, kabir commented
Should be fine, if CI passes

2018-11-01 17:07 UTC, ehsavoie commented
requires core upgrade

2018-11-07 19:11 UTC, jamezp commented
retest this please

2018-11-08 00:20 UTC, bstansberry commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPAcceptorDefinition.java
> +    public static final RuntimeCapability<Void> CAPABILITY = RuntimeCapability.Builder.of("org.wildfly.messaging.activemq", true, HTTPUpgradeService.class)
This can be package protected.

2018-11-08 00:26 UTC, bstansberry requested changes

2018-11-08 08:35 UTC, ehsavoie commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/HTTPAcceptorDefinition.java
> +    public static final RuntimeCapability<Void> CAPABILITY = RuntimeCapability.Builder.of("org.wildfly.messaging.activemq", true, HTTPUpgradeService.class)
Fixed

2018-11-08 23:55 UTC, bstansberry approved these changes

2018-11-10 00:28 UTC, merged