[WFLY-11328] EE Concurency Utilities hung-task-threshold / long-runni…
wildfly/wildfly pull request #11837
Opened 2018-11-12 11:42 UTC by JiriOndrusek

…ng-tasks do not work and are not implemented as explained

Issue: https://issues.jboss.org/browse/WFLY-11328

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

2018-11-12 11:47 UTC, JiriOndrusek commented
I'm aware that in PR's code there is a call of deprecated method (addDependency), but with it it is consistent with the rest of the code.

@emmartins May I ask for your opinion on this PR? It adds a small functionality into code mostly written by you...

2018-11-13 10:28 UTC, kabir requested changes
@JiriOndrusek one minor problem I can see.

@emmartins if you are still familiar can you please check it quickly?

2018-11-13 11:02 UTC, emmartins commented
I can check it after lunch

On Tue, 13 Nov 2018 at 10:28, Kabir Khan <notifications@github.com> wrote:

> *@kabir* requested changes on this pull request.
>
> @JiriOndrusek <https://github.com/JiriOndrusek> one minor problem I can
> see.
>
> @emmartins <https://github.com/emmartins> if you are still familiar can
> you please check it quickly?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly/pull/11837#pullrequestreview-174290818>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAg8eAC5X01TkldsfB0_O0KWbfELt4gzks5uup7OgaJpZM4YZe6_>
> .
>

2018-11-13 11:53 UTC, kabir commented on ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedScheduledExecutorServiceService.java
> +            for(ManagedScheduledExecutorServiceImpl service : managedScheduledExecutorServices) {
@JiriOndrusek  It isn't. A synchronized list only guards the gets and adds, not the iteration. You should create a copy of the list in a synchronized block and then iterate the copy (which can happen outside the synchronized block).

2018-11-13 11:56 UTC, JiriOndrusek commented on ee/src/main/java/org/jboss/as/ee/concurrent/service/ManagedScheduledExecutorServiceService.java
> +            for(ManagedScheduledExecutorServiceImpl service : managedScheduledExecutorServices) {
@kabir Yes, I've currently found it in docs, I see problem you are talking about. Thanks for pointing itout, I'll wait for @emmartins's response and then fix it.

2018-11-13 17:30 UTC, emmartins commented
1. Any synchronisation here is not desirable, best effort checks would be fine
2. IMHO a timer interfering with all running threads every 10s is a very bad idea
That's regarding this specific PR, honestly I don't really like the idea of killing threads based on config no matter how implemented, I believe we should aim for a different non intrusive use of such functionality in RI, and fix docs.

2019-07-30 20:49 UTC, jamezp commented
I'm closing this PR until it's decided what should be done here if anything.

2019-07-30 20:49 UTC, closed without merging