[WFLY-11360] Revert previous take on exposing TransationSynchronizationRegistry via a capability using ContextTransactionSynchronizationRegistry; instead complete that part of WFLY-11166 using a standard  Service-installing capability
wildfly/wildfly pull request #11852
Opened 2018-11-16 02:33 UTC by bstansberry

https://issues.jboss.org/browse/WFLY-11360
https://issues.jboss.org/browse/WFLY-11166

2018-11-16 17:01 UTC, bstansberry commented
@pferraro 1) Does this look ok? See WFLY-11360 for why what I did before re ContextTransactionSynchronizationRegistry is no good.  2) Do you have any sense the failures in "Linux" and "Windows" CI jobs are related?  I see lots of clustering failures lately.

2018-11-16 17:15 UTC, pferraro commented
@bstansberry I'll have a look in a minute.
Those failure are unrelated and are due to https://issues.jboss.org/browse/ISPN-9701, for which an upstream fix should arrive shortly.  We were previously inoculated against this by lifecycle locking in the distributed session manager which was dropped by https://github.com/wildfly/wildfly/commit/88f0cd5bd076ebbbf6fa501c8afa294a7706b063

2018-11-16 17:26 UTC, pferraro requested changes
This is technically fine, although I've suggested some tweaks.

2018-11-16 20:09 UTC, bstansberry commented on clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TransactionServiceConfigurator.java
> +    private volatile Supplier<TransactionSynchronizationRegistry> tsrSupplier;
Thanks, Paul; I'll make all these changes.

2018-11-16 20:44 UTC, scottmarlow commented
I'm not sure of a quick/easy way to add a unit test, so will try building/manually testing the current pr (will repeat after code changes)

2018-11-16 20:58 UTC, scottmarlow commented
JCAOrderedLastSynchronizationList#registerInterposedSynchronization was called to register the JPA container (org.jboss.as.jpa.transaction.TransactionUtil$SessionSynchronization) sync and JCA (org.jboss.jca.core.connectionmanager.transaction.TransactionSynchronizer) sync, which means this PR addresses the  WFLY-11360 regression.

2018-11-16 22:29 UTC, bstansberry commented
@scottmarlow Thanks!  I just updated this to reflect incorporate the inputs from @pferraro.  That shouldn't change any behavior though; it was all in one infinispan extension class and was just a change to use a couple helper classes in place of some handwritten code.

2018-11-17 02:18 UTC, pferraro approved these changes
Clustering changes approved.

2018-11-22 12:15 UTC, kabir commented
@maeste Can you approve the jca changes?

2018-11-22 14:16 UTC, maeste approved these changes

2018-11-22 14:26 UTC, merged