[WFLY-11388] User is not informed about incorrect values in exposed-s…
wildfly/wildfly pull request #11998
Opened 2019-01-13 05:23 UTC by gaol

…ubsystems for MP Metrics

Jira: https://issues.jboss.org/browse/WFLY-11388

- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

The proposed fix will check exposed-subsystems on both server boots and update on the exposed-subsystems attribute.

2019-02-07 13:18 UTC, rsvoboda commented
Linked PR for EAT doesn't make sense to me, it's just copy&paste of the test from this PR.

2019-05-31 16:57 UTC, jamezp commented
@jmesnil The issue has a priority of critical, could you please review this?

2019-06-05 09:56 UTC, jmesnil requested changes

2019-06-05 09:56 UTC, jmesnil commented on microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemDefinition.java
> +        return Arrays.asList(SECURITY_ENABLED);
That is not correct. this method must return all attributes of the resource. 

If you provide a specific read-write handlers for exposed-subsystems, you also have to register other attributes (such as `security-enabled`) in the `registerAttributes` method.

2019-06-05 09:56 UTC, jmesnil commented on microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/MicroProfileMetricsSubsystemDefinition.java
> +                validExposedSubsystems(context, model.getModel());
I'm not sure this works.

When the validation is called on the write-attribute op, the value of the attribute is in the `value` property.
However the `validExposedSubsystem` will read from the `exposed-subsystems` property (which is correct for the `:add` operation.

2019-12-19 12:57 UTC, darranl commented
Changes were requested back in June but no subsequent updates to the PR, I am going to close this for now please either re-open or resubmit after considering the review comments.

2019-12-19 12:57 UTC, closed without merging

2019-12-26 06:28 UTC, gaol commented
I am so sorry that I missed this one, will come back to this issue soon :)

2020-01-07 09:37 UTC, gaol commented
suppressed by https://github.com/wildfly/wildfly/pull/11998