[WFLY-11684][WFLY-11687][WFLY-11607] component upgrades to fix remote transaction propagation issues
wildfly/wildfly pull request #12050
Opened 2019-02-08 16:21 UTC by ochaloup

https://issues.jboss.org/browse/WFLY-11687
https://issues.jboss.org/browse/WFLY-11684
https://issues.jboss.org/browse/WFLY-11607

The fix for the transaction timeout propagation error was done in two components (jboss ejb client and the wfly transaction client). That's why the component upgrades.
The reason of the changes in the integration testsuite is the different handling of timeouted transaction in wftc as it was so far. For more details please check the discussion at https://issues.jboss.org/browse/WFTC-54?focusedCommentId=13677791#comment-13677791

2019-02-11 19:08 UTC, bstansberry requested changes

2019-02-11 19:08 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/mdb/timeout/TransactionTimeoutQueueSetupTask.java
> +    ModelNode amqServerDefaultAdress = new ModelNode().add(ClientConstants.SUBSYSTEM, "messaging-activemq")
This should be a private constant or just created in the needed methods.

2019-02-11 19:08 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/mdb/timeout/TransactionTimeoutQueueSetupTask.java
> +        ModelNode address = amqServerDefaultAdress.add("address-setting", "queue." + queueName);
This add method mutates the target ModelNode, so you need to clone it before adding if you're using a shared object.

2019-02-11 19:08 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/transaction/mdb/timeout/TransactionTimeoutQueueSetupTask.java
> +        ModelNode address = amqServerDefaultAdress.add("address-setting", "queue." + queueName);
This add method mutates the target ModelNode, so you need to clone it before adding if you're using a shared object.

2019-02-11 22:18 UTC, bstansberry commented
@ochaloup I want to merge this today as I'd like the upgrades in tonight. Can you send up a PR to address my minor test comments?

2019-02-12 03:00 UTC, merged

2019-02-12 03:00 UTC, bstansberry commented
@ochaloup Sorry; my last comment was unclear. I meant please send up a separate PR as I'm merging this one.

2019-02-12 15:21 UTC, ochaloup commented
thanks @bstansberry. @istudens fixed my ommisions in the PR https://github.com/wildfly/wildfly/pull/12059. Sorry for the errors here.