WFLY-11678: managed threads creation with factory's classloader
wildfly/wildfly pull request #12099
Opened 2019-02-21 04:41 UTC by emmartins

JIRA: https://issues.jboss.org/browse/WFLY-11678

2019-02-21 04:41 UTC, emmartins commented
@jamezp wdyt?

2019-02-21 16:05 UTC, jamezp requested changes
This doesn't look right to me. We don't want to set the TCCL to the CL that created the thread. The simplest solution here is to just set the TCCL to `null` in the `run()` method.

```
@Override
public void run() {
    try {
        if (securityIdentity != null) {
            securityIdentity.runAs(super::run);
        } else {
            super.run();
        }
    } finally {
        setContextClassLoader(null);
    }
}
```

That said I think we need to look at all the `SetupContextHandle`'s and the `ResetContextHandle`'s. There could be, I have not looked, some of them that use `ThreadLocal`'s that we need to look at. It might make sense to execute these handles in the `ElytronManagedThread.run()`. Again though we'd need to spend some time looking at that.

Either way this doesn't look right to me. I think setting the TCCL to `null` is the correct thing to do.

2019-02-21 16:21 UTC, emmartins commented
The real issue is that executor service threads stay alive on run(), if they were just used once for a single task there would be no leak at all...

2019-02-21 16:22 UTC, emmartins commented
@jamezp can you please point to which CL setup doesn't look right to you?

2019-02-21 17:15 UTC, jamezp commented
@emmartins Both places where the TCCL is set don't look correct to. Also we're already in the thread itself so we should just set the threads context not through the `Thread.currentThread()`.

I don't necessarily think the handlers are wrong BTW. We just need to determine we're not leaking other things on these threads is all. Setting the context class loader to `null` on the current thread seems okay as the handlers will take care of the rest during setup.

2019-02-22 16:55 UTC, jamezp commented
retest this please

2019-02-22 16:56 UTC, jamezp commented on ee/src/main/java/org/jboss/as/ee/concurrent/service/ElytronManagedThreadFactory.java
> +        fccl = WildFlySecurityManager.getCurrentContextClassLoaderPrivileged();
It probably makes sense to just use the `org.jboss.as.ee` module class loader here instead of hoping we get the right one.

2019-02-22 21:53 UTC, emmartins commented
retest this please

2019-02-22 22:26 UTC, jamezp commented
This unfortunately is being blocked by https://issues.jboss.org/browse/WFLY-11769. If we merge this as is the `SecurityIdentity` used will be from the `SecurityDomain` associated with the `org.jboss.as.ee` module.

2019-02-22 23:01 UTC, emmartins commented
Please unblock cause executor service tasks are also wrapped with security
info, so when executed the task is ok. Some sort of leak is possible tho,
but not related with this issue.

On Fri, 22 Feb 2019 at 22:26, James R. Perkins <notifications@github.com>
wrote:

> This unfortunately is being blocked by
> https://issues.jboss.org/browse/WFLY-11769. If we merge this as is the
> SecurityIdentity used will be from the SecurityDomain associated with the
> org.jboss.as.ee module.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly/pull/12099#issuecomment-466570105>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAg8eEGv-bLCKpgL-OYx_dyMgJYmRghzks5vQG6rgaJpZM4bGpBc>
> .
>

2019-02-22 23:09 UTC, jamezp approved these changes

2019-02-23 00:59 UTC, merged