WFLY-11752 testsuite/integration/elytron uses directly a jboss.dist d…
wildfly/wildfly pull request #12094
Opened 2019-02-20 13:39 UTC by OndrejKotek

…ir when set instead of its copy in the target dir

https://issues.jboss.org/browse/WFLY-11752

When the jboss.dist property is set for the mvn command, the testsuite/integration/elytron project uses directly a server distribution in the jboss.dist directory instead of its copy in the target/wildfly directory, and the distribution is customized with the modify-elytron-config.cli script.
As a result, when running the test suite in the elytron mode (-Delytron), the next testing module (compat) fails.

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ x ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ x ] Pull Request contains link to the JIRA issue(s)
- [ x ] Pull Request contains description of the issue(s)
- [ x ] Pull Request does not include fixes for issues other than the main ticket
- [ x ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

2019-02-21 08:27 UTC, OndrejKotek commented
@bstansberry WDYT please?

2019-03-21 22:30 UTC, bstansberry commented
@OndrejKotek I don't know if this is right or not for the jboss.dist case but since that's not a particularly relevant case for normal WildFly testing and nothing changes for the !jboss.dist case, I'm fine with this if it works for you. 

Needs a rebase though.

2019-03-22 12:14 UTC, OndrejKotek commented
@bstansberry, thank you, the jboss.dist case works for me, rebased.

2019-03-22 15:57 UTC, bstansberry approved these changes

2019-04-05 03:09 UTC, bstansberry commented
retest this please

2019-04-15 01:08 UTC, bstansberry requested changes
Tests fail now.

2019-04-18 07:20 UTC, OndrejKotek commented
@bstansberry Fixed.

2019-04-22 22:51 UTC, bstansberry approved these changes

2019-04-24 22:45 UTC, merged