[WFLY-11911] Remove READ_TIMEOUT from cannel configuration options
wildfly/wildfly pull request #12187
Opened 2019-03-27 16:40 UTC by tmiyargi

Issue: https://issues.jboss.org/browse/WFLY-11911

READ_TIMEOUT cannot be set as channel option as sample configuration is missleading.

2019-03-27 17:09 UTC, bstansberry requested changes
The equivalent change needs to be made in ejb3/src/main/resources/subsystem-templates/ejb3.xml

That file drives what ends up in build-legacy and dist-legacy, which we're still maintaining as an aid in checking the the build output from our Galleon-based builds is doing what we expect.

2019-03-27 17:15 UTC, bstansberry commented
@chengfang @tadamski FYI. This change is correct; i.e. other options besides the ones mentioned in the JIRA have no effect so we shouldn't put them in our standard config.

@tmiyargi Can you update the JIRA description with more info why only the listed ones are meaningful? It's not obvious and that will save people researching. AIUI it's because org.jboss.remoting3.remote.RemoteReadListener, the ultimate consumer of the options, only processes the ones you listed.

2019-04-02 21:16 UTC, bstansberry approved these changes

2019-04-04 09:32 UTC, tadamski approved these changes

2019-04-04 18:24 UTC, merged