[WFLY-9954] Fixing too many services and dependencies created for EJBs issue
wildfly/wildfly pull request #12215
Opened 2019-04-05 21:00 UTC by ropalka

https://issues.jboss.org/browse/WFLY-9954

Moving component related JNDI dependencies from o.j.a.s.d.Attachments.JNDI_DEPENDENCIES
 to  o.j.a.s.d.Attachments.COMPONENT_JNDI_DEPENDENCIES attachment.
Before this fix JNDI_DEPENDENCY_SERVICE had too many dependencies.
With this fix applied JNDI_DEPENDENCY_SERVICE will now depend on
JNDI_AGGREGATION_SERVICES and these aggregation services
will reference COMPONENT_JNDI_DEPENDENCIES that were referenced
by JNDI_DEPENDENCY_SERVICE before. In other words we are decreasing
JNDI_DEPENDENCY_SERVICE dependencies count and reorganizing (simplifying)
its dependency tree.

2019-04-09 17:01 UTC, bstansberry requested changes
Just restating what this does, in case I'm wrong: This adds a service per component but by doing so reduces the number of dependencies another service has by replacing 5 dependencies with 1 dependency.

2019-04-09 20:34 UTC, ropalka commented on ee/src/main/java/org/jboss/as/ee/component/deployers/EEModuleInitialProcessor.java
> +import java.util.HashMap;
Fixed

2019-04-09 20:34 UTC, ropalka commented on ee/src/main/java/org/jboss/as/ee/naming/InApplicationClientBindingProcessor.java
> +        final Set<ServiceName> jndiDependencies = jndiComponentDependencies.computeIfAbsent(contextServiceName, k-> new HashSet<>());
Fixed

2019-04-09 20:38 UTC, ropalka commented
Correct @bstansberry but we are replacing not 5 but just 4 dependencies with one intermediary aggregating dependency. This will allow us to deploy more than 7000 EJBs per deployment since now on.

2019-04-09 22:31 UTC, bstansberry approved these changes
I count 5; two in TransactionJndiBindingProcessor. ;)

2019-04-10 07:40 UTC, ropalka commented
You're of course right @bstansberry . I shouldn't even make elementary counting if I'm tired :)

2019-04-14 18:43 UTC, merged