[WEJBHTTP-23] EJB contextData not sent back to client in response when using EJB over HTTP
wildfly/wildfly pull request #12224
Opened 2019-04-12 10:58 UTC by jbaesner

[WEJBHTTP-23] EJB contextData not sent back to client in response when using EJB over HTTP
- added ClientInterceptorReturnDataEjbOverHttpTestCase

This PR only contain the respective test case... 

Jira: https://issues.jboss.org/browse/WEJBHTTP-23

2019-04-16 13:26 UTC, kabir commented
@jbaesner The test failures look related

2019-07-30 19:17 UTC, bstansberry commented
retest this please

2019-07-30 19:19 UTC, bstansberry commented
@chengfang or @tadamski please review

2019-07-30 23:21 UTC, tadamski approved these changes

2019-07-30 23:28 UTC, tadamski requested changes
The test is OK but it tests the feature that was introduced in wildfly-http-client 1.0.16.Final (already in master).

@jbaesner could you please rebase on top of current WildFly HEAD?

2019-08-05 12:37 UTC, jbaesner commented
> The test is OK but it tests the feature that was introduced in wildfly-http-client 1.0.16.Final (already in master).
> 
> @jbaesner could you please rebase on top of current WildFly HEAD?

Done...

2019-12-19 13:24 UTC, darranl commented
Retest this please

2019-12-19 13:25 UTC, darranl commented
Looking at the comments requested actions were performed but the PR has ended up stalling, will see where we are with CI and see if a merge is possible.

2020-08-11 07:47 UTC, darranl requested changes
I have just kicked off CI again as this looks like something that should be ready to go in but can you please update the commit message to reference a WFLY Jira issue.

2021-01-02 20:01 UTC, boris-unckel commented
@jbaesner I think it's WFLY-8449 to reference here and a rebase is missing.

2021-01-04 08:36 UTC, jbaesner commented
> @jbaesner I think it's WFLY-8449 to reference here and a rebase is missing.

Hi @boris-unckel , thanks for the heads up. I rebased to the latest upstream master, but I believe the reference to WEJBHTTP-23 is still valid, as the change only adds a test case for the change made for that Jira...

2021-04-08 15:55 UTC, darranl commented
@jbaesner Please update the commit message to reference a WFLY Jira issue, you are proposing a code change to the WFLY repository so a WFLY issue should be used to track that change even if the component is just "TestSuite".

There is no problem retaining the WEJBHTTP issue reference in addition to the WFLY issue.

2021-04-12 10:38 UTC, jbaesner commented
> @jbaesner Please update the commit message to reference a WFLY Jira issue, you are proposing a code change to the WFLY repository so a WFLY issue should be used to track that change even if the component is just "TestSuite".
> 
> There is no problem retaining the WEJBHTTP issue reference in addition to the WFLY issue.

@darranl the commit message is now updated, do I need to update the PR as well?

2021-04-12 14:26 UTC, darranl commented
Thank you @jbaesner - I have updated the title so it contains both issues as this ends up in the commit history as well.  I think we just have one CI job to complete and we can double check if this is ready to go.

2021-04-23 11:03 UTC, darranl approved these changes

2021-04-23 11:04 UTC, darranl commented
@tadamski Do you want one more look at this one?  I think we are ready to get this in.

2021-05-03 12:33 UTC, tadamski approved these changes
LGTM

2021-05-06 00:41 UTC, bstansberry commented
/retest

2021-05-26 03:29 UTC, merged