WFLY-12006 EJB3 IIOP attributes enable-by-default and use-qualified-name should be required
wildfly/wildfly pull request #12237
Opened 2019-04-18 05:58 UTC by soul2zimate

https://issues.jboss.org/browse/WFLY-12006

Update attributes enable-by-default and use-qualified-name to required.
Because enable-by-default and use-qualified-name must be required during parsing at https://github.com/wildfly/wildfly/blob/16.0.0.Final/ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3Subsystem12Parser.java#L227

2019-04-22 22:41 UTC, bstansberry requested changes
EJB3IIOPAdd can be cleaned up a bit too; in performBoottime when it reads these values it should assign to 'boolean' variables, not 'Boolean'.

Technically the EJB subsystem management API version should be bumped for this, but, meh. I think it was never possible to effectively not define these if the resource was added.

2019-04-22 22:41 UTC, bstansberry commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPResourceDefinition.java
> +                    .setRequired(true)
Please remove the 'true' from L57 as that says the opposite of this setRequired(true).

2019-04-22 22:41 UTC, bstansberry commented on ejb3/src/main/java/org/jboss/as/ejb3/subsystem/EJB3IIOPResourceDefinition.java
> +                    .setRequired(true)
Please remove the 'true' from L64 as that says the opposite of this setRequired(true).

2019-04-23 03:06 UTC, soul2zimate commented
Thanks, I have updated as per review request. I also removed opposite optional value "true" in three other classes.

2019-04-24 18:28 UTC, bstansberry approved these changes

2019-04-24 22:49 UTC, merged