[WFLY-12038]: Expose the enable1Prefixes configuration on external (pooled) connection factories.
wildfly/wildfly pull request #12288
Opened 2019-05-14 12:53 UTC by ehsavoie

* Adding a new attribute 'enable-amq1-prefix' on external connection
factories to override the use of those compatibility prefixes when connecting to a remote artemis broker.

Jira: https://issues.jboss.org/browse/WFLY-12038

Depends on PR: #12150

2019-05-14 13:56 UTC, kabir commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/MessagingTransformerRegistration.java
> +        rejectDefinedAttributeWithDefaultValue(subsystem.addChildResource(PathElement.pathElement(POOLED_CONNECTION_FACTORY)), ConnectionFactoryAttributes.External.ENABLE_AMQ1_PREFIX);
I have checked these with Emmanuel and these are correct

2019-05-14 19:43 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Connect_a_pooled-connection-factory_to_a_Remote_Artemis_Server.adoc
> +Please note that if you are connecting to an Artemis 2.x the old prefixes may not be used anymore for queues and topics.
1) This should explain what's meant by these prefixes, an example or something. It's not covered earlier in the document.
2) This should state that by default WildFy will prepend the prefix.

2019-05-21 15:43 UTC, jamezp approved these changes

2019-05-21 21:24 UTC, bstansberry requested changes

2019-05-21 21:24 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Connect_a_pooled-connection-factory_to_a_Remote_Artemis_Server.adoc
> +In Artemis 1.x topics and queues used had a prefix(jms.topic. and jms.queue.) that were prepended to the destiantion name.
s/used had/used to have/g
s/destiantion/destination

2019-05-21 21:24 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Connect_a_pooled-connection-factory_to_a_Remote_Artemis_Server.adoc
> +In Artemis 2.x this is no longer the case, but for compatibility reasons WildFly still prepend those prefixes and tells Artemis to run in compatibility mode.
s/prepend/prepends

should this be "tells any embedded Artemis server to run in compatibility mode"?  So WF deals with embedded but with remote Artemis you may need this setting.

2019-05-22 16:11 UTC, bstansberry approved these changes
I still have an unaddressed question about the doc but that can come later.

2019-05-22 16:15 UTC, merged