WFLY-12071: use management name for deployment address
wildfly/wildfly pull request #12295
Opened 2019-05-15 09:45 UTC by michpetrov

Issue: [WFLY-12071](https://issues.jboss.org/browse/WFLY-12071)

Deployments are stored under their management name, not the file name. When the two are different metrics cannot be retrieved.

2019-05-15 20:12 UTC, jamezp commented
These failures definitely seem related. I'm not sure, for compatibility purposes, this will work.

2019-05-15 21:05 UTC, bstansberry commented on microprofile/metrics-smallrye/src/main/java/org/wildfly/extension/microprofile/metrics/deployment/DeploymentMetricService.java
> +            return createDeploymentAddressPrefix(deploymentUnit.getParent()).append(SUBDEPLOYMENT, deploymentUnit.getAttachment(Attachments.MANAGEMENT_NAME));
I'm pretty sure removing the change to this line will fix the problem.

I don't think a subdeployment has this attachment, and in any case a subdeployment never has a management name that is different from deploymentUnit.getName(). A user can't assign a management name to a subdeployment as it's an internal part of the top level deployment, not something independently added to the server config.

2019-05-15 21:10 UTC, bstansberry commented
@jamezp The problem he's fixing here is definitely something that needs fixing. The code generates a management model address and if a runtime name is used and it's different from the management name, that will be an invalid address.

Whether an external consumer of metrics would want the runtime name as part of a metric label rather than the management name is a good question. The general reason they'd differ would be if the mgmt name were foo.war_v2 or something. That's a point for @jmesnil but in any case it seems trying to use runtime name doesn't work.

2019-05-15 21:10 UTC, bstansberry commented
@michpetrov This needs a test case.

2019-05-15 21:18 UTC, jamezp commented
That makes sense @bstansberry and I meant to tag @jmesnil to have him take a look and pressed the button too soon.

2019-05-22 01:00 UTC, bstansberry requested changes
Please add a test case.

2019-05-27 16:24 UTC, michpetrov commented
@bstansberry to what extent should this be tested? is "is this running" enough or should I copy e.g. [MicroProfileMetricsApplicationTestCase](https://github.com/wildfly/wildfly/blob/master/testsuite/integration/basic/src/test/java/org/wildfly/test/integration/microprofile/metrics/application/MicroProfileMetricsApplicationTestCase.java)?

2019-06-04 02:38 UTC, bstansberry approved these changes

2019-06-04 10:16 UTC, merged