WFLY-12072 Allow setting create-on-start / drop-on-exit on Infinispan JDBC tables
wildfly/wildfly pull request #12298
Opened 2019-05-15 15:08 UTC by pferraro

https://issues.jboss.org/browse/WFLY-12072

2019-05-15 17:28 UTC, pferraro commented
Retest this please.

2019-05-20 10:15 UTC, darranl reviewed
For changes like this it would be preferable for the version bump to be in a separate commit.

Looking at the changes in GitHub it is not actually possible to see things like the changes made to the schema as they are made in a new file - also in the future if anyone it looking at the history they will not be able to tell the difference between the new schema and the changed made.

2019-05-20 12:13 UTC, pferraro commented
@darranl Makes sense. I'll move that to a separate commit.

2019-05-20 15:18 UTC, pferraro commented
@darranl Done.

2019-06-14 20:27 UTC, pferraro commented
Needs model version bump, since this didn't make it into WF17.

2019-07-30 19:29 UTC, bstansberry requested changes
@pferraro I'm requesting some minor things, mostly because a new CI run would be good.

If you update those and it passes CI please feel free to merge.

2019-07-30 19:29 UTC, bstansberry commented on clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TableResourceDefinition.java
> +        CREATE_ON_START("create-on-start", ModelType.BOOLEAN, new ModelNode(true)),
ModelNode.TRUE

2019-07-30 19:29 UTC, bstansberry commented on clustering/infinispan/extension/src/main/java/org/jboss/as/clustering/infinispan/subsystem/TableResourceDefinition.java
> +        DROP_ON_STOP("drop-on-stop", ModelType.BOOLEAN, new ModelNode(false)),
ModelNode.FALSE

I bulk corrected hundreds of these so I'm being picky. ;)

2019-07-30 19:29 UTC, bstansberry commented on clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
> +infinispan.store.jdbc.binary-keyed-table.table.create-on-start=Indicates whether the store should create this database table the cache starts.
s/table the/table when the/g

2019-07-30 19:29 UTC, bstansberry commented on clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
> +infinispan.store.jdbc.string-keyed-table.table.create-on-start=Indicates whether the store should create this database table the cache starts.
s/table the/table when the/g

2019-07-30 19:29 UTC, bstansberry commented on clustering/infinispan/extension/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
> +infinispan.table.create-on-start=Indicates whether the store should create this database table the cache starts.
s/table the/table when the/g

2019-07-30 19:29 UTC, bstansberry commented on clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_9_0.xsd
> +                <xs:documentation>Indicates whether the store should create this database table the cache starts.</xs:documentation>
s/table the/table when the/g

2019-07-31 18:57 UTC, merged