[WFLY-12252]: Add metric type flags on messaging subsytem metrics.
wildfly/wildfly pull request #12397
Opened 2019-06-28 09:41 UTC by ehsavoie

* Adding the missing flags

Jira: https://issues.jboss.org/browse/WFLY-12252

2019-07-10 07:42 UTC, jmesnil requested changes

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
> +            .addFlag(COUNTER_METRIC)
it's a gauge (number of consumers can go up and down) as a counter is only monotonically increasing

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 07:42 UTC, jmesnil commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/jms/JMSTopicDefinition.java
> +            .addFlag(COUNTER_METRIC)
gauge

2019-07-10 11:58 UTC, ehsavoie commented
All resolved

2019-07-29 20:15 UTC, bstansberry commented
@jmesnil OK now?

2019-07-30 06:56 UTC, jmesnil approved these changes

2019-07-31 18:58 UTC, merged