[WFLY-11101] Add documentation covering the use of the credential store.
wildfly/wildfly pull request #12414
Opened 2019-07-02 17:43 UTC by darranl

Documentation only in relation to existing functionality.

https://issues.jboss.org/browse/WFLY-11101

2019-07-18 21:36 UTC, bstansberry requested changes
Good stuff. :)

I was in the mood to play copy editor so I made a bunch of such suggestions. There was only one substantive thing -- a sentence that didn't really say anything.

Unless you get comments from others please feel free to merge once you've addressed whatever you feel is appropriate; i.e. I don't need to look again.  Unless you *really* want me to. ;)

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +One new component included with WildFly Elytron for the secure storage of credentials is the Credential Store.  Previous versions of the application server made use of the Vault which was used for th
s/text strings, the credential/text strings; the credential/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This documentation will be focused on using the `KeyStoreCredentialStore` however the section <<Custom_CredentialStore, Custom CredentialStore>> will describe how to convert a vault to a credential s
s/`KeyStoreCredentialStore` however/`KeyStoreCredentialStore`; however/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +Included with WildFly is a command line tool which amongst other things allows for the creation of and manipulation of credential stores, a script to execute this tool can be found within the `bin` f
s/stores, a script/stores. A script/g

s/store, by default/store. By default/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +NOTE: These commands are making use of the `.sh` script on linux, the `elytron-tool.bat` and `elytron-tools.ps1` scripts can be use on Microsoft Windows.
s/linux, the/linux; the/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +NOTE: These commands are making use of the `.sh` script on linux, the `elytron-tool.bat` and `elytron-tools.ps1` scripts can be use on Microsoft Windows.
s/use/used

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This command prompts twice for the password that should be used to secure the store.  Alternative the password can be passed in using the `--password` argument however that may mean the password is c
s/Alternative/Alternatively

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +Previous versions of the application server supported a single vault definition only, credential stores however are cross referenced by name so multiple credential stores can be defined simultaneousl
s/only, credential/only; credential/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +WARNING: Care should be taken when using the command line tool to ensure the store is not currently in use by any other processes, if the store is in use by another process which updates the contents
s/processes, if/processes. If/g

s/changed/changes

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +It is also possible to make use of the CredentialStore APIs directly, this could be useful for applications that require access to securely stored credentials.  This could also be an option for an ap
s/directly, this/directly. This/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +If migrating from a prior version of the application server it is possible that you already are making use of a PicketBox vault for the storage of clear text passwords, the tooling provided can be us
s/passwords, the/passwords. the/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +Within the WildFly Elytron command line tool an additional command `vault` is available specifically for the conversion of legacy vaults to a credential store, a complete vault can be converted to a
s/store, a/store. A/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +Entries stored within the vault would have been stored specifying a "block" and "alias" value, within the credential store the new alias will be `block::alias`.
s/value, within/value; within/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +It is also possible to provide custom credential store implementations, overall the pattern to implementing a custom credential store is very similar to the pattern that would be followed to implemen
s/implementations, overall/implementations. Overall/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +It is also possible to provide custom credential store implementations, overall the pattern to implementing a custom credential store is very similar to the pattern that would be followed to implemen
The second part of this doesn't make sense since it says  "the way to do foo is just like the way to do foo." One of the 'foo's should be a 'bar'?

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +The SPI to be extended is `org.wildfly.security.credential.store.CredentialStoreSpi`, the custom implementation will be required to implement the following methods.
s/, the custom/. The custom/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This method is required to perform the initisation of the credential store, by taking in a `Map` of attributes it allows for custom configuration to be provided as required by the store.
s/initisation/initialisation/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +A default implementation of `exists` already is implement which checks if a call to `retrieve` returns a credential as requested, however it could be optimal to check the existence of a credential wi
s/is implement/is implemented/g
s/requested, however/requested. However/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +The `store` and `remove` methods either add credentials to a credential store or remove them, implementing the `flush` method is optional but this method can be used as a trigger for a store to persi
s/them, implementing/them. Implementing/g

s/it's/its/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +The final stage is to provide an implementation of `java.security.Provider` which can return an instance of the SPI for the `CredentialStore` service type.  The WildFly Elytron provider which makes t
s/, the source/. The source/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +The previous sections have made use of either the WildFly Elytron Tool or the management operations and specified the arguments and configuration options required for the action being performed, thes
s/performed, these/performed. These/g

2019-07-18 21:36 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +|Remove the aliad specified from the credential store.
s/aliad/alias

2019-07-19 10:55 UTC, darranl commented
Thanks @bstansberry I will make the updates and get this merged, we have a couple of other enhancements being developed that will build on this so will be good to get it merged.

2019-07-19 15:34 UTC, fjuma approved these changes

2019-07-24 17:36 UTC, merged