WFLY-12136 Fix consistency of HttpSessionActivationListener event timing for distributed session managers
wildfly/wildfly pull request #12435
Opened 2019-07-16 02:49 UTC by pferraro

https://issues.jboss.org/browse/WFLY-12136

2019-08-16 16:47 UTC, bstansberry requested changes
Another huge refactor. :( Seems ok though, logging issues aside.

2019-08-16 16:47 UTC, bstansberry commented on clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
> +            InfinispanWebLogger.ROOT_LOGGER.infof("Session %s not found", id);
This doesn't look like INFO.

2019-08-16 16:47 UTC, bstansberry commented on clustering/web/infinispan/src/main/java/org/wildfly/clustering/web/infinispan/session/InfinispanSessionManager.java
> +            InfinispanWebLogger.ROOT_LOGGER.infof("Session %s was found, but has expired", id);
This doesn't look like INFO.

2019-08-16 20:42 UTC, pferraro commented
Fixed inadvertent logging level changes (residual debugging cruft).  Rebased against master.

2019-08-19 15:40 UTC, bstansberry approved these changes

2019-08-19 20:57 UTC, merged