[WFLY-11943] add code to retrieve resteasy endpoint data and insert i…
wildfly/wildfly pull request #12472
Opened 2019-08-05 19:19 UTC by rsearls

…nto model.

https://issues.jboss.org/browse/WFLY-11943

This PR is part of RFE https://issues.jboss.org/browse/EAP7-606
QA requested this be created for access during their Pre-Verification phase.
It should NOT be considered for merging at this time.

For new features ensure as well:
- [ ] Analysis was done 
     Document at https://github.com/wildfly/wildfly-proposals/pull/201
- [ ] Test Plan has been done
    Document at https://polarion.engineering.redhat.com/polarion/#/project/EAP7/wiki/RFEs_7_3/EAP7-606
- [ ] Tests were verified in advance
    This is in progress

2019-08-14 10:56 UTC, marekkopecky commented
This PR is currently blocked by https://issues.jboss.org/browse/WFLY-12091

2019-08-16 00:28 UTC, bstansberry commented
@rsearls https://github.com/wildfly/wildfly/commit/3960a17aefb73072d49816b83e6d2c41db37386d fixes your problem. Galleon provisions a server's config files by calculating and executing management ops and letting the server persist the xml. But JaxrsSubsystemAdd was not storing the new statistics-enabled attribute to the model so nothing got persisted.

Your PR should include an update to https://github.com/wildfly/wildfly/blob/master/jaxrs/src/test/java/org/jboss/as/jaxrs/JaxrsSubsystemTestCase.java#L40 so the test case covers this new attribute.

2019-08-16 20:02 UTC, rsearls commented
@bstansberry 
Thanks I have made the needed changes.

2019-08-19 10:05 UTC, jfdenise commented
@rsearls instead of duplicating the attribute in the galleon layer and basic profile would you mind define a jaxrs feature-group and reference the feature-group from the jaxrs layer and basic-profile? it will help maintenance. Thank-you.

2019-08-19 11:46 UTC, rsearls commented
Brian,

Would you care to comment on Jean-François's request for me to change the
location of the addition of the jaxrs attribute.

On Mon, Aug 19, 2019 at 6:05 AM Jean-François Denise <
notifications@github.com> wrote:

> @rsearls <https://github.com/rsearls> instead of duplicating the
> attribute in the galleon layer and basic profile would you mind define a
> jaxrs feature-group and reference the feature-group from the jaxrs layer
> and basic-profile? it will help maintenance. Thank-you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly/pull/12472?email_source=notifications&email_token=AAD3X43M4TN6HDHX5QQ5Z6LQFJV6VA5CNFSM4IJOEFJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4SMBEI#issuecomment-522502289>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAD3X422O6VWMB43Z4TD3PLQFJV6VANCNFSM4IJOEFJQ>
> .
>

2019-08-19 15:35 UTC, bstansberry commented
@rsearls +1 to his suggestion.  I haven't even built this, so there may be typos etc but I think the last commit at https://github.com/bstansberry/wildfly/commits/testPullRequest12472 is what's needed.

2019-08-19 15:55 UTC, rsearls commented
Ok thanks.
galleon-pack/src/main/resources/feature_groups/jaxrs.xml   has been added.

On Mon, Aug 19, 2019 at 11:35 AM Brian Stansberry <notifications@github.com>
wrote:

> @rsearls <https://github.com/rsearls> +1 to his suggestion. I haven't
> even built this, so there may be typos etc but I think the last commit at
> https://github.com/bstansberry/wildfly/commits/testPullRequest12472 is
> what's needed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly/pull/12472?email_source=notifications&email_token=AAD3X45LOKC5NB6HT7YSKWTQFK4VXA5CNFSM4IJOEFJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4TLTII#issuecomment-522631585>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAD3X47CQYXBSFD4XVVS7SDQFK4VXANCNFSM4IJOEFJQ>
> .
>

2019-08-19 15:55 UTC, rsearls commented
Addition complete

2019-08-20 08:59 UTC, jfdenise commented
Hi @rsearls , you added the feature-group, that is nice, but you are not making use of it in basic-profile and jaxrs layer. You should replace the jaxrs feature by  <feature-group name="jaxrs"/>

2019-08-20 12:00 UTC, rsearls commented
@jfdenise 
Please point me to sample code I can follow.

2019-08-20 12:06 UTC, jfdenise commented
You can look at brian repo: https://github.com/bstansberry/wildfly/commit/58364fbff3006fa4613f366cc9ff7f47211df482#diff-7c7e29588d041416fe03af41b27ffefeR105

2019-08-21 12:35 UTC, rsearls commented
Thanks, adjustments have been made.

2019-08-21 12:37 UTC, jfdenise commented
@rsearls , Thank-you.

2019-08-27 06:08 UTC, marekkopecky commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/jaxrs/HelloApplication.java
> +        classes.add(HelloBadResource.class);
This change causes regression of JaxrsRuntimeNameTestCase. JaxrsRuntimeNameTestCase uses HelloApplication.java as well, but HelloBadResource is not added to the deployment from JaxrsRuntimeNameTestCase. So JaxrsRuntimeNameTestCase fails.

2019-08-27 06:08 UTC, marekkopecky requested changes

2019-08-27 06:08 UTC, marekkopecky commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/deploy/runtime/jaxrs/HelloApplication.java
> +        classes.add(HelloBadResource.class);
This change causes regression of JaxrsRuntimeNameTestCase. JaxrsRuntimeNameTestCase uses HelloApplication.java as well, but HelloBadResource is not added to the deployment from JaxrsRuntimeNameTestCase. So JaxrsRuntimeNameTestCase fails.

2019-08-27 08:49 UTC, marekkopecky commented
AccessConstraintUtilizationTestCase#testConstraintUtilization is failing with:
```
[ERROR] Failures: 
[ERROR]   AccessConstraintUtilizationTestCase.testConstraintUtilization:154 {"outcome" => "failed","failure-description" => "WFLYCTL0216: Management resource '[
    (\"core-service\" => \"management\"),
    (\"access\" => \"authorization\"),
    (\"constraint\" => \"sensitivity-classification\"),
    (\"type\" => \"messaging-activemq\")
]' not found","rolled-back" => true}
[ERROR]   PermissionsCoverageTestCase.testTheEntireDomainTreeHasPermissionsDefined:70 {"outcome" => "failed","failure-description" => "WFLYCTL0158: Operation handler failed: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key jaxrs.deployment.rest-resource-paths.method_statistics","rolled-back" => true}
```

2019-08-29 12:14 UTC, rsearls commented
@jfdenise  @bstansberry 
Having added a single attribute to the existing subsystem=jaxrs appears to
break wfly's ability to properly discover this subsystem.  The following 
integration tests fail.  All failures appear related to not properly finding 
the jaxrs subsystem definition.

Who can I consult to figure out how to resolve these issues?
 
Failing test:
rbac  org/jboss/as/test/integration/mgmt/access/PermissionsCoverageTestCase.java 
basic org/jboss/as/test/integration/jmx/ModelControllerMBeanTestCase.java 

-------
org/jboss/as/test/integration/mgmt/access/PermissionsCoverageTestCase.java

  Reports failure from AbstractOperationContext line 1037 msg

    "WFLYCTL0158: Operation handler failed: java.util.MissingResourceException: 
    Can't find resource for bundle java.util.PropertyResourceBundle, 
    key jaxrs.deployment.rest-resource-paths.method_statistics","rolled-back" => true}

------
basic org/jboss/as/test/integration/jmx/ModelControllerMBeanTestCase.java
    ResourceAccessControl getResourceAccessWithInstanceNotFoundExceptionIfNotAccessible(
              ObjectName name, PathAddress address, boolean operations) throws InstanceNotFoundException {
        ResourceAccessControl accessControl = getResourceAccess(address, operations);
        if (!accessControl.isAccessibleResource()) {
            throw JmxLogger.ROOT_LOGGER.mbeanNotFound(name);
        }
        return accessControl;
    }

  Variable accessControl reports a false address
        protect: true
        value: {"address" => false}
  
  Variables name and address are report to be
        name: jboss.as:subsystem=jaxrs
        address: [("subsystem" => "jaxrs")]

2019-08-29 13:59 UTC, jfdenise commented
@rsearls , don'y you have to add something to: https://github.com/wildfly/wildfly/blob/master/jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties file?

2019-08-29 18:05 UTC, rsearls commented
Thanks that resolved the issue with PermissionsCoverageTestCase.

2019-08-30 09:30 UTC, jfdenise commented
@rsearls , just a note, I can see a lot of formatting changes in your commit, that creates noise when reviewing. That would help to remove them.

2019-08-30 16:37 UTC, rsearls commented
@jfdenise 
The failure with org/jboss/as/test/integration/jmx/ModelControllerMBeanTestCase.java still remains.
I need assistance with this one as well.

2019-09-16 20:21 UTC, rsearls commented
Regression in ModelControllerMBeanTestCase.java has been addressed

2020-04-30 10:14 UTC, darranl commented
@rsearls I am just trying to tidy up the WildFly PR queue as we have a lot of stale PRs in the queue, it looks like this now has a set of merge conflicts that will need to be addressed - if this is continuing could you also please confirm the state so we can kick off review again and see if we are ready for a merge.  Alternatively can we please close the PR for now and re-open once ready.

2020-04-30 13:11 UTC, closed without merging