[WFLY-11697] Add documentation for WS integration with WildFly Elytro…
wildfly/wildfly pull request #12475
Opened 2019-08-06 15:37 UTC by Skyllarr

…n - AuthenticationClient for Authentication / SSL

Jira: https://issues.jboss.org/browse/WFLY-11697

2019-12-02 22:55 UTC, fjuma requested changes

2019-12-02 22:55 UTC, fjuma commented on docs/src/main/asciidoc/_client-guide/Webservices_Client_Configuration.adoc
> +The _<webservices />_ element in a `wildfly-config.xml` file can be used to specify Webservices Client configuration that will apply during link:https://docs.jboss.org/author/display/JBWS/Predefined+
```urn:jboss:wildfly-client-ejb:4.0``` should be ```urn:elytron:client:1.5```

2019-12-02 22:55 UTC, fjuma commented on docs/src/main/asciidoc/_client-guide/Webservices_Client_Configuration.adoc
> +    <webservices xmlns="urn:jboss:wildfly-client-ejb:3.0">
Looks like the xmlns part should be removed here.

2019-12-03 12:54 UTC, Skyllarr commented
@fjuma Thank you. I updated this PR

2019-12-10 15:09 UTC, darranl approved these changes

2019-12-19 18:12 UTC, merged