WFLY-12283 Upgrade IronJacamar from 1.4.16.Final to 1.4.17.Final
wildfly/wildfly pull request #12485
Opened 2019-08-08 09:44 UTC by xstefank

https://issues.jboss.org/browse/WFLY-12283

It also incorporates https://github.com/wildfly/wildfly/pull/12439 containing a test for https://issues.jboss.org/browse/JBJCA-1389.

2019-08-08 09:47 UTC, xstefank commented
Supersedes #12439

2019-08-08 13:31 UTC, kabir commented
@xstefank it seems the new test is failing

2019-08-08 15:24 UTC, xstefank commented
The test seems to be wrong, I will try to amend the commit.

2019-08-08 16:52 UTC, xstefank commented
retest this please

2019-08-09 05:12 UTC, xstefank commented
@kabir test suite passed

2019-08-09 08:19 UTC, kabir commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/DataSourceDefinitionTestCase.java
> +        expectedException.expectMessage("IJ031041: Connection handle has been closed and is unusable");
We should probably just check for the message id, or it will fail if someone is e.g. using German as their locale

2019-08-09 08:20 UTC, kabir commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/DataSourceDefinitionTestCase.java
> +    @Test
Nitpick: move after the comment

2019-08-09 08:20 UTC, kabir commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/datasourcedefinition/DataSourceDefinitionTestCase.java
> +        }catch (NullPointerException e){
Nitpick: could do with some spaces `} catch (NullPointerException e) {`

2019-08-09 08:22 UTC, xstefank commented
@kabir and that's what I get for cherry-picking :)

2019-08-09 08:22 UTC, kabir requested changes
@xstefank some minor comments, the i18n one is the real one but while there might as well deal with the nits :)

2019-08-09 08:23 UTC, xstefank commented
@kabir and that's what I get for cherry-picking :)

2019-08-09 14:12 UTC, jamezp approved these changes

2019-08-11 10:27 UTC, merged