[WFLY-12442]:Upgrade jboss-saaj-api and saaj-impl from 1.3 to 1.4
wildfly/wildfly pull request #12549
Opened 2019-08-28 10:34 UTC by jimma

….0.CR1
https://issues.jboss.org/browse/WFLY-12442

2019-08-28 13:30 UTC, bstansberry requested changes

2019-08-29 03:26 UTC, jimma commented on pom.xml
> +            </dependency>
Fixed. Thanks.

2019-08-29 11:50 UTC, psakar commented
@rgdoliveira this will require changes in test release + new project stream

2019-08-29 21:39 UTC, kabir commented
@jimma A few of the jobs seem messed up, but for a bunch of the others there are 22 similar failures

2019-08-30 12:23 UTC, jimma commented
@kabir  Looks we have to do more work to upgrade saaj-impl to 1.4. I am looking at these Ws test failures.

2019-08-30 15:18 UTC, scottmarlow commented
@jimma please do let us know if you hit obstacles with SAAJ 1.4 that cannot be solved.

2019-08-31 19:07 UTC, bstansberry commented
@jimma More exclusions needed:

```
[04:20:21][Step 2/3] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanTransitiveDependencies failed with message:
[04:20:21][Step 2/3] org.wildfly:wildfly-feature-pack:pom:18.0.0.Beta1-SNAPSHOT
[04:20:21][Step 2/3]    org.jboss.spec.javax.xml.soap:jboss-saaj-api_1.4_spec:jar:1.0.0.CR1:compile has transitive dependencies:
[04:20:21][Step 2/3]       jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[04:20:21][Step 2/3] 
[04:20:21][Step 2/3] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (ban-transitive-deps) on project wildfly-feature-pack: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
```

2019-09-02 08:25 UTC, jimma commented
@scottmarlow @bstansberry  It turns out that we can't upgrade to saaj 1.4 , even upgrade to 1.3.29.
There is one[ problematic commit]( https://github.com/jboss/saaj-impl/commit/148757613467ee3c60ac8db364c80cc842348713#diff-a1e80cc152d578329e259c567d2b9c96R94 )  in saaj 1.3.29 which changed saaj behavior to create one dom document instead of using the passed by element part's owner document.  This leads  webservice subystem complains many errors like : 
`javax.xml.ws.soap.SOAPFaultException: WRONG_DOCUMENT_ERR: A node is used in a different document than the one that created it.
`

I am going to look at what we can do in our saaj-impl 1.4 fork to fix these failures. It will probably take a lot more time than expected to get this work.

2019-09-04 06:52 UTC, jimma commented
Retest this please

2019-09-04 11:58 UTC, bstansberry commented
@darranl FYI re the 2nd commit

2019-09-04 12:18 UTC, jimma commented
Looks the batch api upgrade in WFLY master broke enforcer rule :

```
[04:50:40][Step 2/3] [INFO] ------------------< org.wildfly:wildfly-batch-jberet >------------------
[04:50:40][Step 2/3] [INFO] Building WildFly: Batch Integration Subsystem (JBeret implementation) 1
[04:50:41][Step 2/3] [WARNING] 
[04:50:41][Step 2/3] Dependency convergence error for org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:2.0.0.CR1 paths to dependency are:
[04:50:41][Step 2/3] +-org.wildfly:wildfly-batch-jberet:18.0.0.Beta1-SNAPSHOT
[04:50:41][Step 2/3]   +-org.jboss.spec.javax.batch:jboss-batch-api_1.0_spec:2.0.0.CR2
[04:50:41][Step 2/3]     +-org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:2.0.0.CR1
[04:50:41][Step 2/3] and
[04:50:41][Step 2/3] +-org.wildfly:wildfly-batch-jberet:18.0.0.Beta1-SNAPSHOT
[04:50:41][Step 2/3]   +-org.wildfly.transaction:wildfly-transaction-client:1.1.7.Final
[04:50:41][Step 2/3]     +-org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:1.0.1.Final
[04:50:41][Step 2/3] 
[04:50:41][Step 2/3] [WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
[04:50:41][Step 2/3] Found Banned Dependency: org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:2.0.0.CR1
[04:50:41][Step 2/3] Use 'mvn dependency:tree' to locate the source of the banned dependencies.
[04:50:41][Step 2/3] [WARNING] Rule 1: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
[04:50:41][Step 2/3] Failed while enforcing releasability. See above detailed error message.
[04:50:41][Step 2/3] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (ban-bad-dependencies) on project wildfly-batch-jberet: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[04:50:41][Step 2/3] [INFO] 
```

2019-09-04 12:20 UTC, bstansberry commented
retest this please

@jimma We just merged the fix for the enforcer problem.

2019-09-04 14:28 UTC, jimma commented
Retest this please

2019-09-09 07:38 UTC, jimma commented
The failures after security manager is enabled is caused by https://issues.apache.org/jira/browse/WSS-654

2019-09-13 17:26 UTC, jamezp commented
@jimma This needs a rebase and likely should be bumped to the 1.0.0.Final version.

2019-09-15 03:37 UTC, bstansberry commented
I resolve the conflict via the github UI as I want to see what CI does.

2019-09-16 04:05 UTC, jimma commented
@bstansberry  @jamezp  I already rebased and upgraded saaj 1.4 api to 1.0.0.Final.

2019-09-16 12:47 UTC, jimma commented
Looks one failure from Linux JDK11 build is not relevant.

2019-09-19 16:18 UTC, bstansberry commented
retest this please

2019-09-19 16:22 UTC, bstansberry commented
@jimma @jamezp @asoldano I just kicked off a retest of this as it's been a couple days, but once that's done, as per an earlier discussion we should merge this and deal with the picketlink issue later, just being sure that's sorted or this is reverted before WF 18 Final.  There's value in getting this in and tested in other testsuites that consume WF master.

2019-09-19 16:43 UTC, jamezp approved these changes

2019-09-19 16:44 UTC, asoldano approved these changes
Thanks Brian, clearly I agree on the approach.

2019-09-19 23:37 UTC, merged