[WFLY-12447] Removing generated keystore files from source control
wildfly/wildfly pull request #12563
Opened 2019-08-30 15:10 UTC by ashley-abdelsayed98

https://issues.jboss.org/browse/WFLY-12447

Removing keystore files generated and deleted during tests from git and moving the keystore directory.

2019-08-30 19:23 UTC, fjuma approved these changes

2019-08-30 20:13 UTC, bstansberry requested changes

2019-08-30 20:13 UTC, bstansberry commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/web/ssl/AbstractCertificateLoginModuleTestCase.java
> +    protected static final File WORK_DIR = new File("./target/test-classes/keystores-workdir");
This needs to be Windows-compatible.

2019-08-31 02:05 UTC, bstansberry approved these changes

2019-08-31 02:05 UTC, merged