[WFLY-12496] Fix MessagingHATestCase
wildfly/wildfly pull request #12592
Opened 2019-09-05 13:35 UTC by istraka

https://issues.jboss.org/browse/WFLY-12496

2019-09-16 23:32 UTC, bstansberry commented
retest this please

This requires approval from @ehsavoie as he's dealing with blocker issues involving these tests and we don't want to conflict.

2019-09-17 01:13 UTC, bstansberry commented
I put the 18.x label on this because if it passes CI and doesn't interfere with other work there's no reason not to merge it for 18.

2019-09-17 02:47 UTC, bstansberry commented
@istraka The 'Linux with security manager' CI job failures are due to this change. Deployment needs permissions.

2019-09-17 07:52 UTC, ehsavoie approved these changes

2019-09-25 20:29 UTC, bstansberry requested changes

2019-09-25 20:29 UTC, bstansberry commented on testsuite/integration/multinode/src/test/java/org/jboss/as/test/multinode/transaction/nooutbound/TransactionContextRemoteCallTestCase.java
> +        ProviderUrlData providerUrl = new ProviderUrlData("remote+http", TestSuiteEnvironment.getServerAddressNode1(), serverPort);
This test now reads a system property so I think the set of permissions added to CLIENT_DEPLOYMENT in clientDeployment() needs to include a PropertyPermission.

2019-10-29 09:44 UTC, kabir commented
@istraka if you agree can you add the missing permission? Or if not, leave a message

2019-11-06 09:33 UTC, kabir commented
Superseded by 12779

2019-11-06 09:33 UTC, closed without merging