[WFLY-12520][WFLY-12467]
wildfly/wildfly pull request #12668
Opened 2019-09-23 20:44 UTC by emmartins

Issues: https://issues.jboss.org/browse/WFLY-12520, https://issues.jboss.org/browse/WFLY-12467

2019-09-23 20:56 UTC, emmartins commented
fyi Includes "model bump" commit common to #12567

2019-11-07 21:51 UTC, bstansberry requested changes
@emmartins Small issues in my comments aside, looks good. Please @ ping me when corrected and we'll get this pushed through. Thanks for your patience.

2019-11-07 21:51 UTC, bstansberry commented on ee/src/main/java/org/jboss/as/ee/subsystem/ManagedExecutorServiceResourceDefinition.java
> +            new SimpleAttributeDefinitionBuilder(THREAD_PRIORITY, ModelType.INT, true)
This and THREAD_FACTORY_AD should both use setAlternatives to declare that each is an alternative to the other.

2019-11-07 21:51 UTC, bstansberry commented on ee/src/main/java/org/jboss/as/ee/subsystem/ManagedScheduledExecutorServiceResourceDefinition.java
> +            new SimpleAttributeDefinitionBuilder(THREAD_PRIORITY, ModelType.INT, true)
This and THREAD_FACTORY_AD should both use setAlternatives to declare that each is an alternative to the other.

2019-11-08 16:01 UTC, emmartins commented
thanks @bstansberry, requested changes applied

2019-11-08 23:25 UTC, bstansberry submitted a review, later dismissed

2019-12-06 01:28 UTC, bstansberry commented
@emmartins The tests failures are related.

2019-12-16 19:28 UTC, emmartins commented
@bstansberry fixed

2019-12-16 20:21 UTC, bstansberry approved these changes

2019-12-19 18:13 UTC, merged