[CLOUD-2262] adding documentation about EJB remote calls on Kubernetes
wildfly/wildfly pull request #12716
Opened 2019-10-16 12:53 UTC by ochaloup

https://issues.jboss.org/browse/CLOUD-2262

Documentation for the EJB remote calls enablement on Kubernetes. It's connected with the transaction context propagation and transaction recovery.

2019-10-16 12:53 UTC, ochaloup commented
@jmesnil would you be so kind and check if this is in a correct format?

2019-10-16 13:15 UTC, simkam requested changes

2019-10-16 13:15 UTC, simkam commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +The rest of this chapter assumes you run to use the link:https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/[`StatefulSet`]
`assumes you run to use` wording doesn't seem correct to me

2019-10-16 13:15 UTC, simkam commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +The `StatefulSet` guarantees depend on the ordering of the pods. The pod are named by the defined order.
The pod**s** are

2019-10-16 13:15 UTC, simkam commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +. There is need a small workaround for remote EJB transaction recovery on Kubernetes
wording doesn't seem correct to me, I would suggest "Small workaround is needed"

2019-10-16 13:15 UTC, simkam commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +  Let’s say there is configured a user on the target server. It's used the script ``$JBOSS_HOME/bin/add-user.sh` and the user is created under the `ApplicationRealm`.
"It’s used the script $JBOSS_HOME/bin/add-user.sh" -> "The script $JBOSS_HOME/bin/add-user.sh is used" ?

2019-10-16 13:20 UTC, ochaloup commented
@simkam thanks for the review!

2019-10-17 11:03 UTC, rhusar requested changes

2019-10-17 11:03 UTC, rhusar commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +  ```
This is markdown, not asciidoc notation.

https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks

2019-10-17 11:03 UTC, rhusar commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +  ```
This is markdown, not asciidoc notation.

https://asciidoctor.org/docs/asciidoc-writers-guide/#listing-and-source-code-blocks

2019-10-17 12:58 UTC, ochaloup commented
@rhusar thanks. You are right, fixed.

Just pointing - I use it because the AsciiDoc declares compatibility with markdown https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility

2019-10-17 13:00 UTC, rhusar commented
@ochaloup 

> Markdown compatible syntax is only available when using Asciidoctor.

e.g. GitHub doesn't seem to because ti was rendered incorrectly.

2019-10-17 15:34 UTC, jmesnil requested changes

2019-10-17 15:34 UTC, jmesnil commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +If the WildFly server is deployed on the Kubernetes then there are several
"on Kubernetes"

2019-10-17 15:34 UTC, jmesnil commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +If you scale your application up to 3 replicas you may expect to name of pods like `wildfly-server-0`, `wildfly-server-1`, `wildfly-server-2`.
"your pods will have names such as  `wildfly-server-0`, "

2019-10-17 15:34 UTC, jmesnil commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +If the WildFly is run on `StatefulSet` with the headless service named `wildfly-server-headless`.
"If the application uses the WildFly Operator, a headless service will be created with a name such as `wildfly-server-headless`.

2019-10-17 15:34 UTC, jmesnil commented on docs/src/main/asciidoc/_developer-guide/ejb3/EJB_on_Kubernetes.adoc
> +If the Wildfly is run as cluster then this use of the hostname `wildfly-server-0.wildfly-server-headless`
"The use of the hostname..."

2019-10-18 07:53 UTC, ochaloup commented
@jmesnil thanks!

2019-10-21 13:34 UTC, ochaloup commented
@bstansberry @jmesnil do you think this could be merged now?

2019-10-25 22:11 UTC, bstansberry commented
@ochaloup I see the comments from @jmesnil were addressed so I'm going to merge this.

2019-10-25 22:12 UTC, merged