Updated Smallrye Config to 1.3.9
wildfly/wildfly pull request #12721
Opened 2019-10-16 19:13 UTC by tobiasstadler

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] Pull Request contains description of the issue(s)
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted

For bigger changes, major and minor component upgrades make sure your PR also meets following requirements:
- [ ] Pull Request requires a change to the documentation
- [ ] Documentation have been updated accordingly
- [ ] Tests were added to cover changes

For new features ensure as well:
- [ ] Analysis was done
- [ ] Test Plan has been done
- [ ] Tests were verified in advance

If you are not an active contributor of the WildFly project you can request sponsorship by one of the members to help guide you through the process.

2019-10-17 10:58 UTC, rhusar requested changes
Tests need to be adapted as well.
```
ConfigProviderTest.testEnvironmentConfigSource
EmptyValuesTest.testEmptyStringProgrammaticLookup
EmptyValuesTest.testEmptyStringPropertyFromConfigFile
```

2019-10-17 10:59 UTC, rhusar commented
Also a component upgrade Jira is needed and needs to prefix the commit message.

2019-10-31 11:36 UTC, jmesnil commented
@tobiasstadler thanks for the PR.

Your PR looks fine but I'll put it on hold for the time being.
After smallrye-config 1.3.6 was released, changes in the components were made for its use in Quarkus.
They resulted in challenges to the TCK about the `EmptyValuesTest` tests that fail in our WildFly Jobs.

We are in the process of releasing smallrye-config 1.3.10 to run the MP Config TCK with Quarkus. At this point, we will be able to upgrade smallrye-config in WildFly with the same TCK challenges that Quarkus has.

2019-11-08 09:28 UTC, jmesnil requested changes
smallrye-config 1.3.11 has been released and this is the version we should upgrade to: https://mvnrepository.com/artifact/io.smallrye/smallrye-config/1.3.11

It challenges some MicroProfile Config TCK tests (as defined in https://github.com/smallrye/smallrye-config/blob/master/testsuite/tck/tck-suite.xml).

We should update https://github.com/wildfly/wildfly/blob/master/testsuite/integration/microprofile-tck/config/tck-suite.xml to add the same exclusions.

@tobiasstadler do you want to take care of ^^? thanks

2019-11-11 19:37 UTC, tobiasstadler commented
@jmesnil I updated the PR

2019-11-11 22:23 UTC, rhusar requested changes
Tests are failing:

org.eclipse.microprofile.metrics.tck
(1)

GlobalTagsTest.customConfigSource
 

org.wildfly.test.integration.microprofile.config.smallrye.app
(2)

MicroProfileConfigTestCase.testGetWithArraySetListDefaultProperties
 

MicroProfileConfigTestCase.testGetWithArraySetListOverriddenProperties
 

TestSuite: org.eclipse.microprofile.config.tck
(1)

ConfigProviderTest.testEnvironmentConfigSource

2019-11-12 20:46 UTC, tobiasstadler commented
@rhusar I am not sure what to with GlobalTagsTest.customConfigSource. As per the api spec `ConfigProviderResolver#registerConfig` should throw an IllegalStateException if there is already a Config registered within the Application (with is the case here). I think the test needs to call `releaseConfig` before  `registerConfig`. What do you think?

2019-11-12 21:56 UTC, rhusar requested changes

2019-11-12 21:56 UTC, rhusar commented on testsuite/integration/microprofile-tck/config/tck-suite.xml
> +            <!-- These test are also exclueded in the SmallRye TCK -->
s/exclueded/excluded

2019-11-12 21:56 UTC, rhusar commented
@tobiasstadler Its possible, I would need to have a better look...

2019-11-28 09:29 UTC, jmesnil commented
@tobiasstadler same comment than for #12719 

Thanks for your help!

2019-11-28 09:29 UTC, closed without merging