WFLY-12777 Stateful bean with @StatefulTimeout value -1 should not ti…
wildfly/wildfly pull request #12797
Opened 2019-11-13 20:28 UTC by chengfang

…meout or removed

Fixed `org.jboss.as.ejb3.cache.simple.SimpleCache` class to properly handle stateful-timeout value -1 (never timeout).

JIRA: https://issues.jboss.org/browse/WFLY-12777

2019-11-14 15:38 UTC, scottmarlow approved these changes
Looks good to me, the -1 setting is also mentioned in ejb-jar_3.1.xsd:
>         The stateful-timeoutType represents the amount of time
>         a stateful session bean can be idle(not receive any client
>         invocations) before it is eligible for removal by the container.
> 
>         A timeout value of 0 means the bean is immediately eligible for removal.
> 
>         A timeout value of -1 means the bean will never be removed due to timeout.
>

2019-11-14 15:38 UTC, scottmarlow commented
@pferraro could you please review this change also.

2019-11-14 16:42 UTC, pferraro requested changes
DistributableCache needs to be fixed as well:
https://github.com/wildfly/wildfly/blob/master/ejb3/src/main/java/org/jboss/as/ejb3/cache/distributable/DistributableCacheFactoryBuilderServiceConfigurator.java#L138

2019-11-14 16:49 UTC, pferraro commented
Frankly, this particular detail in the spec is a bit illogical...
@StatefulTimeout(value=-24, unit=TimeUnit.HOURS), is invalid, but
@StatefulTimeout(value=-1, unit=TimeUnit.DAYS), while logically equivalent to the above, is valid and means the bean never times out.

iMO, we ought to clean this up in future versions of the EJB spec.  Really, *any* negative value should to be interpreted in the same way.

2019-11-14 17:48 UTC, chengfang commented
@pferraro thanks.  I'll update DistributableCache, and loosen the condition to allow for all negative numbers.

2019-11-18 23:11 UTC, chengfang commented
I've updated the PR based on the review comments.  Please review again.

2019-11-21 11:31 UTC, pferraro approved these changes

2019-11-23 16:13 UTC, merged