[WFLY-12990] Upgrade WildFly Naming Client to 1.0.12.Final
wildfly/wildfly pull request #12930
Opened 2020-01-17 11:32 UTC by ropalka

Includes fix for https://issues.redhat.com/browse/WFNC-56

2020-01-17 13:31 UTC, darranl requested changes
Could you please provide some release notes to show what is included, is it just the one fix or anything else?

2020-01-17 18:18 UTC, ropalka commented
It includes just that one fix @darranl - all PR, JIRA and commit descriptions are exhaustive ;)

2020-01-18 20:51 UTC, bstansberry commented
Linux with security manager failure looks like https://issues.redhat.com/browse/WFLY-12822. I'll re-run.

2020-01-19 20:30 UTC, bstansberry approved these changes

2020-01-19 20:31 UTC, merged