[WFLY-13101] Tests for Microprofile Health 2.2
wildfly/wildfly pull request #13004
Opened 2020-02-17 18:29 UTC by fabiobrz

This PR adds a test case for validating `HealthCheckResponse` class, which has been defined as concrete in the latest MicroProfile Health 2.2 release. This is basically the main change introduced by this last version of the spec from the end user point of view.

* Please be aware that this PR depends on https://github.com/wildfly/wildfly/pull/12983 and thus _shouuld not_ be merged before the latter is, as well.
 
* JIRA issue: https://issues.redhat.com/browse/WFLY-13101

This test case was run against the Wildfly feature branch which already has the MicroProfile/SmallRye upgrade, see [1].

The test failed, because there's a mismatch in the spec between a property name and the actual payload JSON schema. An issue to MicroProfile Health project has been filed [2] and the test case has been marked as ignored for this reason.

[1]
https://github.com/jmesnil/wildfly/tree/WFLY-13048_upgrade_microprofile-health_2.2

[2]
https://github.com/eclipse/microprofile-health/issues/243

- [x] Pull Request title is properly formatted: `[WFLY-XYZ] Subject` or `WFLY-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue(s)
- [x] Pull Request contains description of the issue(s)
- [x] Pull Request does not include fixes for issues other than the main ticket
- [x] Attached commits represent units of work and are properly formatted

2020-02-17 19:13 UTC, bstansberry commented
this is ok to test

2020-02-17 19:14 UTC, bstansberry commented
@jmesnil If these changes are ok can you pull them into your branch(es) for the upgrade? Your submitting the commits as part of your PR counts as the necessary approval of them.

2020-02-17 19:21 UTC, jmesnil commented on testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/health/ConcreteHealthCheckResponseTestCase.java
> +                HealthCheckResponse typedResponse = new ObjectMapper().readValue(
-1, the spec does not specify that the JSON schema must map to the `HealthCheckResponse`.

2020-02-17 19:24 UTC, jmesnil requested changes
I'm -1 on this test.

The MP Health TCK already uses extensively the `HealthCheckResponse `class.
This test does not bring any additional assertions to what is already tested by the TCK.

2020-02-17 19:55 UTC, fabiobrz commented
Hi @jmesnil although the spec doesn't mandate for the `HealthCheckResponse` class to map to the protocol JSON schema, I see that the use case [1] which was referred by the PR [2] that brought the change in is actually about deserialization with - for instance - REST Client. This would help the end user (Wildfly end user, in this very case) to leverage such tools easily. WDYT?
Also @xstefank what are actual plans on `HealthCheckResponse` class in future? Is mapping to the JSON schema going to be a requirement? 

[1]
https://github.com/eclipse/microprofile-health/issues/194

[2]
https://github.com/eclipse/microprofile-health/pull/218

2020-02-17 20:18 UTC, xstefank commented
@jmesnil I believe this is an oversight on the spec side. I will raise this in the community. However, this kind of test can be added as an actual new TCK test in my opinion. So I agree that this test is not necessary for wfly test suite.

2020-02-18 10:41 UTC, marekkopecky commented
> The MP Health TCK already uses extensively the HealthCheckResponse class.
This test does not bring any additional assertions to what is already tested by the TCK.

@jmesnil It seems that TCK uses JSON-P, not JSON-B/Jackson

2020-02-18 10:52 UTC, jmesnil commented
@marekkopecky that's correct. One more reason to move that test in the microprofile-health tck to make sure that https://github.com/eclipse/microprofile-health/issues/243 is properly addressed.

However that does not change my opinion that this test does not belong to WildFly integration test suite.

2020-02-18 15:50 UTC, fabiobrz commented
PR can be closed as necessary test coverage will be added to https://github.com/eclipse/microprofile-health, see https://github.com/eclipse/microprofile-health/issues/243
Thanks for your feedback @jmesnil, @xstefank, @marekkopecky and @bstansberry

2020-02-18 15:50 UTC, closed without merging