WFLY-13099 WIP
wildfly/wildfly pull request #13015
Opened 2020-02-19 01:32 UTC by bstansberry

Just an experiment to see what CI says. I intend to add more testsuite executions.

2020-02-19 22:36 UTC, rhusar requested changes

2020-02-19 22:36 UTC, rhusar commented on testsuite/layers/pom.xml
> +>>>>>>> e9c00016f7... [WFLY-13099] Add layers tests for the combos used in standalone-microprofile.xml and standalone-microprofile-ha.xml
Rebase oops? :-)

2020-02-20 03:45 UTC, bstansberry commented on testsuite/layers/pom.xml
> +>>>>>>> e9c00016f7... [WFLY-13099] Add layers tests for the combos used in standalone-microprofile.xml and standalone-microprofile-ha.xml
Seems so!

2020-02-20 18:51 UTC, bstansberry commented
retest this please

2020-02-23 12:34 UTC, bstansberry commented
retest this please

2020-03-06 17:25 UTC, merged