[WFLY-13185]:Add microprofile restclient dependency to jaxrs deployment to fix NPE issue
wildfly/wildfly pull request #13089
Opened 2020-03-06 15:16 UTC by jimma

https://issues.redhat.com/browse/WFLY-13185

2020-03-11 18:44 UTC, bstansberry commented
@jimma I believe you also need to add a line equivalent to this:

https://github.com/wildfly/wildfly/pull/13075/files#diff-aaad68233e8e9273c54f93f079cc27cbR82

@jfdenise Please review

2020-03-11 18:45 UTC, bstansberry requested changes
@jimma I believe you also need to add a line equivalent to this:

https://github.com/wildfly/wildfly/pull/13075/files#diff-aaad68233e8e9273c54f93f079cc27cbR82

@jfdenise Please review

2020-03-12 09:53 UTC, jimma commented
@bstansberry  Fixed.

2020-03-12 10:13 UTC, jfdenise approved these changes

2020-03-13 16:52 UTC, bstansberry approved these changes

2020-03-13 19:03 UTC, merged