[WFLY-13185]:Add microprofile restclient dependency to jaxrs deployment
wildfly/wildfly pull request #13092
Opened 2020-03-09 13:56 UTC by jimma

https://issues.redhat.com/browse/WFLY-13185

2020-03-11 18:45 UTC, bstansberry requested changes
@jimma I believe you also need to add a line equivalent to this:

https://github.com/wildfly/wildfly/pull/13075/files#diff-aaad68233e8e9273c54f93f079cc27cbR82

@jfdenise Please review

2020-03-12 08:17 UTC, jfdenise commented
@jimma , as @bstansberry pointed, you need to advertise to galleon any module that are not hard dependencies of the extension module.xml (directly or transitively) that you are injecting to deployments. This seems the case there. This is done calling RuntimePackageDependency.optional(MP_REST_CLIENT.getName());

2020-03-12 09:54 UTC, jimma commented
@bstansberry @jfdenise  Fixed. Thanks.

2020-03-12 10:13 UTC, jfdenise approved these changes

2020-03-13 16:00 UTC, bstansberry approved these changes

2020-03-13 19:03 UTC, merged