license check
wildfly/wildfly pull request #13142
Opened 2020-03-25 19:20 UTC by jamezp

This PR somewhat undoes https://issues.redhat.com/browse/WFLY-13232. This is done because of a downstream license check. I'm not entirely sure how it works, but without these changes that test does not pass.

2020-03-25 20:03 UTC, bstansberry commented
@jamezp @dosoudil A change of this magnitude should be backed by a WFLY explaining what the main bits are about. (I don't mean simple things like fixing alphabetical order.) Otherwise people trying to investigate code history will have no clue what happened.

@darranl should agree to the JBoss Negotiation change. I believe it's his project and he recently did https://issues.redhat.com/browse/WFLY-13232 so there's a discrepancy of some sort.

2020-03-25 22:07 UTC, jamezp commented
For the reasons above I'm going to place a hold on this for now. This is definitely not required.

2020-03-26 08:34 UTC, darranl requested changes
This changes for JBoss Negotiation MUST NOT be applied, the project uses the "or later" form of LGPL.

2020-03-26 08:34 UTC, darranl commented on servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
> +          <name>GNU Lesser General Public License v2.1 only</name>
This change MUST NOT be applied, the project uses the "or later" form of LGPL.

2020-03-26 08:34 UTC, darranl commented on servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
> +          <name>GNU Lesser General Public License v2.1 only</name>
This change MUST NOT be applied, the project uses the "or later" form of LGPL.

2020-03-26 08:34 UTC, darranl commented on servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
> +          <name>GNU Lesser General Public License v2.1 only</name>
This change MUST NOT be applied, the project uses the "or later" form of LGPL.

2020-03-26 08:34 UTC, darranl commented on servlet-feature-pack/src/license/servlet-feature-pack-licenses.xml
> +          <name>GNU Lesser General Public License v2.1 only</name>
This change MUST NOT be applied, the project uses the "or later" form of LGPL.

2020-03-26 15:39 UTC, jamezp commented
Given the above comments I'm just going to close this for now.

2020-03-26 15:39 UTC, closed without merging