[WFLY-13370] Eliminate fault-tolerance/executor dependence on ee subs…
wildfly/wildfly pull request #13205
Opened 2020-04-10 16:02 UTC by bstansberry

…ystem module

https://issues.redhat.com/browse/WFLY-13370

2020-04-10 16:02 UTC, bstansberry commented
@rhusar FYI

2020-04-10 17:15 UTC, rhusar requested changes
Thanks @bstansberry , the idea is good, but the PR needs a small change as the tests fail with

```
    Caused by: java.lang.NoClassDefFoundError: javax/enterprise/concurrent/ManagedThreadFactory
```

I assume `galleon-pack/src/main/resources/modules/system/layers/base/org/wildfly/microprofile/fault-tolerance-smallrye/executor/main/module.xml` needs to be updated as well, but I can look during next working day in detail :-)

2020-04-11 02:34 UTC, pferraro approved these changes

2020-04-11 08:30 UTC, rhusar approved these changes
Looks good now!

2020-04-12 17:44 UTC, merged