[WFLY-13396] Tests for RESTEasy integration with WildFly Elytron - Au…
wildfly/wildfly pull request #13229
Opened 2020-04-21 13:25 UTC by Skyllarr

…thenticationClient for Authentication / SSL

[WFLY-13396](https://issues.redhat.com/browse/WFLY-13396)

2020-09-16 05:15 UTC, Skyllarr commented
retest this please

2020-09-16 11:40 UTC, darranl commented
/retest

2020-09-16 18:26 UTC, Skyllarr commented
/retest

2020-09-16 18:40 UTC, Skyllarr commented
/retest

2020-09-16 20:52 UTC, bstansberry requested changes
Hi @Skyllarr 

As both of these tests aren't passing on multiple jobs, please be sure they are passing locally for you before using /retest or pushing your branch. Our CI is somewhat overloaded now and this week it is important to reserve it for things that we know will pass. Please be sure they pass in an execution with -Delytron set and another with -Dts.layers set.

I'm going to cancel the jobs currently running against this as we know some are failing.

2020-09-16 20:52 UTC, bstansberry commented on testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/ssl/UndertowTwoWaySslNeedClientAuthTestCase.java
> +        SSLContext sslContext = AUTH_CONTEXT_CLIENT.getSSLContext(new URI(securedRootUrl.getHost()), contextWithTruststore);
The value returned from URL.getHost() is not valid input to new URI(String str).

2020-09-17 14:11 UTC, Skyllarr commented
> Hi @Skyllarr
> 
> As both of these tests aren't passing on multiple jobs, please be sure they are passing locally for you before using /retest or pushing your branch. Our CI is somewhat overloaded now and this week it is important to reserve it for things that we know will pass. Please be sure they pass in an execution with -Delytron set and another with -Dts.layers set.
> 
> I'm going to cancel the jobs currently running against this as we know some are failing.

Hi @bstansberry, sorry for me overusing the CI. The tests were passing for both me and QE locally, but were failing on CI. I think there was a problem with my using of hard coded "127.0.0.1" address in those failing tests. I have fixed it and I think the CI should pass now.

2020-09-17 14:25 UTC, bstansberry commented
@Skyllarr Thanks. Yes, IPv6 can be an issue that developers don't hit locally. Which is why we make sure CI uses it. :)

Normally CI load isn't a big issue but this week it is.

2020-09-18 00:42 UTC, merged