WFLY-13063: adjust sizes of id cache and confirmation window
wildfly/wildfly pull request #13350
Opened 2020-06-04 18:20 UTC by michpetrov

Issue: [WFLY-13063](https://issues.redhat.com/browse/WFLY-13063)

`id-cache-size` value is the same, I just changed it not to be hard-coded on our end

`confirmation-window-size` changed from 1048576 to 10485760, as this seems to be intended default value as per [ARTEMIS-1261](https://issues.apache.org/jira/browse/ARTEMIS-1261)

2020-06-05 14:58 UTC, pferraro requested changes
@ehsavoie Please review/advise.

In general, changes to an attribute's default value will require:
* Incrementing the model version for the subsystem (this may not be necessary, if the version has already been changed since the last release)
* Registration of appropriate transformers so that the domain controller to transform the model to any host controllers running older versions of WildFly.  See: https://github.com/wildfly/wildfly/blob/master/docs/src/main/asciidoc/_extending-wildfly/Domain_Mode_Subsystem_Transformers.adoc

To achieve this, you can utilize this AttributeConverter instance:
https://github.com/wildfly/wildfly-core/blob/master/controller/src/main/java/org/jboss/as/controller/transform/description/AttributeConverter.java#L97

With this in place, there should be no need to "fix" the model in the subsystem transformer tests.

2020-06-05 15:29 UTC, ehsavoie requested changes
Since this is going to miss WildFly 20 you need to bump the schema version.You should rebase your work over https://github.com/ehsavoie/wildfly/commit/a6ebd35f0b2972e98448f5d31074032b8d922c66. You should manage the model transformation in MessagingTransformerRegistration and not use ModelFixer as @pferraro wrote.

2020-06-05 17:21 UTC, michpetrov commented
Ok, I'll look into that. What's the difference between ModelFixer and Transformer? They seem to be doing the same thing.

2020-06-05 17:34 UTC, ehsavoie commented
ModelFixer 'fix' the model for tests.
Transformers transform the model for retro compatibility

2020-06-08 20:48 UTC, bstansberry reviewed
@ehsavoie The comments I've made here are really more for you than for @michpetrov. The subsystem's management API is fragile because of the use of these values from Artemis.

There's benefit to using the Artemis values. Perhaps we can have a subsystem test that validates all the defaults against a static value? If Artemis changes one, the test would inform us and then you can decide what to do.

2020-06-08 20:48 UTC, bstansberry commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/CommonAttributes.java
> +            .setDefaultValue(new ModelNode(ActiveMQDefaultConfiguration.getDefaultBridgeConfirmationWindowSize()))
Our default values need to be statically declared in our own code base, and not be dependent on external libraries which can change without us noticing.

That or we have to have some test that will notice if any of the values change so we can update the API version, do transformation etc.

The code you're changing already had this problem, so you're not introducing any new problem.

2020-06-08 20:48 UTC, bstansberry commented on messaging-activemq/src/main/java/org/wildfly/extension/messaging/activemq/ServerDefinition.java
> +            .setDefaultValue(new ModelNode(ActiveMQDefaultConfiguration.getDefaultIdCacheSize()))
Here you are introducing a new problem by converting a static value to a changeable one.

2020-06-09 07:29 UTC, ehsavoie commented
@bstansberry I removed all the references to ActiveMQDefaultConfiguration but it looks like i missed some other Artemis related default configuration. I've created https://issues.redhat.com/browse/WFLY-13575 to track this

2020-06-15 11:36 UTC, michpetrov commented
I have refactored the PR.

2020-07-23 16:16 UTC, michpetrov commented
@ehsavoie gotcha, I've updated the file

2020-08-06 21:47 UTC, bstansberry commented
/retest

2021-03-08 21:11 UTC, bstansberry commented
Superseded by #14095

2021-03-08 21:11 UTC, closed without merging