[WFLY-13626] make transaction subsytem CMR attributes optional
wildfly/wildfly pull request #13390
Opened 2020-06-30 18:03 UTC by ochaloup

https://issues.redhat.com/browse/WFLY-13626

2020-06-30 18:04 UTC, ochaloup commented
@kabir if you have a minute would you be so kind and check if the fix on the txn parser is fine?

2020-06-30 18:08 UTC, kabir commented
@ochaloup Only looked quickly while on the meeting, but the original code looks fine to me. If an attribute has a default value (and/or is optional) then it does not need to be part of the add operation.

What is the problem you're trying to fix?

2020-06-30 21:31 UTC, bstansberry requested changes

2020-06-30 21:31 UTC, bstansberry commented on transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem15Parser.java
> +        String value = rawAttributeText(reader, attributeDefinition.getXmlName(), attributeDefinition.getDefaultValue().asString());
@ochaloup The parser can't do this. It needs to preserve what it read from the xml, not introduce default values into the management model that were not what the user put in the xml. The subsystem can use a default value from the AttributeDefinition to configure the runtime services, but what's stored in the management model should reflect the user provided configuration.

It appears this method is only called by the parseCM method, so I think just eliminating the 'else' block that throws missingRequired would be fine.

2020-06-30 21:31 UTC, bstansberry commented on transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystem30Parser.java
> +        String value = rawAttributeText(reader, attributeDefinition.getXmlName(), attributeDefinition.getDefaultValue().asString());
Same comment as I made for TransactionSubsystem15Parser.

2020-07-01 08:35 UTC, ochaloup commented
@kabir the trouble was that attributes behaves as required ones instead of optional
@bstansberry oh, I see. By your suggestion I removed the exception thrown on the missing parameter. It works fine.
I think the parser with my original change was preserving the XML part. But I see it all went against the design principle.

How would you asses the current state?

2020-07-07 01:33 UTC, bstansberry approved these changes
@ochaloup LGTM; thanks.

The issue with storing a default value that wasn't read from the xml in the model is if a later management op that modifies the model is invoked, the server will write over the standalone.xml in order to persist the updated model. And when it does that it will write the default value in the xml.

2020-07-07 01:33 UTC, merged

2020-07-07 01:34 UTC, bstansberry commented
Thanks, @ochaloup