WFLY-13643 Test Case of WFLY-13592 "jndi-view doen't show values for EJB in java:jboss/exported"
wildfly/wildfly pull request #13395
Opened 2020-07-03 12:08 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFLY-13643 

This issue is a test case for https://issues.redhat.com/browse/WFLY-13592.

2020-07-05 17:15 UTC, bstansberry requested changes

2020-07-05 17:15 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/ejb/RemoteNamingEjbTestCase.java
> +public class RemoteNamingEjbTestCase extends JcaMgmtBase{
This test shouldn't subclass JcaMgmtBase just to pick up some utility code. In a later comment I'll explain how to avoid that.

2020-07-05 17:15 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/ejb/RemoteNamingEjbTestCase.java
> +        ModelNode operation = getOperation(address);
Please have a look at org.jboss.as.controller.operations.common.Util.createEmptyOperation.

2020-07-05 17:15 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/naming/remote/ejb/RemoteNamingEjbTestCase.java
> +        ModelNode res = executeOperation(operation);
In the end this is a call to AbstractMgmtTestBase.executeOperation(operation, true) which is just a call to ManagementOperations.executeOperation(getModelControllerClient(), operation). So this is just ManagementOperations.executeOperation(managementClient.getControllerClient(), operation), which can be called directly.

2020-07-06 06:31 UTC, parsharma commented
@bstansberry Thank You for the suggestion, I have updated the code.

2020-07-07 01:43 UTC, bstansberry approved these changes

2020-07-07 01:43 UTC, merged

2020-07-07 01:43 UTC, bstansberry commented
Thanks, @parsharma!