WFLY-13655 LOG INFO level message if the Hibernate second level cache is enabled
wildfly/wildfly pull request #13404
Opened 2020-07-08 19:48 UTC by scottmarlow

https://issues.redhat.com/browse/WFLY-13655

This is a minor change to show when the second cache is enabled.

2020-07-10 12:06 UTC, kabir approved these changes

2020-07-17 21:02 UTC, jamezp requested changes
I'm not really sure I understand the use case for this change. Reading the JIRA and associated JIRA's I didn't get out of it that we should be logging a message like this at a INFO message.

2020-07-17 21:02 UTC, jamezp commented on jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/JpaLogger.java
> +    @Message(id = 20253, value = "second level cache enabled for %s")
This should be "Second", upper case S.

2020-09-16 11:38 UTC, darranl commented
@scottmarlow FYI this one is awaiting a response for the review from @jamezp

2020-12-06 20:54 UTC, bstansberry commented
@scottmarlow If you'd like this in, please adjust the capitalization. Thanks.

2020-12-07 16:39 UTC, scottmarlow commented
I somehow missed the feedback from last summer.  Correcting now.

2020-12-07 16:41 UTC, scottmarlow commented on jpa/hibernate5_3/src/main/java/org/jboss/as/jpa/hibernate5/JpaLogger.java
> +    @Message(id = 20253, value = "second level cache enabled for %s")
Thanks James!

2020-12-07 16:44 UTC, scottmarlow commented
> @scottmarlow If you'd like this in, please adjust the capitalization. Thanks.

@bstansberry just did that, thanks!

2020-12-08 15:42 UTC, scottmarlow commented
> I'm not really sure I understand the use case for this change. Reading the JIRA and associated JIRA's I didn't get out of it that we should be logging a message like this at a INFO message.

@jamezp the idea is to make it more obvious when the second level cache is enabled, since the second level caching comes with a cost and applications may not know that it is enabled.

2020-12-16 01:35 UTC, merged