[WFLY-13177] ManagedExecutorService: Wrong activeRequestCount at RequestController on RejectedExecutionException
wildfly/wildfly pull request #13410
Opened 2020-07-17 12:42 UTC by istudens

Issue: https://issues.redhat.com/browse/WFLY-13177

2020-07-17 12:43 UTC, istudens commented
@emmartins could you review this please? thanks

2020-07-17 13:05 UTC, emmartins commented
@istudens sure will do

2020-07-21 10:10 UTC, istudens commented
retest this please

2020-07-22 07:06 UTC, istudens commented
retest this please

2020-07-22 15:48 UTC, emmartins commented
Hi @istudens , just looked briefly but I believe there are few major issues with the PR:
1. the issue should apply to all wraps of tasks wrt the request controller, not just the submits, since those begin the request
2. you are converting all exceptions to rejected exceptions, when you should just catch any RejectedExecutionException *after* the begin request completes, in the submit/execute, and in such catch *complete the request* and rethrow the exception.

2020-07-23 09:21 UTC, istudens commented
@emmartins I've just added the same logic to the execute method. Could you point me to a code line related to your second comment please? The logic with converting all exceptions to rejected exceptions was there before my fix and it looks good to me. I've only added another case for rejected exception when ControlPoint returns RunResult.REJECTED. Then, ManagedExecutorServiceImpl contains a new logic which catches a rejected exception thrown by super.submit/execute and only in that case it calls controlPoint.requestCompelete which decreases active request counter. If a rejected exception is thrown from doWrapOrThrowException method itself, there is no need to decrease it.

2020-07-23 09:21 UTC, istudens commented
retest this please

2020-07-24 20:36 UTC, emmartins requested changes
Hi @istudens, here are the PR issues wrt 2.
Please note that you may have received additional requests to changes, now not found cause I deleted/edited some. While I don't agree with exceptions in the "wrap" turned into rejected exception, maybe there was a valid reason for such decision, and since that is not related with the original issue let's keep it that way.

2020-07-24 20:36 UTC, emmartins commented on ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
> +            RunResult result = controlPoint.forceBeginRequest();
Exceptions here should be throw, not be converted to RejectedExeception

2020-07-24 20:36 UTC, emmartins commented on ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
> +                ROOT_LOGGER.rejectedDueToMaxRequests();
This is ok.

2020-07-24 20:36 UTC, emmartins commented on ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
> +            final ControlledCallable controlledCallable = new ControlledCallable(callable, controlPoint);
Exceptions in this line and below should not be converted to RejectedException, and request must be completed.

2020-07-24 20:36 UTC, emmartins commented on ee/src/main/java/org/jboss/as/ee/concurrent/ControlPointUtils.java
> +    public static <T> Callable<T> doWrapOrThrowException(Callable<T> callable, ControlPoint controlPoint) {
instead of adding a new method you should fix the existent method, any usage of it has the issue

2020-07-24 20:36 UTC, emmartins commented on ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorServiceImpl.java
> +        try {
this is not ok, any exception should complete the request

2020-07-29 09:32 UTC, istudens commented
retest this please

2020-07-29 09:37 UTC, darranl submitted a review, later dismissed
Can you please change the text in the test case commit.

In five years time when someone looks at the history "a test case" doesn't reveal much, ideally a short sentence saying what the test does.

2020-07-29 13:02 UTC, istudens commented
My fault, I was pushing into another repo. Now it is up to date.
Thanks for your comments.

2020-07-29 13:02 UTC, istudens commented
retest this please

2020-07-29 13:53 UTC, istudens commented
retest this please

2020-07-29 15:27 UTC, emmartins requested changes

2020-07-29 15:27 UTC, emmartins commented on ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorServiceImpl.java
> +        } catch (RejectedExecutionException e) {
should be catching Exception here too

2020-07-30 12:42 UTC, istudens commented on ee/src/main/java/org/jboss/as/ee/concurrent/ManagedExecutorServiceImpl.java
> +        } catch (RejectedExecutionException e) {
I am sorry I missed this.

2020-07-30 14:18 UTC, emmartins commented
retest this please

2020-08-06 15:52 UTC, emmartins approved these changes

2020-08-29 03:10 UTC, bstansberry approved these changes

2020-08-29 19:53 UTC, merged

2020-08-29 19:54 UTC, bstansberry commented
Thanks, @istudens!