WFLY-13354  Add Galleon layers for the EJB subsystem
wildfly/wildfly pull request #13524
Opened 2020-09-02 04:32 UTC by chengfang

JIRA: https://issues.redhat.com/browse/WFLY-13354

Related JIRA: https://issues.redhat.com/browse/EAP7-1524

Analysis doc: https://github.com/wildfly/wildfly-proposals/pull/317

This pull request implements Galleon layers for the EJB subsystems. It includes 3 main ejb3 layers: `ejb3-lite`, `ejb3`, and `ejb-iiop`, and 3 ancillary layers: `ejb-local-cache`, `ejb-dist-cache`, and `iiop-openjdk`. This PR also includes basic testing configuration and community doc for this feature.

MDB-related configuration and tests is not included in this PR; instead it will be implemented and delivered as a separate follow-up feature.

This request currently includes multiple commits over time. I'll squash them if so desired.

2020-09-02 15:41 UTC, chengfang commented
18 clustering tests failed in Galleon Linux JDK11 (not related to ejb). They seem to be intermittent and probably due to CI not stable. Error messages like: `Timed out waiting for responses for request 3 from node-2`. Will re-run it.

```
org.jboss.as.test.clustering.cluster.web.DistributableTestCase.testSerialized
org.jboss.as.test.clustering.cluster.web.DistributableTestCase.testSessionReplication
org.jboss.as.test.clustering.cluster.web.DistributableTestCase.testGracefulServeOnUndeploy
org.jboss.as.test.clustering.cluster.web.DistributableTestCase.testGracefulServeOnShutdown
org.jboss.as.test.clustering.cluster.web.ExternalizerTestCase.test
org.jboss.as.test.clustering.cluster.web.FineNonTransactionalSessionActivationTestCase.test
org.jboss.as.test.clustering.cluster.web.FineTransactionalSessionActivationTestCase.test
org.jboss.as.test.clustering.cluster.web.NonDistributableTestCase.test
org.jboss.as.test.clustering.cluster.web.async.AsyncServletTestCase.test
org.jboss.as.test.clustering.cluster.web.expiration.CoarseSessionExpirationTestCase.test
org.jboss.as.test.clustering.cluster.web.expiration.FineSessionExpirationTestCase.test
org.jboss.as.test.clustering.cluster.web.passivation.CoarseSessionPassivationTestCase.test
org.jboss.as.test.clustering.cluster.web.passivation.FineSessionPassivationTestCase.test
org.jboss.as.test.clustering.cluster.web.shared.LegacySharedSessionTestCase.test
org.jboss.as.test.clustering.cluster.web.shared.SharedSessionTestCase.test
org.jboss.as.test.clustering.cluster.jpa.ClusteredJPA2LCTestCase.testEntityCacheReplication
org.jboss.as.test.clustering.cluster.jpa.custom.ClusteredJPA2LCCustomRegionTestCase.testEntityInCustomCache
org.jboss.as.test.clustering.cluster.jpa.custom.ClusteredJPA2LCCustomRegionTestCase.testPropsInCustomCache
```

2020-09-02 18:54 UTC, bstansberry commented
@chengfang Nice :)

I'll look through this again more thoroughly but I've gone through it and it looks good. @fabiobrz @tommaso-borgato fyi

2 requests, both about testsuite/layers:

1) Please add executions that provision the 'ejb-local-cache' and 'ejb-dist-cache' layers. We want one for all layers as part of a basic smoke check that all layers produce bootable servers. Such a server may not be useful but it should be bootable; that proves the layer doesn't have an unstated dependency that might be a source of bugs.

2) Can you take one of your executions and duplicate it, but add ejb-dist-cache and exclude ejb-local-cache? If you look in testsuite/layers/pom.xml for 'excluded-layers' elements you'll see examples of that kind of thing.

2020-09-02 20:57 UTC, chengfang commented
Will update the PR to address the 2 areas.

2020-09-03 17:02 UTC, bstansberry commented on ee-feature-pack/galleon-common/src/main/resources/layers/standalone/iiop-openjdk/layer-spec.xml
> +    <feature-group name="iiop-openjdk"/>
This feature-group uses 'security="identity"' which AFAICT introduces a requirement for the legacy security subsytem. Which isn't ok; we don't want layers to require the legacy security subsystem

2020-09-03 17:22 UTC, bstansberry commented on ee-feature-pack/galleon-common/src/main/resources/layers/standalone/iiop-openjdk/layer-spec.xml
> +    <feature-group name="iiop-openjdk"/>
If the layer instead specified 'security='elytron'" then a dependency on the 'elytron' layer would be required.

Such a dependency should be declared as optional, to allow the user to exclude the dependency if they intend to change the 'security' value.

2020-09-03 20:56 UTC, bstansberry requested changes

2020-09-03 21:27 UTC, chengfang commented on testsuite/integration/basic/pom.xml
> +                                            <groupId>${project.groupId}</groupId>
will fix it.

2020-09-03 21:27 UTC, chengfang commented on testsuite/integration/basic/pom.xml
> +                                            <groupId>${project.groupId}</groupId>
will fix it.

2020-09-04 03:30 UTC, bstansberry commented
@chengfang I created #13532 to combine this with the JSF layer PR and add some testing that was part of the JSF RFE's test plan.  Once I had the branch I decided to use it to see if EJB testing in testsuite/integration/clustering would help with coverage of jpa-distributed ot help wrap up the JPA RFE.

1) I saw there was no EJB layer execution in testsuite/integration/clustering so I added a commit to #13532 for that. That would be better squashed in here eventually though.

2) Running those tests revealed a problem in the layers here, with the default-sfsb-cache attribute. Basically that should not be directly set by ejb-lite, it should be set by ejb-local-cache and ejb-dist-cache. This results in the usual standalone-full-ha value of 'distributable' when ejb-dist-cache is used. The 2nd to last comint in #13532 does that. I think that would be better squashed in here too though.

2020-09-04 04:03 UTC, chengfang commented
@bstansberry that's great to have ejb layer clustering tests, and have the cache setting fixed. I'll cherrypick the 2 commits and update this PR.

2020-09-04 12:20 UTC, bstansberry commented
@chengfang Great. When you pull those in can you squash this down? I don't care about any commits from me getting squashed into other changes.

2020-09-04 21:59 UTC, bstansberry approved these changes

2020-09-08 08:08 UTC, tommaso-borgato approved these changes

2020-09-09 20:31 UTC, merged