Wfly 13771
wildfly/wildfly pull request #13527
Opened 2020-09-02 15:40 UTC by ehsavoie

This is using the commits from https://github.com/wildfly/wildfly/pull/13524

2020-09-04 21:57 UTC, bstansberry commented
Superseded by #13535 which is this commit on top of the current EJB layers branch.

2020-09-06 18:01 UTC, bstansberry requested changes
@ehsavoie This needs an update to update https://github.com/wildfly/wildfly/pull/13527/files#diff-9a6f6b7a6bd30fddb786db3840aac00f

2020-09-08 11:38 UTC, tommaso-borgato requested changes

2020-09-08 11:38 UTC, tommaso-borgato commented on testsuite/layers/pom.xml
> +                                                <layer>ejb-lite</layer>
@ehugonne I can't see the `remote-activemq` added to `all-layers-provisioning-full` as written in the TP (https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/test-plans/merge_requests/392/diffs#1135f3443166464178d2031722561a56e1bdc307_0_105)

2020-09-08 11:38 UTC, tommaso-borgato commented on testsuite/layers/pom.xml
> +                                                <layer>ejb-lite</layer>
@ehugonne I can't see the `remote-activemq` added to `all-layers-jpa-distributed-provisioning-full` as written in the TP (https://gitlab.mw.lab.eng.bos.redhat.com/jbossqe-eap/test-plans/merge_requests/392/diffs#1135f3443166464178d2031722561a56e1bdc307_0_106)

2020-09-08 12:04 UTC, tommaso-borgato commented
@ehsavoie I see may modifications to existing JMS tests; I didn't find modifications to existing tests in the other EAP7-1444 related RFEs and I couldn't find motivations for these modifications in AD and TP: can you to provide some details on this? is it some refactoring/improvements or something necessary to make tests work also when a slimmed version of the server is used (I mean wildfly with the `remote-activemq` + some other layers)?

2020-09-08 15:15 UTC, ehsavoie commented
@tommaso-borgato the changes are due to enable the same code to use an embedded broker and a remote one. For example with a remote broker you can't rely on a WildFly management operation to get the message count in a topic.

2020-09-09 17:44 UTC, ehsavoie commented
The failure on windows don't seem related.

2020-09-09 20:33 UTC, bstansberry commented
@ehsavoie Please rebase

2020-09-09 20:35 UTC, bstansberry commented
@ehsavoie if you're around though, please wait a bit as I'll merge others that may produce more conflicts

2020-09-09 22:21 UTC, bstansberry commented
@ehsavoie I see this has been through pre-check, so rather than you rebasing I'll do it on top of the other layers branches and I'll push that up and merge the whole set.  @jimma can then base on my branch while you sleep and not wait for you to rebase tomorrow.

2020-09-10 03:04 UTC, bstansberry commented
Superseded by #13546

2020-09-10 03:04 UTC, closed without merging