[WFLY-14135] Do not overwrite the default-stateful-bean-access-timeou…
wildfly/wildfly pull request #13746
Opened 2020-11-27 14:30 UTC by yersan

…t on ejb-dist-cache/ejb-local-cache Galleon layers

Jira issue: https://issues.redhat.com/browse/WFLY-14135

2020-11-27 15:42 UTC, kabir approved these changes

2020-12-01 02:19 UTC, bstansberry commented
@yersan I think the LayersTestCase failure is why the attribute is part of the layer.

2020-12-01 02:21 UTC, bstansberry requested changes
The layers must pass LayersTestCase.

2020-12-01 09:23 UTC, yersan commented
I removed them because I expected the values were merged by Galleon when the affected layers were used in conjunction with ejb / ejb-lite. They are merged correctly, however we are validating each layer in isolation on the LayersTestCase and the attribute removed is mandatory, hence, the failure. I recovered them by using the expected value as timeout.

2020-12-01 14:52 UTC, chengfang approved these changes

2020-12-01 17:11 UTC, bstansberry approved these changes

2020-12-02 02:08 UTC, merged