[WFLY-6660]: Allow to dump Artemis journal to file using WildFly Management API.
wildfly/wildfly pull request #13761
Opened 2020-12-02 08:43 UTC by ehsavoie

* Adding an admin-only operation to print the data of a broker.
* Testing the data printed in safe and full mode.

Jira: https://issues.redhat.com/browse/WFLY-6660
Proposal: https://github.com/wildfly/wildfly-proposals/pull/350

2021-02-15 14:32 UTC, jbliznak requested changes

2021-02-15 14:32 UTC, jbliznak commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/PrintDataTestCase.java
> +        Assert.assertTrue("Should have a message count of 1 for " + jmsQueueName, hasQueueCount);
This check is not enough, the test passes even with `printData(dataPath, false, false); // ~ secure = false` 

but I guess we want to check the secure info is _not printed_ and that is also described in analysis:
> - check that it displays the correct number of total messages and the correct number of message in the queue but doesn't display the queue infos.

2021-02-15 18:25 UTC, jbliznak commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/messaging/mgmt/PrintDataTestCase.java
> +        Assert.assertTrue("Should have a message count of 1 for " + jmsQueueName, hasQueueCount);
Updated, thanks.

2021-02-15 18:35 UTC, jbliznak requested changes
Tests are now testing what they should.

However, I have 2 more points:
First, nice to have - test methods are doing a lot of the same checks, might worth to refactor with methods.

Second, serious one - the tests are prone to leave server in incorrect state (reloaded to admin-only mode) if they fail - I suppose the reloading back to normal mode should be done in `@After` method or in a finally block.

2021-02-16 10:17 UTC, ehsavoie commented
@bstansberry ping for merge :)

2021-02-16 10:18 UTC, jbliznak approved these changes

2021-02-18 19:04 UTC, merged