[WFLY-13706] Add documentation describing how to use the Keycloak adapters with WildFly Elytron.
wildfly/wildfly pull request #13835
Opened 2020-12-18 18:03 UTC by darranl

https://issues.redhat.com/browse/WFLY-13706

2020-12-18 18:08 UTC, darranl commented
I have added the 22.x label as it would be good to get this published so we can start to draw attention to it as a new way to install the Keycloak adapters.

2020-12-21 11:45 UTC, jfdenise requested changes

2020-12-21 11:45 UTC, jfdenise commented on docs/src/main/asciidoc/_elytron/Keycloak_Integration.adoc
> +                <inherit-configs>false</inherit-configs>
inherit-configs and inherit-packages shouldn't be mentioned.

2020-12-21 11:45 UTC, jfdenise commented on docs/src/main/asciidoc/_elytron/Keycloak_Integration.adoc
> +                <inherit-configs>false</inherit-configs>
inherit-configs and inherit-packages shouldn't be mentioned.

2021-01-03 22:35 UTC, bstansberry reviewed
Other than Jean-Francois' comment and one minor typo I noticed, this LGTM so please feel free to merge when those are addressed.

2021-01-03 22:35 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Keycloak_Integration.adoc
> +installed to WildFly including a new subsystem to support configring the client side adapters.  Depending on how
s/configring/configuring

2021-01-05 15:25 UTC, darranl commented
Superseded by https://github.com/wildfly/wildfly/pull/13849

2021-01-05 15:25 UTC, closed without merging