WFLY-14305 Some mistakes in Developer Guide
wildfly/wildfly pull request #13898
Opened 2021-01-18 18:36 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/WFLY-14305
Resolving Some mistakes in Developer Guide

2021-01-18 18:39 UTC, RanabirChakraborty commented
@bstansberry if you can review this :)

2021-01-18 19:25 UTC, bstansberry requested changes
Thanks @RanabirChakraborty

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Application_Client_Reference.adoc
> +libraries, it is perfectly possible to write client application that does
s/write client/write a client/g

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Application_Client_Reference.adoc
> +not uses the application client, but instead use the jboss-ejb-client
s/uses the/use the/g
s/instead use/instead uses/g

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Implicit_module_dependencies_for_deployments.adoc
> +javax.ejb.* classes have a specific name and so does the module which
"has" was correct as the subject is 'module' not 'classes'

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/JTA_Reference.adoc
> +WildFly uses http://narayana.io[Narayana] as the implementation on the JTA specification.
'on' should be removed, and 'of' kept.

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/JTA_Reference.adoc
> +which gives you the chance to change transaction timeout for particular bean/method.
"which gives you the chance to change the transaction timeout for a particular bean/method"

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Migrate_Seam_2_Booking_EAR_Binaries_-_Step_by_Step.adoc
> +wes used. Looking at the server log we see this:
s/wes/was

2021-01-18 19:25 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Migrate_Seam_2_Booking_EAR_Binaries_-_Step_by_Step.adoc
> +shows how problems appear in the log and provide some information on
'provides' was correct

2021-01-19 12:06 UTC, RanabirChakraborty commented
@bstansberry Thanks for the review :) changed it accordingly.

2021-01-19 14:00 UTC, bstansberry approved these changes

2021-01-19 14:42 UTC, merged