[WFLY-14389] Resource-adapters: correctly marshall application elemen…
wildfly/wildfly pull request #13966
Opened 2021-02-08 13:45 UTC by tadamski

…t with expression value

https://issues.redhat.com/browse/WFLY-14389

This fix seem to work for me. In case of application being set to true, it is marshalled as an empty element. In other cases, expression included, it is fully marshalled.

2021-02-08 16:26 UTC, bstansberry requested changes
Hi @tadamski -- please add coverage of this to the xml parsed by ResourceAdaptersSubsystemTestCase.

2021-02-09 13:15 UTC, tadamski commented
hi @bstansberry, I have attached an update to test configuration; with this configuration current master fails and this branch succeedes

2021-02-09 23:06 UTC, bstansberry approved these changes
Nice. :)

2021-02-11 04:16 UTC, merged

2021-02-11 04:16 UTC, bstansberry commented
Thanks, @tadamski