WFLY-14385 Ensure wildfly-clustering-server ProtoStream marshallers use valid protobuf encoding
wildfly/wildfly pull request #13978
Opened 2021-02-10 18:25 UTC by pferraro

https://issues.redhat.com/browse/WFLY-14385

Requires: https://github.com/wildfly/wildfly/pull/13951

2021-02-10 18:27 UTC, pferraro commented
@rhusar Please review

2021-02-11 20:45 UTC, rhusar requested changes

2021-02-11 20:45 UTC, rhusar commented on clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/ChannelCommandDispatcherFactory.java
> +        System.out.println(id + " dispatcher will use " + dispatcherMarshaller.getClass().getName());
Please rid of this System.out.

2021-02-11 20:45 UTC, rhusar commented on clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/CommandResponseMarshaller.java
> +        }
Please run a formatter to fix indentation.

2021-02-11 20:45 UTC, rhusar commented on clustering/server/src/main/java/org/wildfly/clustering/server/dispatcher/CommandResponseMarshaller.java
> +        }
Please run a formatter to fix indentation.

2021-02-12 22:37 UTC, rhusar approved these changes
👍

2021-02-14 02:47 UTC, merged