WFLY-13933 access-log entries might become lost during the shutdown even if graceful timeout is specified
wildfly/wildfly pull request #13997
Opened 2021-02-16 09:02 UTC by baranowb

ISSUE: https://issues.redhat.com/browse/WFLY-13933
Depends: https://issues.redhat.com/browse/UNDERTOW-1794

2021-04-26 08:37 UTC, baranowb commented
@darranl I will rebase it. Someone I did not see this mention.

2022-01-31 11:28 UTC, darranl commented
@baranowb This PR and RFE looks like it still needs quite a bit of work to get it ready - should we close this PR for now and reopen once we are ready?

2024-04-30 09:34 UTC, fl4via requested changes
I can't see the new close retry delay and close retry count being used anywhere? Do we want to make them both configurable? (see question in the analys document PR about this: https://github.com/wildfly/wildfly-proposals/pull/374#discussion_r1584455794 )

2024-04-30 09:41 UTC, fl4via commented
> I can't see the new close retry delay and close retry count being used anywhere? 
Now I see, it is in the Undertow PR, second commit: https://github.com/undertow-io/undertow/pull/1041/commits/77cb16d229092425f41b37e6214523d312edcd34

2024-04-30 09:50 UTC, fl4via commented
I am sugesting breaking this PR in two parts, one that is a normal bug fix and can be merged as such immediately, and another one that contains the new configuration will follow the WildFly feature process. Please see my comments in the Jira.

2025-10-22 08:02 UTC, closed without merging

2025-10-22 08:03 UTC, baranowb commented
huh? what the hell happened here?