WFLY-14388 resolve expression for transaction-support attribute in r-a subsystem.
wildfly/wildfly pull request #14059
Opened 2021-03-01 13:40 UTC by soul2zimate

Issue: https://issues.redhat.com/browse/WFLY-14388  resolve expression for transaction-support attribute in r-a subsystem.

In r-a subsystem `ResourceAdapterSubsystemParser` and `ResourceAdapterParser` rely on resolved value of `transaction-support` (user specified transaction support level of the resource adapter among `NoTransaction`, `LocalTransaction` and `XATransaction`) to read/write connection-definition attributes. It's not a perfect approach, but that's the reason `transaction-support` attribute is defined to determine XA.

Also I have removed unused `isXa` in `parseTimeOut`and unused `resource-adapters-xapool-expression2.xml`

@tadamski  please review. thanks.

2021-03-04 10:28 UTC, tadamski approved these changes
LGTM

2021-03-04 19:53 UTC, bstansberry commented
Sounds fine so long as we're in agreement re what I say at https://issues.redhat.com/browse/WFLY-14388?focusedCommentId=15896045&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15896045

2021-03-08 10:38 UTC, istraka requested changes

2021-03-08 10:38 UTC, istraka commented on connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdapterParser.java
> +                            ModelNode transactionSupport = TRANSACTION_SUPPORT.parse(value, reader);
`SimpleAttributeDefinition#parse` is deprecated. Can you use `getParser` as JavaDoc suggests?

2021-03-08 18:31 UTC, merged