WFLY-14317 Replace 'Java Message Service|JMS' references in java doc …
wildfly/wildfly pull request #14088
Opened 2021-03-06 17:47 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/WFLY-14317
(Replace "Java Message Service|JMS" references in java doc with corresponding Jakarta EE ones)
Link with: https://github.com/wildfly/wildfly/pull/13808

2021-03-06 17:48 UTC, RanabirChakraborty commented
@ehsavoie If you can review this PR :)

CC: @asoldano @scottmarlow

2021-03-09 16:01 UTC, ehsavoie requested changes

2021-03-09 16:02 UTC, ehsavoie commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Backward_&_Forward_Compatibility.adoc
> +* forward compatibility: legacy Jakarta Messaging clients (using HornetQ) can connect
or just use messaging

2021-03-09 16:02 UTC, ehsavoie commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Backward_&_Forward_Compatibility.adoc
> +Forward compatibility requires no code change in legacy Jakarta Messaging clients. It
or just use messaging

2021-03-09 16:02 UTC, ehsavoie commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Backward_&_Forward_Compatibility.adoc
> -entries must match the lookup expected by the legacy JMS client.
or just use messaging

2021-03-09 16:02 UTC, ehsavoie commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging_Backward_&_Forward_Compatibility.adoc
> +legacy Jakarta Messaging clients will not be able to communicate with WildFly 10
or just use messaging

2021-03-09 18:11 UTC, RanabirChakraborty commented
@ehsavoie Thanks! Did the changes accordingly :) please check once

2021-03-09 20:13 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Messaging.adoc
> +Jakarta Messaging servers, as long as they are JMS 1.1 compliant.
@ehsavoie Right now we should probably treat our docs as not being about WildFly Preview (i.e. where EE 9 variants of the specs come into the picture.) We'll probably need a major effort to deal with EE 9-specific changes like you've noted here.

2021-03-09 22:36 UTC, merged