[WFLY-12215] Documentation for encrypted expression support.
wildfly/wildfly pull request #14084
Opened 2021-03-05 19:07 UTC by darranl

https://issues.redhat.com/browse/WFLY-12215

2021-03-08 17:22 UTC, bstansberry requested changes

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +`PasswordCredential`, `KeyPairCredential`, and `SecretKeyCredential`.  The second implementation is the `PropertiesCredentialStore` this credential
s/ this credential/. This credential/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +of the credentials it stores so it's primary purpose is to provide an initial key to a server environment.
s/it's/its

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This documentation is primarily focussed on the `KeyStoreCredentialStore` and `PropertiesCredentialStore`; however the section <<Custom_CredentialStore, Custom CredentialStore>> describes the SPIs fo
https://proofreadmyessay.co.uk/writing-tips/spelling-tips-focused-or-focussed/

Up to you. :)

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This documentation is primarily focussed on the `KeyStoreCredentialStore` and `PropertiesCredentialStore`; however the section <<Custom_CredentialStore, Custom CredentialStore>> describes the SPIs fo
s/implementatin/implementing

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +NOTE: The command line tool only creates the instance of the credential store on the underlying file system, the management operation is still required to define the credential store in the `elytron`
s/system, the management/system; the management/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This is a simple credential store implementation which can only be used to store `SecretKey` instances.  This credential store also does not offer any protection of the contents.  Within an applicati
s/well know/well known/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +This is a simple credential store implementation which can only be used to store `SecretKey` instances.  This credential store also does not offer any protection of the contents.  Within an applicati
s/initial secret, although/initial secret. Although/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +WARNING: If you rely on automatic generation of a `SecretKey` be sure to create a backup of the key when you can, if you were to loose the key we do not have a mechanism to decrypt anything
s/can, if/can. If/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +By default the `credential-store` resource assumes the type to be removed is `PasswordCredential`, if a diffierent type is to be removed it can be specified with the `entry-type=SecretKeyCredential`
s/`PasswordCredential`, if/`PasswordCredential`. If/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Credential_Store.adoc
> +By default the `credential-store` resource assumes the type to be removed is `PasswordCredential`, if a diffierent type is to be removed it can be specified with the `entry-type=SecretKeyCredential`
s/diffierent/different

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Encrypted_Expressions.adoc
> +In both cases the `ENC` prefix is used to identify the expression is an encrypted expression, this prefix is the default however it is possible to define an alternative prefix for use
s/expression, this/expression. This/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Encrypted_Expressions.adoc
> +NOTE: The following section illustrates how to create an encrypted expression, if you repeat the same command for the same clear text is it normal that a different
s/expression, if/expression. If/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Encrypted_Expressions.adoc
> +NOTE: The following section illustrates how to create an encrypted expression, if you repeat the same command for the same clear text is it normal that a different
s/is it normal/it is normal/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Encrypted_Expressions.adoc
> +To make use of encrypted expressions in the host controler configuration the `expression=encryption` resource and relevant `*credential-store` definitions must be defined within the `elytron` subsyst
s/controler/controller

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Encrypted_Expressions.adoc
> +The `--encrypt` action is used with the `credential-store` command, the argument to this action is the alias of the secret key to use.  In this form the tool will prompt
s/command, the argument/command. The argument/g

2021-03-08 17:22 UTC, bstansberry commented on docs/src/main/asciidoc/_elytron/Encrypted_Expressions.adoc
> +twice for the clear text which is being encrypted.  When using the command line tool the output is just the Base64 encoded encrypted ciphertext, to use this in the management model
s/ciphertext, to use/ciphertext. To use/g

2021-03-09 09:58 UTC, darranl commented
@bstansberry FYI I have marked each of your comments as resolved as I have implemented every suggestion.

2021-03-09 14:31 UTC, merged