[WFLY-14566] Fix JSFDeploymentProcessorTestCase on Java11+secmgr
wildfly/wildfly pull request #14115
Opened 2021-03-12 15:44 UTC by spyrkob

Issue: https://issues.redhat.com/browse/WFLY-14566

2021-03-15 10:23 UTC, darranl requested changes
When any proposed changes the permissions granted to test deployments are submitted we need the PR or code change to be accompanied with a description.  Ideally I would like to see the original error including full stack trace.

If I am reading this correctly there is an issue in an underlying component - we should not be adding permissions to test cases to work around these issues.  If there is an underlying problem we should be looking to address that.

2021-03-16 14:51 UTC, spyrkob commented
Added more information in the PR description and the stack trace in JIRA.

The root cause is indeed an issue in commons-beanutils. If it's better to wait for the component fix, I'll close this PR.

2021-03-17 11:52 UTC, darranl commented
@fjuma Do you have any thoughts on this one?  It looks to me like the priority should be fixing https://issues.apache.org/jira/browse/BEANUTILS-547 rather than adding a permission to the deployment.

2021-03-17 13:49 UTC, fjuma commented
@spyrkob @darranl Since the root cause is in commons-beanutils, we should make sure the problem is fixed there instead of adding the permission to the deployment.

2021-03-18 08:45 UTC, spyrkob commented
Thanks, I'll close this and see if the component issue can be resolved

2021-03-18 08:45 UTC, closed without merging