[WFLY-14762] Expose complete-timeout Infinispan transaction setting
wildfly/wildfly pull request #14271
Opened 2021-05-04 16:07 UTC by spyrkob

Issue: https://issues.redhat.com/browse/WFLY-14762

2021-05-04 16:08 UTC, spyrkob commented
@pferraro could you review when you have a moment?

2021-05-05 00:21 UTC, pferraro requested changes

2021-05-05 07:03 UTC, spyrkob commented
Thanks @pferraro, changes made.

2021-05-05 09:24 UTC, spyrkob commented
@pferraro does this change need a RFE doc as well?

2021-05-05 12:35 UTC, pferraro commented
> @pferraro does this change need a RFE doc as well?

No - this is a bug fix, not an enhancement.

2021-05-05 12:46 UTC, pferraro requested changes

2021-05-05 12:46 UTC, pferraro commented on clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_13_0.xsd
> +                    Only applies to a BATCH transaction mode.
This attribute applies to any transactional cache, not just BATCH mode.

2021-05-05 14:01 UTC, pferraro approved these changes

2021-05-07 02:41 UTC, merged