WFLY-14488 AppClientScriptTestCase fails if host defines _JAVA_OPTIONS environment variable
wildfly/wildfly pull request #14323
Opened 2021-05-27 09:35 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFLY-14488

2021-06-04 10:02 UTC, yersan reviewed
For the sake of completeness, JAVA_TOOL_OPTIONS could be also taken into account.

Maybe a possible approach instead of using a regular expression could be just to skip the line if it starts with "Picked up " looping over `script.getStdout()`, so it could more resilient to future JDK changes.

2021-06-07 11:23 UTC, parsharma commented
Thanks,@yersan for your review comments.

2021-06-07 15:12 UTC, yersan requested changes

2021-06-08 05:35 UTC, parsharma commented on testsuite/scripts/src/test/java/org/wildfly/test/scripts/AppClientScriptTestCase.java
> +        final int expectedLines = (script.getShell() == Shell.BATCH ? 3 : javaOptions ? count : 2);
I have updated the code, thanks.

2021-06-08 09:05 UTC, yersan approved these changes

2021-06-13 02:04 UTC, merged