[WFLY-14968] Collapse if-statements (Undertow)
wildfly/wildfly pull request #14424
Opened 2021-07-03 06:53 UTC by boris-unckel

Fixes https://issues.redhat.com/browse/WFLY-14968

2021-07-15 11:02 UTC, yersan approved these changes
LGTM, although component lead could have issues with the cosmetic changes

2021-07-15 11:44 UTC, boris-unckel commented
@bstansberry This one has passed tests and is approved, too. Please, could you check and merge?

2021-07-15 11:46 UTC, darranl commented
Just be clear regarding approval, the last comment was that the component lead may want an opportunity to review the code for the component they maintain.

2021-07-15 11:47 UTC, darranl commented
@fl4via FYI

2021-07-15 11:53 UTC, boris-unckel commented
My apologies getting this wrong. I don't want to break any formal or informal rules of review and approval. @darranl Thanks for the clarification. @bstansberry  Please ignore my previous merge request.

2021-07-29 03:52 UTC, boris-unckel commented
Good Morning @fl4via , could you review and approve this PR, please? It's one of two missing to finish the Jira and I hope to get it into the release.

2021-08-20 15:02 UTC, rhusar requested changes

2021-08-20 15:02 UTC, rhusar commented on undertow/src/main/java/org/wildfly/extension/undertow/DiskBasedModularPersistentSessionManager.java
> +                && !baseDir.mkdirs()) {
Just put these on the same line for readability.

2021-08-20 15:02 UTC, rhusar commented on undertow/src/main/java/org/wildfly/extension/undertow/deployment/ServletContainerInitializerDeploymentProcessor.java
> +                                && sciClasses.add(service.getClass())) {
Just put these on the same line for readability.

2021-08-20 15:02 UTC, rhusar commented on undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
> +                && deploymentUnit.getParent() == null) {
Just put these on the same line for readability.

2021-08-20 15:02 UTC, rhusar commented on undertow/src/main/java/org/wildfly/extension/undertow/deployment/UndertowDeploymentProcessor.java
> +                    && k.startsWith(OLD_URI_PREFIX)) {
Just put these on the same line for readability.

2021-08-20 15:02 UTC, rhusar commented on undertow/src/main/java/org/wildfly/extension/undertow/security/digest/DigestAuthenticationMechanism.java
> +                && !OPAQUE_VALUE.equals(parsedHeader.get(DigestAuthorizationToken.OPAQUE))) {
Just put these on the same line for readability.

2021-08-20 15:02 UTC, rhusar commented on undertow/src/main/java/org/wildfly/extension/undertow/security/jacc/WarJACCService.java
> +                && seenMethods.size() != NUMBER_OF_HTTP_METHODS) {
Just put these on the same line for readability.

2021-08-21 19:41 UTC, boris-unckel commented
@rhusar Hi Radoslav, thanks for your feedback. It's fixed. Could you review again, please?
@fl4via fyi

2021-10-13 17:26 UTC, fl4via approved these changes

2021-10-13 17:27 UTC, fl4via commented
@boris-unckel thanks for reopening! @bstansberry  this one is good to go

2021-10-15 17:01 UTC, merged