WFLY-14988 Inside clustering remove unnecessary unboxing to clean code
wildfly/wildfly pull request #14456
Opened 2021-07-08 18:07 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/WFLY-14988

2021-07-08 19:59 UTC, RanabirChakraborty commented
@pferraro please take a look once you get back.

2021-07-13 15:26 UTC, pferraro requested changes

2021-07-23 19:57 UTC, RanabirChakraborty commented
@pferraro can you please review this :)

2021-07-23 21:22 UTC, pferraro approved these changes

2021-07-24 02:06 UTC, merged