[WFLY-15044] Avoid Nullpointer (IIOP)
wildfly/wildfly pull request #14566
Opened 2021-08-21 21:54 UTC by boris-unckel

Fixes https://issues.redhat.com/browse/WFLY-15044

2021-09-22 01:03 UTC, bstansberry commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/rmi/ValueAnalysis.java
> +            if (wo != null && spf != null) { // Right modifiers?
@tadamski Please review.

I suspect this isn't the right fix here and that the problem is that L177 should be

int mods = wo.getModifiers();

I don't see why the modifiers of the 'serialPersistentFields' field would be relevant at this point.

2021-09-28 10:32 UTC, tadamski requested changes
@bstansberry I agree, spf seems irrelevant in this place and it looks like a bug.
@boris-unckel I believe this PR should be modified according to Brian's suggestion.

2021-09-28 11:10 UTC, boris-unckel commented
@tadamski Fixed accordingly. Could you check again and approve, please?

2021-09-28 11:27 UTC, tadamski approved these changes

2021-09-28 11:27 UTC, tadamski commented
@boris-unckel Approved.

2021-10-04 21:46 UTC, merged