[WFLY-14350] Allows DEFAULT_CONTEXT_PROPAGATION to use expressions and sets default value
wildfly/wildfly pull request #14578
Opened 2021-08-25 07:49 UTC by xjusko

Fixes https://issues.redhat.com/browse/WFLY-14350

2021-08-31 19:31 UTC, bstansberry commented
/ok-to-test

2021-12-16 12:53 UTC, darranl commented
@bstansberry should changing the use of expressions trigger a version bump?  It feels like we should detect in transformers.

2023-03-24 17:25 UTC, darranl requested changes
This will need a model version bump and also transformer support as older secondary host controllers would not recognise the expressions on these resources.

2023-04-04 16:14 UTC, xjusko commented
So if I understand this correctly, should I create a new xsd schema version which differs from 3.0 only in allowing expression in DEFAULT_CONTEXT_PROPAGATION?
If yes, then the new xsd schema would be the same as 3.0 and the parser should be able to parse both definitions of DEFAULT_CONTEXT_PROPAGATION based on the version of xsd?

2025-11-22 22:40 UTC, bstansberry commented
@tomjenkinson The XTS subsystem was deprecated in Nov 2020 via WFLY-14093. Do we want a change like this? If not let's close the PR and resolve the JIRA.

If we want it Marek would need to bump the management API version and add a new xsd version, plus add a domain transformer. The basic effect of all that would be to properly document in the read-resource-description output and in the xsd that the default value is false. There's no change in how the actual services work as the code was already using false as a default

2025-11-24 09:03 UTC, tomjenkinson commented
I would say no and have just updated two other issues which had the XTS component (I left a test fix). If Marek was really keen on it, I think it could be argued to re-raise but in case Marek is neutral on it and for clarity for future I will close this pull request and resolve/close the JIRA. Thank you for asking, and thank you Marek for the contribution!

2025-11-24 09:03 UTC, closed without merging