[WFLY-15075] Add encryption and integrity support to FilesystemSecurityRealm
wildfly/wildfly pull request #14582
Opened 2021-08-26 18:33 UTC by Ashpan

Jira: https://issues.redhat.com/browse/WFLY-15075

Requires: https://issues.redhat.com/browse/WFCORE-5530
WildFly Core PR with tests: https://github.com/wildfly/wildfly-core/pull/4722

2021-10-07 19:39 UTC, fjuma requested changes

2021-11-04 17:22 UTC, Ashpan commented on testsuite/integration/elytron/src/test/java/org/wildfly/test/integration/elytron/realm/FilesystemRealmEncryptedTestCase.java
> +    public void testEncryptionFail(@ArquillianResource URL webAppURL) throws Exception {
Added a test that uses the wrong key. Receives an `INTERNAL_SERVER_ERROR`
https://github.com/wildfly/wildfly/pull/14582/files?authenticity_token=7sKc1zgUU%2Fp01mR1dR7M3eJLQi%2Bgq6bCQtdXeKpRoNAo4WWJuGZnDOAYT%2FnIE456qvCUqoQwfiOgujKO0iB1Jg%3D%3D&file-filters%5B%5D=.java#diff-6cc7095e29da23e05a90f17be79648563cfae719bc9c73e74c4b46cb4ab2e3eeR99-R106

2022-03-01 02:21 UTC, bstansberry commented on pom.xml
> +
Hi @Ashpan 

Please adjust your editor config so it doesn't make this kind of whitespace change. Mass whitespace changes increase the chances of merge conflicts between PRs and tend to obscure the important parts of a change.

2022-03-01 15:30 UTC, Ashpan commented
Closed this PR and reopened new one with only Encryption changes.

https://github.com/wildfly/wildfly/pull/15269

2022-03-01 15:30 UTC, closed without merging