[(nobranch,rebasingWFCORE-5343)]:  [WFCORE-5343]: Preparing YAML Support
wildfly/wildfly pull request #14614
Opened 2021-09-06 13:28 UTC by ehsavoie

* Adding metadata for the underlying types for a list attrbite definition.

Thanks for submitting your Pull Request!

Please delete this text, and add a link to the Jira issue solved by this PR.

Remember to use the Jira issue ID in the PR title, and any commits.

2021-12-07 17:25 UTC, bstansberry requested changes
As discussed at https://github.com/wildfly/wildfly/pull/15006#issuecomment-988123885 the TimerAttributeDefinition and LegacySupport changes should not be needed.

2022-03-04 20:01 UTC, ehsavoie commented
Fixed and rebased

2022-06-10 19:18 UTC, bstansberry requested changes
@ehsavoie The test aspects of this seem to be WIP that needs to be completed.

2022-06-10 19:18 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/appclient/basic/AppClientMain.java
> -
Please restore this line (just to get this commit out of the file's history.)

2022-06-28 11:20 UTC, ehsavoie commented
@bstansberry all should be fixed now :)

2022-09-19 17:17 UTC, bstansberry approved these changes

2022-09-19 17:17 UTC, bstansberry commented
/help

2022-09-19 17:18 UTC, bstansberry commented
/re-test

2022-09-19 17:19 UTC, bstansberry commented
/retest

2022-09-20 01:37 UTC, merged

2022-09-20 01:37 UTC, bstansberry commented
Thanks @ehsavoie