[WFLY-14255] allow configuration of reuse-x-forwarded and rewrite-hos…
wildfly/wildfly pull request #14859
Opened 2021-10-29 08:25 UTC by baranowb

…t attributes in ReverseProxy

Issue: https://issues.redhat.com/browse/WFLY-14255

2021-11-01 09:52 UTC, darranl commented
Added "missing-reqs" as a feature request,

2021-11-01 09:56 UTC, darranl requested changes
As commented in the other PR, please separate the bump into it's own commit so we can see the changes made to the new version - at the moment the changes specific to this feature are not visible.

2022-03-04 04:47 UTC, fl4via requested changes

2022-03-04 04:47 UTC, fl4via commented on undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem140TestCase.java
> + * Copyright 2021, Red Hat, Inc., and individual contributors
Is this really 2021?

2022-03-04 04:47 UTC, fl4via commented on undertow/src/test/resources/org/wildfly/extension/undertow/undertow-14.0.xml
> +  ~ Copyright 2021, Red Hat, Inc., and individual contributors
Same here. All headers should be checked.

2022-03-04 04:49 UTC, fl4via approved these changes

2022-03-04 04:50 UTC, fl4via commented
Other than the headers, this looks good to me @baranowb

2022-03-04 10:57 UTC, baranowb commented on undertow/src/test/java/org/wildfly/extension/undertow/UndertowSubsystem140TestCase.java
> + * Copyright 2021, Red Hat, Inc., and individual contributors
It was.

2023-09-29 21:57 UTC, rezsekzs commented
Hi Guys, 

We are waiting long time ago for that. Because of this missing feature, we have to patch undertow, to override this property's default value under Wildfly. How can we help to speed up the ticket?

Thank So Much

2023-10-05 06:16 UTC, closed without merging

2023-10-05 06:16 UTC, baranowb commented
Im going to close this one, as this one is obsolete.