[WFLY-15732] / [WFLY-15356] Remove use of security-plugins from Undertow subsystem.
wildfly/wildfly pull request #14936
Opened 2021-11-23 19:31 UTC by darranl

https://issues.redhat.com/browse/WFLY-15732

2021-11-23 19:34 UTC, darranl commented
Hello @fl4via could you please review this one, hopefully helps with less code to transform in the Undertow subsystem as well as this removes some Jakarta API implementations.

@pferraro Could you please take a look at the clustering code I have deleted and let me know if I gone far enough / too far?

There will be some further clean up later when it comes to making application security domain resources optional, but for now I just want to eliminate the final pieces of code still calling the legacy APIs and report an error if they are called.

2021-12-15 19:07 UTC, ropalka approved these changes
Since this is about code removal I was able to review this PR.

2021-12-16 16:16 UTC, pferraro requested changes
Is the intention to deprecate the resource defined by HostSingleSignOnDefinition?
This resource is still functional, and this PR only seems to remove clustered behavior (the local implementation is still intact).

2021-12-16 16:16 UTC, pferraro commented on clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/UndertowSecuritySerializationContextInitializer.java
> -        super("io.undertow.security.api.proto");
The file `clustering/web/undertow/src/main/resources/io.undertow.security.api.proto` should also be removed.

2021-12-16 16:16 UTC, pferraro commented on clustering/web/undertow/src/main/java/org/wildfly/clustering/web/undertow/sso/UndertowSingleSignOnManagementProvider.java
> -@MetaInfServices(HostSingleSignOnManagementProvider.class)
While the distributed HostSingleSignOnManagementProvider was removed (by deleting this class and its supporting classes), the org.wildfly.extension.undertow.HostSingleSignOnServiceHandler class will still configure an in-memory single sign-on provider.
Should this not also be removed?

2022-01-16 20:37 UTC, merged