[WFLY-10886] improve performance from AbstractJMSContext.getContext
wildfly/wildfly pull request #15036
Opened 2021-12-16 19:09 UTC by fbrandaouolinc

Change AbstractJMSContext.getContext from synchronized method to ConcurrentHashMap for improved performance

https://issues.redhat.com/browse/WFLY-10886

2021-12-16 19:11 UTC, saulocn approved these changes

2021-12-17 11:23 UTC, darranl commented on messaging-activemq/injection/src/test/java/org/wildfly/extension/messaging/activemq/deployment/injection/AbstractJMSContextTestCase.java
> +package org.wildfly.extension.messaging.activemq.deployment.injection;
All new classes should have a copyright header added with the year set to the current year,

2021-12-17 11:24 UTC, darranl commented
@ehsavoie Could you please give this a review?

2021-12-17 17:09 UTC, felipe-toshio approved these changes

2021-12-21 09:50 UTC, ehsavoie commented
Could you please squash your commits ?
Otherwise looks good to me.

2021-12-21 09:50 UTC, ehsavoie requested changes
squash the commits please

2021-12-23 11:17 UTC, fbrandaouolinc commented
Hi @ehsavoie , @darranl ,

Do you have any other considerations?

Thanks

2022-01-06 12:35 UTC, fbrandaouolinc commented
@jmesnil can you see this PR, please?

2022-01-06 12:40 UTC, ehsavoie approved these changes

2022-01-09 20:30 UTC, darranl commented
Sorry just taken off "ready for merge" do we also have a PR against main?

2022-01-11 20:45 UTC, fbrandaouolinc commented
> Sorry just taken off "ready for merge" do we also have a PR against main?

No, we do not have a PR against main.
I'll open, okay?

2022-01-11 21:55 UTC, fbrandaouolinc commented
@darranl I've create the PR against main: https://github.com/wildfly/wildfly/pull/15077

2022-01-13 17:42 UTC, bstansberry commented
I just kicked off another run of the "Linux with security manager" job, but reconfigured to use -Dts.multinode instead of -DallTests, which means most of the integration testsuite won't run, but the module where the current job had failures will. So it will take much less time to run. I'd be shocked if this PR has anything to do with the current failures.

I'm not concerned about the 1 failure in "Linux - JDK 8" as that tests is well known for intermittent failures.

2022-01-13 19:43 UTC, fbrandaouolinc commented
> I just kicked off another run of the "Linux with security manager" job, but reconfigured to use -Dts.multinode instead of -DallTests, which means most of the integration testsuite won't run, but the module where the current job had failures will. So it will take much less time to run. I'd be shocked if this PR has anything to do with the current failures.
> 
> I'm not concerned about the 1 failure in "Linux - JDK 8" as that tests is well known for intermittent failures.

Hi, the PR against main have failures in differents tests of this 2 suites.

2022-01-22 03:06 UTC, merged

2022-01-22 03:06 UTC, bstansberry commented
Thanks @fbrandaouolinc