[WFLY-14967] Move WildFly Preview to a native Jakarta namespace varia…
wildfly/wildfly pull request #15070
Opened 2022-01-08 22:04 UTC by boris-unckel

…nt of the jpa/eclipselink module

Fixes https://issues.redhat.com/browse/WFLY-14967

2022-01-09 15:07 UTC, boris-unckel commented
@scottmarlow Could you review and approve this PR, please? It's the successor of #14855 implementing step 3 and 4 of https://github.com/wildfly/wildfly/pull/14855#issuecomment-962580936 It was not optional to use eclipselink 3.0.2 due to compile errors (javax.* vs. jakarta.*).

@bstansberry Due to splitting up the previous PR into several steps all your requirements https://github.com/wildfly/wildfly/pull/14855#discussion_r743993385 should be fulfilled now. Please have a look.

@yersan Thanks for your hint https://github.com/wildfly/wildfly/pull/14855#discussion_r772289876 regarding the correct place for the module/license. I have implemented it in this way, please have a look.

Thank you all for your support.

2022-01-11 12:57 UTC, yersan approved these changes
Changes look good to me

2022-01-11 14:32 UTC, scottmarlow commented on ee-9/source-transform/jpa/eclipselink/pom.xml
> +  ~ Copyright 2021, Red Hat, Inc., and individual contributors
If this pr was created 3 days ago, the Copyright date could be 2022.

2022-01-11 14:34 UTC, scottmarlow requested changes
Please update copyright date in ee-9/source-transform/jpa/eclipselink/pom.xml  to 2022 or explain why its 2021.

2022-01-11 14:40 UTC, scottmarlow approved these changes

2022-01-11 14:42 UTC, scottmarlow commented
Looks good to me, I couldn't hide my second comment above that is still visible but since the date was changed to 2022, I have no concerns now.  Thanks for the change @boris-unckel !

2022-01-11 17:46 UTC, luck3y commented
/retest

2022-01-18 23:30 UTC, merged

2022-01-18 23:31 UTC, bstansberry commented
Thanks, @boris-unckel