WFLY-15524]: Upgrade netty from 4.1.68 to 4.1.72.
wildfly/wildfly pull request #15122
Opened 2022-01-17 20:56 UTC by ehsavoie

* Upgrading netty to 4.1.72.
* Removing netty-all and using the proper netty artefacts in pom.xml.
* Removing the io.netty jboss module and creating io.netty.netty-*
modules for each artefact.
* Adding a task to manage the native parts.
* Adding the missing io.netty.netty-handler dependency to the artemis journal module.

Jira: https://issues.redhat.com/browse/WFLY-15935
Jira: https://issues.redhat.com/browse//WFLY-15524

2022-01-18 07:51 UTC, jmesnil commented
@ehsavoie could you please mention in the PR description the upstream PRs for the `main` branch?

2022-01-18 08:01 UTC, ehsavoie commented
@jmesnil Done.
Also I'm not sure the CI failures are related to that PR

2022-01-18 08:08 UTC, jmesnil commented
@ehhttps://ci.wildfly.org/buildConfiguration/WF_PullRequest26x_WindowsJdk11/290926?showRootCauses=false&expandBuildChangesSection=true&expandBuildTestsSection=true might be related

OIDC failures are a known regression that will be fixed by an upcoming WildFly Core release

2022-01-18 15:22 UTC, jmesnil reviewed
@ehsavoie can you explain why the replacement of netty-all required the creation of all these JBOss modules?

Couldn't they all be provided by `io.netty`? 
As the PR stands, that seems to be a significant changes for 26.0.1.Final?

2022-01-18 15:34 UTC, ehsavoie commented
@jmesnil  The initial goal was to reduce the size and to have modules only depending of what they required instead of depending on everything as some parts are only used by some subsystems.
I agree that it it 'big' for 26.0.1 but it is cleaner in the long run.

2022-01-18 15:35 UTC, jmesnil requested changes
We can't remove `io.netty` module in a micro release of WildFly.
Brian told me that the reason it was removed was that we could not keep this module and exposing a different set of resources.
Adding artifacts until we are able to provide an identical `io.netty` would required new devs and we are past the freeze for WildFly 26.0.1.Final.

This PR will have to wait after this release to be merged.

2022-01-18 15:50 UTC, jmesnil commented
@boris-unckel  my understanding is that CVE-2021-43797  is not relevant for WildFly as we don't use Netty for HTTP. @ehsavoie is that correct?

2022-01-18 16:36 UTC, boris-unckel commented
@jmesnil @ehsavoie @bstansberry thank you all to clarify the impact.

2022-03-01 23:27 UTC, merged

2022-03-01 23:28 UTC, bstansberry commented
Thanks, @ehsavoie