[WFLY-15748] / [WFLY-13889] Remove PicketBox from the testsuite.
wildfly/wildfly pull request #15120
Opened 2022-01-17 11:37 UTC by darranl

This supersedes https://github.com/wildfly/wildfly/pull/14949 as GitHub was incorrectly reporting a merge conflict.

Remove dependencies on the PicketBox module and APIs for the testsuite.
https://issues.redhat.com/browse/WFLY-15748
Also resolve https://issues.redhat.com/browse/WFLY-15843

2022-01-17 14:46 UTC, darranl commented
@ropalka / @bstansberry This one is ready to review to get this batch of testsuite deletions in so we can see what is left.

2022-01-18 14:18 UTC, ropalka requested changes
Wouldn't it be possible to rework this PR to simplify and ensure proper review @darranl ?

It was easy to review commits related to Picketbox removal from test suite,
but the last three "sync with upstream" are almost impossible to review :(
I can't verify them if they are correct or if there is something missing.

My proposal is:
 * don't use git merge
 * start a new branch from current upstream
 *  cherry-pick commit by commit into new branch

2022-01-18 18:34 UTC, darranl commented
TBH on this one the "Files Changed" tab is giving an accurate view on this overall PR.

2022-01-18 19:04 UTC, ropalka approved these changes
Thanks @darranl for the hint how to approach this review. I was used to review PRs commit by commit and didn't use "Files Changed" till now. I am approving this PR. All test changes looks good.

2022-01-22 13:50 UTC, darranl commented
@bstansberry could you please take a look at this PR.

After removing the dependency on PicketBox I was getting ts.bootable test failures but looking more closely these were in some redundant legacy-security so I have removed those as no longer applicable.

2022-01-25 23:53 UTC, bstansberry commented on testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/formauth/SecureServlet.java
> +//        }
If you make other changes to this PR these lines can be deleted and the commit message changed to 'Remove unused verification dependent on Picketbox."

Both in main and in downstream there's no code that passes requrest parameter "validateSubject" so this is all cruft.

2022-01-26 01:57 UTC, bstansberry commented on testsuite/integration/web/src/test/java/org/jboss/as/test/integration/web/security/cert/WebSecurityCERTTestCase.java
> +@Ignore("[WFLY-15749] Update WebSecurityCERTTestCase to use Elytron SSLContext.")
I made this a Blocker.

2022-01-26 02:05 UTC, bstansberry requested changes
@darranl I made a minor change request, to help the GetCallerPrincipalTestCaseclass be more understandable in the future.  Ignoring another test isn't great but it's ok.

2022-01-26 02:05 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/callerprincipal/GetCallerPrincipalTestCase.java
> +        callable.call();
Unless I'm missing something the callable should just be removed and its code inlined.

2022-01-26 02:05 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/security/callerprincipal/GetCallerPrincipalTestCase.java
> +            callable.call();
Unless I'm missing something the callable should just be removed and its code inlined.

2022-01-26 14:35 UTC, darranl commented
@bstansberry I have just pushed again with the requested changes.

2022-01-26 16:41 UTC, bstansberry approved these changes

2022-01-26 22:21 UTC, merged