[WFLY-16137] - update elytron docs for WFCORE-4314
wildfly/wildfly pull request #15309
Opened 2022-03-10 09:06 UTC by baranowb

Issue: https://issues.redhat.com/browse/WFLY-16137
Related: https://issues.redhat.com/browse/WFCORE-4314

2022-03-10 20:00 UTC, fjuma requested changes
Thanks for the PR @baranowb!

I've added some small comments.

In the commit message and PR title/description, please reference this WFLY issue instead of the WFCORE issue:

https://issues.redhat.com/browse/WFLY-16137

Thanks!

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +==== List all aliases(recursively) in a key store.
Minor nit but would be good to have a space before (recursively).

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +==== List all aliases(recursively, no keys) in a key store.
Again, would be good to have a space before the opening bracket.

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +==== List all aliases(recursively, no keys) in a key store.
Might be good to reword this to (recursively, non-verbose)

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +==== Read alias in a key store.
s/Read alias/Read an alias

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +/subsystem=elytron/credential-store=exampleCS:read-alias(name="localhost")
s/credential-store=exampleCS/key-store=httpsKS

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +==== Read alias in a key store(non verbose).
s/Read alias in a key store/Read an alias in a key store (non-verbose)

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +/subsystem=elytron/credential-store=exampleCS:read-alias(name="localhost",verbose=false)
s/credential-store=exampleCS/key-store=httpsKS

2022-03-10 20:00 UTC, fjuma commented on docs/src/main/asciidoc/_elytron/Using_the_Elytron_Subsystem.adoc
> +/subsystem=elytron/credential-store=exampleCS:read-aliases(recursive=true, verbose=false)
s/credential-store=exampleCS/key-store=httpsKS

2022-03-14 14:26 UTC, fjuma approved these changes
Thanks @baranowb!

2022-03-22 21:58 UTC, merged

2022-03-22 21:59 UTC, bstansberry commented
Thanks, @baranowb 

I went ahead and merged this before the 19.0.0.Beta6 upgrade, as I know this will be in it and I wanted to merge the 26.x variant for this week's 26.1 beta.