[WFLY-16129] [allowlist/blocklist] Problematic Language usage depreca…
wildfly/wildfly pull request #15326
Opened 2022-03-16 06:38 UTC by moulalis

Issue: https://issues.redhat.com/browse/WFLY-16129

2022-03-16 08:14 UTC, darranl commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_JWT.adoc
> +|smallrye.jwt.blocklist.algorithms
@moulalis Has the JWT code actually changed?

2022-03-18 13:07 UTC, darranl requested changes
We need to verify what properties SmallRye JWT is using.

2022-03-21 13:11 UTC, moulalis commented
> smallrye.jwt.whitelist.algorithms

@darranl As per https://github.com/smallrye/smallrye-jwt/blob/3.1.1/doc/modules/ROOT/pages/configuration.adoc, it doesn't mention any "whitelist" property, instead they have smallrye.jwt.verify.algorithm.  The whitelist prop is removed https://github.com/smallrye/smallrye-jwt/commit/77eab5054915342b8ee9e121c5a7e4a7b94f74e1 here.

2022-04-28 21:14 UTC, bstansberry commented
@moulalis @darranl I recommend that this 'smallrye.jwt.blocklist.algorithms' entry in the table be deleted and we file a separate JIRA to sync this doc page with the current set of smallrye config properties, as there are a number of differences, plus some of the smallrye-specific ones are documented as deprecated with an mp.* one recommended. That work is unrelated to problematic language though.

The string 'whitelist' does not appear in the smallrye-jwt 3.1.1 source, so it seems pretty clear the entry in the docs table here is invalid.

2022-05-17 11:44 UTC, yersan commented
Hi, @moulalis would you mind following Brian's recommendation and deleting the entry from the doc?

Just for the record, I've just created this Jira to track the documentation changes for JWT: https://issues.redhat.com/browse/WFLY-16382

2022-05-17 13:04 UTC, moulalis commented
> Hi, @moulalis would you mind following Brian's recommendation and deleting the entry from the doc?
> 
> Just for the record, I've just created this Jira to track the documentation changes for JWT: https://issues.redhat.com/browse/WFLY-16382

PR Updated. Thanks.

2022-06-04 15:30 UTC, bstansberry approved these changes

2022-06-04 15:30 UTC, merged