[WFLY-13798]:Add a Galleon layer for embedded broker messaging.
wildfly/wildfly pull request #15413
Opened 2022-04-07 10:07 UTC by ehsavoie

* Adding the new layer `embedded-activemq`.
 * Adding a new feature group `embedded-activemq` to contain the
   configuration.

Jira: https://issues.redhat.com/browse/WFLY-13798
Proposal: https://github.com/wildfly/wildfly-proposals/pull/473

Supersedes https://github.com/wildfly/wildfly/pull/15277

2022-05-03 11:52 UTC, yersan requested changes

2022-05-03 11:52 UTC, yersan commented on ee-feature-pack/galleon-common/src/main/resources/feature_groups/embedded-activemq.xml
> +<feature-group-spec name="embedded-activemq" xmlns="urn:jboss:galleon:feature-group:1.0">
For ee-9 module, we are also generating a configuration that includes the embedded messaging broker. Together with this PR, you should also adjust the ee-9 module to reuse this feature group spec and avoid re-defining it there.

See: https://github.com/wildfly/wildfly/blob/8958a48418159da5b0e3fce03aeb9f211342f2b1/ee-9/galleon-content/src/main/resources/packages/docs.examples.configs/pm/wildfly/tasks.xml#L23-L26

2022-05-12 08:34 UTC, yersan approved these changes
LGTM

2022-06-20 15:43 UTC, jfdenise approved these changes

2022-06-20 17:04 UTC, ehsavoie commented
@bstansberry I've also added the remote naming part as we discussed on https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Remote.20naming.20layer.3F

2022-08-03 02:21 UTC, bstansberry reviewed
@ehsavoie This LGTM, but the ts/int/basic test of the layer is still using test-feature-pack and its remote-naming layer. I don't think that affects the results CI is showing, but we should clean that up. I did that in #15878, which is just this plus a cleanup commit.

2022-08-03 15:35 UTC, bstansberry approved these changes

2022-08-03 21:54 UTC, merged