[WFLY-14266] Add resource adapter subsystem dependencies based on cap…
wildfly/wildfly pull request #15422
Opened 2022-04-13 14:11 UTC by tadamski

…ability

2023-03-24 17:31 UTC, darranl submitted a review, later dismissed
@tadamski Is the correct Jira issue referenced?  This seems to be about adding some capability references but the referenced Jira issue it about adding new config?

This PR looks to have failed test runs associated.

You should have the permissions to be able to request some reviews of the changes so we can see if they can be merged without handling as an RFE.

2023-03-30 09:37 UTC, tadamski commented
@darranl I think the issue is correct. IIRC there was an error in appclient tests which tried to extract property from nonexistent subsystem. I proposed this fix https://github.com/wildfly/wildfly/pull/15418, but from the discussion it turned out that it would better to use capabilitie hence this PR.

I have rebased it and cannot reproduce the error neither on JDK17 nor JDK11.

2023-03-30 18:56 UTC, tadamski commented
now there is some other test failing but tbh I don't expect it to be related

2024-01-02 15:22 UTC, darranl commented on connector/src/main/java/org/jboss/as/connector/deployers/ra/Capabilities.java
> + */
Please update to the new license header and use the Apache licence.

e.g. https://github.com/wildfly/wildfly/blob/main/connector/src/main/java/org/jboss/as/connector/deployers/ra/RaDeploymentActivator.java#L1-L4

2024-01-02 15:23 UTC, darranl requested changes
Small licence change needed.

2024-01-02 15:24 UTC, darranl commented
@pferraro Would you be able to please help with a review of the capability handling here.

2024-01-02 18:40 UTC, pferraro commented
@darranl The logic in this PR looks sound to me (given my note below), however, the linked jira is a feature request, whereas, the proposed change here is clearly a bug fix.  Do we need a separate jira for this?
@tadamski N.B. Normally, your "org.wildfly.resource-adapters" would expose the value provided by the service installed via the resource-adapters subsystem add operation - however, that service does not sufficiently encapsulate its provided value, so we definitely do not want this exposed via a public contract.

2024-01-02 23:15 UTC, tadamski commented
This is a bug fix in an RFE that was already merged so I used WFLY jira. I can create bug specific one if necessary.

2024-01-03 00:00 UTC, pferraro commented
@tadamski I see. Since it looks like WFLY-14266 was merged several releases ago, I think a separate bug fix jira (targeting 31.0.0.Final) is warranted.

2024-01-03 10:48 UTC, tadamski commented
@pferraro I have created WFLY-18882 and opened https://github.com/wildfly/wildfly/pull/17512

2024-07-03 01:15 UTC, bstansberry commented
@tadamski Please rebase and change the commit message to WFLY-18882

2024-07-03 12:54 UTC, pferraro approved these changes

2024-07-03 13:05 UTC, tadamski commented
@bstansberry done

2024-07-03 15:44 UTC, tadamski commented on connector/src/main/java/org/jboss/as/connector/subsystems/resourceadapters/ResourceAdaptersRootResourceDefinition.java
> +    static final RuntimeCapability<Void> RESOURCE_ADAPTERS_SUBSYSTEM = RuntimeCapability.Builder.of(RESOURCE_ADAPTERS_SUBSYSTEM_CAPABILITY).build();
fixed

2024-07-03 15:44 UTC, tadamski commented
@bstansberry rebased but apparently this was fixed in other PR and after rebase it is just access and naming change

2024-08-21 01:18 UTC, bstansberry commented
Superseded by #17512

2024-08-21 01:18 UTC, closed without merging