[WFLY-16267] Upgrade bouncycastle to 1.71
wildfly/wildfly pull request #15429
Opened 2022-04-14 10:25 UTC by boris-unckel

Fixes https://issues.redhat.com/browse/WFLY-16267

2022-04-14 10:29 UTC, boris-unckel commented
The component upgrade of bouncycastle to 1.71 includes a maven coordinate change. Please find all the links in the Jira. This PR requires https://github.com/wildfly/wildfly-core/pull/5051 The discussion how to deal with it starts there.

2022-04-20 09:02 UTC, yersan requested changes

2022-04-20 09:21 UTC, boris-unckel commented on pom.xml
> +            </dependency>
@yersan Thanks for the feedback and explanation. I have changed it accordingly.

2022-04-22 09:17 UTC, yersan approved these changes
Looks good to me.

2022-04-27 14:06 UTC, jmesnil commented
@boris-unckel   This PR is superseded by #15484 where I cherry-picked your commit. Thanks!

2022-04-27 14:06 UTC, closed without merging