[WFLY-16089] Upgrade Weld version for EE8 (3.1.9)
wildfly/wildfly pull request #15490
Opened 2022-04-27 19:23 UTC by boris-unckel

Fixes https://issues.redhat.com/browse/WFLY-16089
A rare case where 26.x was patched first: https://github.com/wildfly/wildfly/commit/92d02eeaafc6212325e1055dfa41cc9b8a64a66c

2022-04-27 19:25 UTC, boris-unckel commented
@manovotn I only checked main before I created the duplicated Jira, sorry. I think now it's better with your original Jira and link to the commit. Could you review and approve, please?

2022-04-27 21:30 UTC, manovotn commented
@boris-unckel I didn't update `main` because as far as I know, this branch is targeting EE 10 so the version of WEEld for EE 8 doesn't really matter. Am I right @bstansberry?

2022-04-28 06:45 UTC, boris-unckel commented
@manovotn Looking forward to the published versions you're right. I'm looking at it with the chance to have the latest version of JavaSE 11 and JakartaEE 8 in great shape. In my company and project this might be the best bridge before we can achieve the Java-Package jakarta.* namespace. Therefor I'm working a lot to have WF26 and WF27 beeing patched before the big-bang "JakartaEE 10 goes main" happens.

2022-04-28 08:02 UTC, darranl requested changes
Thank you for the PR, I am just going to place on hold for now - I am just going to check with Brian but we are getting ready to work on the big changes to drop Jakarta EE 8 support from main (we already know there will be no future Jakarta EE 8 releases from main) so I think we are ready to stop accepting changes that affect EE 8 only on main.

2022-04-28 12:47 UTC, bstansberry commented
@boris-unckel @darranl @manovotn Since this passes CI and AFAIK doesn't interfere with anything I don't have any objection. I thought about doing it when we upgraded 26.x just due to the general upstream first policy we have, but I was lazy and got distracted.

2022-04-28 12:51 UTC, manovotn commented
Sure, it doesn't interfere.

> I thought about doing it when we upgraded 26.x just due to the general upstream first policy we have, but I was lazy and got distracted.

You can always blame it on my laziness that I only sent the PR for 26.x branch ;-)

2022-04-28 19:59 UTC, merged