[WFLY-16349] Upgrade to jakarta.* versions of MP reactive messaging
wildfly/wildfly pull request #15529
Opened 2022-05-05 09:53 UTC by kabir

https://issues.redhat.com/browse/WFLY-16349

2022-05-05 15:45 UTC, bstansberry commented
@kabir This will conceptually conflict with 2 open PRs:

https://github.com/wildfly/wildfly/pull/15515
https://github.com/wildfly/wildfly/pull/15528

The first one might need some work as it might be doing more dependencyMgmt stuff than is strictly necessary. But anyway we should align on how/where we manage these TCK versions.

The latter is partly about getting rid of use of jakarta.el:jakarta-el-api, which we won't use at runtime (we use a spec fork, which now has a release) so we shouldn't use it at compile or test time. So we shouldn't introduce another use of it here.

2022-05-06 17:08 UTC, bstansberry requested changes
@kabir 

I need to make some further tweaks to #15515 and I don't want this blocked by those. I've made comments below that will get this to the correct GAVs. When this is merged I'll adapt the #15515 stuff to account for this changeset.

2022-05-06 17:08 UTC, bstansberry commented on testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
> +                <version.jakarta.enterprise>4.0.0-RC2</version.jakarta.enterprise>
Please use 4.0.0 as it's what the production code uses.

2022-05-06 17:08 UTC, bstansberry commented on testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
> +                <version.jakarta.el.jakarta-el-api>5.0.0-RC1</version.jakarta.el.jakarta-el-api>
Please change this to 
```
<version.org.jboss.spec.jakarta.el.jboss-el-api_5.0_spec>4.0.0.Alpha1</version.org.jboss.spec.jakarta.el.jboss-el-api_5.0_spec>
```

2022-05-06 17:08 UTC, bstansberry commented on testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
> +            </dependencies>
Please change to

```


                    <dependency>
                        <groupId>org.jboss.spec.jakarta.el</groupId>
                        <artifactId>jboss-el-api_5.0_spec</artifactId>
                        <version>${version.org.jboss.spec.jakarta.el.jboss-el-api_5.0_spec}</version>
                        <exclusions>
                            <exclusion>
                                <groupId>*</groupId>
                                <artifactId>*</artifactId>
                            </exclusion>
                        </exclusions>
                    </dependency>
```

2022-05-06 17:08 UTC, bstansberry commented on testsuite/integration/microprofile-tck/reactive-messaging/pom.xml
> +                <version.jakarta.el.jakarta-el-api>5.0.0-RC1</version.jakarta.el.jakarta-el-api>
Same comments as above apply to this profile.

2022-05-09 10:05 UTC, kabir commented
@bstansberry I think it should be in order now. I tried to do this before finishing on Friday but that el-api dependency made it a bit more complicated than first thought.

2022-05-09 12:46 UTC, bstansberry approved these changes
Thanks @kabir 

On #15515 I'll deal with the CDI API exclude of the jakarta.el dep in a higher level pom.

2022-05-11 14:31 UTC, merged