[WFLY-15559]:Move WildFly Preview to a native Jakarta namespace varia…
wildfly/wildfly pull request #15648
Opened 2022-06-13 02:46 UTC by jimma

…nt of the webservices subsystem module

https://issues.redhat.com/browse/WFLY-15559

2022-06-13 12:30 UTC, bstansberry requested changes

2022-06-13 12:47 UTC, jimma commented on ee-9/pom.xml
> +            </dependency>
These dependencies added are for preview/jakarta versions. Will moving out these dependencies still work for WildFly Preview?

2022-06-14 00:46 UTC, bstansberry commented on ee-9/pom.xml
> +            </dependency>
Yes. The declarations you have here will be what WFP uses.

https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/thread/A2ULGAF2VGAONJ272L6N5I44QVVPSYLH/ describes how the various 'internal boms' work.  What you've done above is configure '5) An 'wildfly-preview' bom'. What I'm looking for is for the standard WildFly dependencies to be moved out of the 'common bom' (#2) and into the '3) An 'ee' bom for standard WildFly dependencies that get installed via the
wildfly-ee feature pack and that are not used in WFP'.

2022-06-14 03:45 UTC, jimma commented on ee-9/common/pom.xml
> +        </dependency>
Fixed.

2022-06-14 03:46 UTC, jimma commented on ee-9/pom.xml
> +            </dependency>
Thanks @bstansberry. I wrongly read to moving out dependencies from ee-9/pom.xml to ee-feature-pack/pom.xml.  
Already moving out these dependencies from root pom to ee-feature-pack  pom file.

2022-06-14 12:53 UTC, merged

2022-06-14 12:53 UTC, bstansberry commented
Thanks @jimma