[WFLY-10912] - CodecSessionConfig#findSessionId() causes an incorrect…
wildfly/wildfly pull request #15657
Opened 2022-06-15 05:25 UTC by adamecp

CodecSessionConfig#findSessionId() causes an incorrect JSESSIONID Set-Cookie header
JIra issue: [https://issues.redhat.com/browse/WFLY-10912](https://issues.redhat.com/browse/WFLY-10912)

2022-06-15 13:58 UTC, pferraro commented
@adamecp Did you intend to submit a fix for this issue as well?  I only see a test case reproducing the problem.

2022-06-15 16:22 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/response/CodecSessionConfigTestCase.java
> + * Copyright 2020, Red Hat Inc., and individual contributors as indicated
2022?

2022-06-15 16:26 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/web/response/CodecSessionConfigTestCase.java
> +            Assert.fail("The expected behavior is that WildFly/EAP 7 should respond without JSESSIONID Set-Cookie header. See https://issues.redhat.com/browse/WFLY-10912");
Please remove the "EAP 7" here and in the javadoc. Thanks!

2022-06-28 16:32 UTC, rhusar requested changes
For this pull request to be mergeable, the test would need to be commited as `@Ignored`.

2022-10-19 20:00 UTC, bstansberry commented
/retest

2022-10-28 01:37 UTC, bstansberry commented
/ok-to-test

2022-10-28 11:41 UTC, pferraro commented
We can close this - it was already addressed in full by https://github.com/wildfly/wildfly/pull/16019

2022-10-28 11:41 UTC, closed without merging