[WFLY-16428] LegacyCompliantPrincipalPropagationTestCase fails in Windows
wildfly/wildfly pull request #15705
Opened 2022-06-27 19:45 UTC by cam-rod

https://issues.redhat.com/browse/WFLY-16428

2022-06-27 20:31 UTC, fjuma requested changes
Thanks @cam-rod! I've just added a small comment.

It would also be good to update the WFLY issue description to explain why this fix was needed just to provide some context there.

2022-06-27 20:31 UTC, fjuma commented on testsuite/integration/manualmode/src/test/java/org/jboss/as/test/manualmode/weld/builtinBeans/LegacyCompliantPrincipalPropagationTestCase.java
>          ServerReload.reloadIfRequired(managementClient);
This reload can be removed too since we're no longer adding the `application-security-domain` resource.

2022-06-27 20:44 UTC, fjuma commented
/ok-to-test

2022-06-30 11:07 UTC, darranl approved these changes

2022-06-30 12:50 UTC, merged