[Big Bang] WFLY-7628 Distributed EJB timers
wildfly/wildfly pull request #15806
Opened 2022-07-18 19:00 UTC by darranl

This takes the following PR and resolves merge issues / migrates new test class to the jakarta.* namespace.
    https://github.com/wildfly/wildfly/pull/15053

2022-07-18 20:12 UTC, pferraro requested changes

2022-07-19 12:21 UTC, darranl commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ejb/timer/beans/AbstractTimerBean.java
>  import javax.annotation.Resource;
Thanks @pferraro - fixed

2022-07-19 12:24 UTC, pferraro approved these changes

2022-07-20 22:43 UTC, merged

2022-07-20 22:44 UTC, bstansberry commented
Thanks @darranl