[WFLY-16788] Move org.wildfly.security:wildfly-elytron-jaspi from tes…
wildfly/wildfly pull request #15914
Opened 2022-08-11 16:09 UTC by yersan

…tsuite/integration to the legacy modules

Jira issue: https://issues.redhat.com/browse/WFLY-16788

2022-08-11 18:05 UTC, bstansberry requested changes
@yersan Looks like all that's needed is removal of the dep from testsuite/integration/pom.xml; the child modules don't need it.

Except... I think it can be removed from boms/legacy-ee as well, since the only use of it is in testsuite/integration/pom.xml.

2022-08-11 18:05 UTC, bstansberry commented on testsuite/integration/legacy-ejb-client/pom.xml
> +        </dependency>
Please remove. My testing verifies this dep is not needed.

2022-08-11 18:05 UTC, bstansberry commented on testsuite/integration/legacy/pom.xml
> +        </dependency>
Please remove. My testing verifies this dep is not needed.

2022-08-16 08:40 UTC, yersan commented
Thanks for the review @bstansberry , I've removed both dependencies

2022-08-16 14:27 UTC, bstansberry approved these changes

2022-08-16 17:05 UTC, merged

2022-08-16 17:05 UTC, bstansberry commented
Thanks @yersan