[WFLY-16238] Don't export traces by default
wildfly/wildfly pull request #16082
Opened 2022-09-19 20:31 UTC by jasondlee

https://issues.redhat.com/browse/WFLY-16238

If no sender endpoint is configure, configure a no-op sender

2022-09-19 20:41 UTC, bstansberry commented on microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingExtensionLogger.java
> +    @Message(id = 12, value="No Jaeger endpoint configured. Installing a no-op sender")
Perhaps INFO? Or is this something that logs more than once?

2022-09-19 20:56 UTC, bstansberry requested changes

2022-09-19 20:56 UTC, bstansberry commented on microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/spi/sender/WildFlySenderFactory.java
> +        if (configuration.getEndpoint() == null) {
You need to check configuration.getAgentHost() and configuration.getAgentPort() as well. ThriftSenderFactory uses those to create a UdpSender is there is no endpoint is configured. Those are configured via the sender-binding attribute in the subsystem model.

Tangent: SENDER_BINDING should not allow expressions. It's a capability reference and those shouldn't allow expressions.

2022-09-19 20:56 UTC, bstansberry commented on microprofile/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/TracingExtensionLogger.java
> +    @Message(id = 12, value="No Jaeger endpoint configured. Installing a no-op sender")
s/endpoint/endpoint or sender-binding/g

2022-09-20 18:53 UTC, jasondlee commented
> **Dependency Tree Analyzer Output:**
> 
> New Dependencies:
> 
>     * org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.7.10:compile
> 
>     * org.jetbrains.kotlin:kotlin-stdlib:jar:1.7.10:compile
> 
> 
> Major Version Changes:
> 
>     * com.squareup.okio:okio:jar:1.17.5:compile -> 2.8.0
> 
> 
> CC @wildfly/prod

These changes have been moved to #[16089](https://github.com/wildfly/wildfly/pull/16089)

2022-09-20 18:58 UTC, bstansberry approved these changes

2022-09-20 22:22 UTC, jasondlee commented
/retest

2022-09-21 16:31 UTC, merged