WFLY-17056 Update JPA subsystem doc for Hibernate 6
wildfly/wildfly pull request #16121
Opened 2022-09-28 14:56 UTC by scottmarlow

Signed-off-by: Scott Marlow <smarlow@redhat.com>
https://issues.redhat.com/browse/WFLY-17056

2022-10-04 19:41 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Jakarta_Persistence_Reference_Guide.adoc
> +|hibernate.id.new_generator_mappings can no longer be set to false by applications as per Hibernate 6 change to only support hibernate.id.new_generator_mappings=true.
This is not a 2 cell table row any more.

Also, 
s/per Hibernate 6/per the Hibernate 6/g

2022-10-04 19:42 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Jakarta_Persistence_Reference_Guide.adoc
> +|hibernate.id.new_generator_mappings can no longer be set to false by applications as per Hibernate 6 change to only support hibernate.id.new_generator_mappings=true.
Also, 'can' should be 'Can' -- capitalize the first word in the 'Purpose' cell.

2022-10-04 19:42 UTC, bstansberry commented on docs/src/main/asciidoc/_developer-guide/Jakarta_Persistence_Reference_Guide.adoc
> +|hibernate.jpa.compliance=true | sets all of the various hibernate.jpa.* properties to true (hibernate.jpa.compliance.transaction, hibernate.jpa.compliance.closed,hibernate.jpa.compliance.query, hibe
s/sets/Sets

2022-10-04 19:43 UTC, bstansberry requested changes
See previous comments for requested changes.

2022-10-04 20:11 UTC, scottmarlow commented
> See previous comments for requested changes.

Requested changes pushed, thanks!

2022-10-05 20:51 UTC, merged

2022-10-05 20:51 UTC, bstansberry commented
Thanks @scottmarlow