[WFLY-17070] Drop source transformation for the Agroal subsystem
wildfly/wildfly pull request #16173
Opened 2022-10-14 09:49 UTC by yersan

Jira issue: https://issues.redhat.com/browse/WFLY-17070

2022-10-14 19:15 UTC, bstansberry requested changes
Thanks @yersan 

Please handle this TODO:

https://github.com/wildfly/wildfly/blob/main/pom.xml#L1988-L1989

Bonus points for fixing mail and jaxrs that have already been migrated where I forgot to ask for this in code review.

2022-10-17 09:30 UTC, yersan commented
Good catch @bstansberry , thanks for reviewing it

2022-10-17 14:09 UTC, bstansberry approved these changes

2022-10-17 16:09 UTC, merged

2022-10-17 16:10 UTC, bstansberry commented
Thanks, @yersan