WFLY-17164 Remove AttributeDefinition.isAllowNull
wildfly/wildfly pull request #16181
Opened 2022-10-18 11:35 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFLY-17164

2022-10-21 12:16 UTC, pferraro requested changes

2022-10-21 12:16 UTC, pferraro commented on clustering/common/src/main/java/org/jboss/as/clustering/controller/PropertiesAttributeDefinition.java
> +                this.elementValidator = new ModelTypeValidator(ModelType.STRING, this.isNillable(), this.isAllowExpression());
isNillable() is not a method of MapAttributeDefinition.Builder.

2022-10-21 12:16 UTC, pferraro commented on clustering/common/src/main/java/org/jboss/as/clustering/controller/validation/AbstractParameterValidatorBuilder.java
> +        this.allowsUndefined = builder.isNillable();
isNillable() is not a method of AbstractAttributeDefinitionBuilder.

2022-11-08 12:42 UTC, yersan commented
Hi @parsharma , for your information,  we have already released the WildFly Core version required to complete this PR.

2022-11-11 14:51 UTC, pferraro commented on clustering/common/src/main/java/org/jboss/as/clustering/controller/PropertiesAttributeDefinition.java
> +                this.elementValidator = new ModelTypeValidator(ModelType.STRING, this.isNillable(), this.isAllowExpression());
OK - this compiles now.  I did not realize that this PR was dependent on a future wildfly-core release.

2022-11-11 14:54 UTC, pferraro commented
@parsharma I think you are going to need to rebase your branch in order to get the gihub actions to pass (unlike the CI jobs, these are run directly on your branch).

2022-11-13 19:16 UTC, bstansberry commented
/retest

2022-11-15 06:58 UTC, parsharma commented
Thanks for letting me know and I am sorry I was on sick leave last week so won't be able to rebase the branch.

2022-11-15 14:22 UTC, pferraro approved these changes

2022-11-15 15:33 UTC, merged

2022-11-15 15:33 UTC, pferraro commented
Thanks @parsharma !