[WFLY-17281]:Set release version to maven compiler plugin
wildfly/wildfly pull request #16269
Opened 2022-11-09 03:48 UTC by jimma

https://issues.redhat.com/browse/WFLY-17281

2022-11-10 15:39 UTC, jamezp requested changes

2022-11-10 15:39 UTC, jamezp commented on pom.xml
> -        <maven.compiler.source>11</maven.compiler.source>
I think we need to keep these. While they'll be ignored if `<release/>` is used, but we don't explicitly set that on the `maven-compiler-plugin`. However, we do explicitly set the `<target/>` and `<source/>` settings. By default too the `jdk.min.version` is set to `maven.compiler.argument.source` which is set from `maven.compiler.source`.

2023-01-30 22:39 UTC, bstansberry commented
@jamezp @jimma Is this a case of needing to restore the removed lines, PLUS add the new line in the PR? Or should this just be closed?

Either way, lets get it out of the PR queue. :)

2023-01-31 21:37 UTC, jamezp commented
I think we should do it, but I also think we should keep the other properties. I created #16503 as a replacement.

2023-01-31 21:37 UTC, closed without merging