WFLY-8718: remove xa-datasource-class from JDBC driver definition
wildfly/wildfly pull request #16271
Opened 2022-11-09 19:52 UTC by michpetrov

Issue: [WFLY-8718](https://issues.redhat.com/browse/WFLY-8718)

The attribute definition itself was kept in since it used in xa-datasource but it shouldn't be included in the definition of a driver (which already has DRIVER_XA_DATASOURCE_CLASS_NAME). This has no impact on schema definition.

2023-04-05 10:37 UTC, tadamski requested changes
@michpetrov could you please also deprecate the related attribute so that we can remove it ultimately?

2023-04-06 12:51 UTC, michpetrov commented
@tadamski which one do you want to deprecate? The one I removed is still used in XaDataSourceDefinition where I assume it is necessary, it was just wrongly included in the driver definition.

2023-04-08 09:02 UTC, tadamski commented
@michpetrov true, my mistake, approving

2023-04-08 09:02 UTC, tadamski approved these changes

2023-05-25 15:19 UTC, merged