[WFLY-17487] Remove usage of legacy InitialContextFactory from integr…
wildfly/wildfly pull request #16447
Opened 2023-01-09 22:05 UTC by tadamski

…ation tests

https://issues.redhat.com/browse/WFLY-17487

2023-01-10 22:01 UTC, chengfang approved these changes

2023-01-18 11:18 UTC, ropalka requested changes
Also documentation should be updated, I see 4 references of _org.wildfly.naming.client.WildFlyInitialContextFactory_ in docs/ folder.

2023-01-24 22:24 UTC, tadamski commented
> Also documentation should be updated, I see 4 references of _org.wildfly.naming.client.WildFlyInitialContextFactory_ in docs/ folder.

fixed

2023-01-25 11:26 UTC, ropalka approved these changes

2023-01-30 21:40 UTC, merged

2023-01-30 21:41 UTC, bstansberry commented
Thanks @tadamski, @chengfang and @ropalka