[WFLY-17357] [git branches] Fix problematic language usage in branches
wildfly/wildfly pull request #16522
Opened 2023-02-09 15:45 UTC by petrberan

https://issues.redhat.com/browse/WFLY-17357

2023-02-09 15:47 UTC, petrberan commented
There are still some "master" branches left, those still use the word "master" instead of "main" or any other variant. Few links were removed due to the fact that said link doesn't work anymore and has no alternative (helloworld-rs for example)

2023-02-23 12:25 UTC, yersan requested changes
thanks, @petrberan. I've added some very minor comments that would be great if are done together with this change.

I've also checked you left this one:

src/main/asciidoc/_developer-guide/ejb3/Jakarta_Enterprise_Beans_over_HTTP.adoc:https://github.com/wildfly/wildfly-http-client/blob/master/docs/src/main/asciidoc/wire-spec-v1.asciidoc

It can use `main` branch instead of `master`

2023-02-23 12:25 UTC, yersan commented on docs/src/main/asciidoc/_developer-guide/Class_Loading_in_WildFly.adoc
> +https://github.com/wildfly/wildfly-core/blob/main/server/src/main/resources/schema/jboss-deployment-structure-1_2.xsd[https://github.com/wildfly/wildfly-core/blob/main/server/src/main/resources/schem
You can just use the latest one which is: [jboss-deployment-structure-1_3.xsd](https://github.com/wildfly/wildfly-core/blob/main/server/src/main/resources/schema/jboss-deployment-structure-1_3.xsd)

In addition, Can you replace the `[https://github.com/wildfly/wildfly-core/blob/main/server/src/main/resources/schema/jboss-deployment-structure-1_2.xsd]` by `[jboss-deployment-structure-1_2.xsd]` ?

2023-02-23 12:25 UTC, yersan commented on docs/src/main/asciidoc/_testsuite/WildFly_Testsuite_Harness_Developer_Guide.adoc
> +https://github.com/jboss/jboss-parent-pom/blob/main/pom.xml#L65 .
Again, remove the line number and describe the paragraph a bit differently so the user can understand what the links provide, for example, The plugin version needs to be specified in jboss-parent at the `<properties>` section of the jboss-parent pom.xml file

2023-02-27 16:48 UTC, petrberan commented
Thanks for looking into this @yersan , I've made the requested changes and managed to find one more problem to fix.

Can you please take a look at changes in Micrometer.adoc as I'm not sure if the code is fine now.

2023-02-28 02:13 UTC, bstansberry approved these changes

2023-02-28 02:13 UTC, merged

2023-02-28 02:13 UTC, bstansberry commented
Thanks @petrberan