[WFLY-14587] JCA subsystem: throw parsing exception if name for workm…
wildfly/wildfly pull request #16536
Opened 2023-02-15 14:36 UTC by tadamski

…anager pools is configured

https://issues.redhat.com/browse/WFLY-14587

I believe this is not a model change but a bug fix. The name was never a part of a model was a side effect of delegating parsing to jboss-threads. Otoh, I think that current naming in which thread pool matches workmanager name is pretty clean and I would vote for not changing it.

@ehsavoie FYI

2023-02-15 16:54 UTC, rhusar requested changes
The change makes `org.jboss.as.test.integration.jca.workmanager.WorkManagerThreadsCheckTestCase` fail.

2023-02-16 13:14 UTC, tadamski commented
@rhusar  fixed (I have reverted log removal as it is necessary with CLI usage)

2023-03-17 16:25 UTC, bstansberry approved these changes
Nice. I agree this is just a parsing bug fix. Most, maybe all, of our parsers, including this one, fail if they find unexpected attributes or elements; this is just adding a missing check for that.

2023-03-17 20:06 UTC, bstansberry commented
Having [long|short]-running-thread-pool be resources instead of ObjectTypeAttributeDefinition attributes is the fundamental flaw here; that's why these things have names. But the effort to correct that would be pretty high, even ignoring the backward compatibility code that would be needed. Between this and [WFLY-14579](https://issues.redhat.com/browse/WFLY-14579) we have reasonable behavior.

2023-03-17 20:06 UTC, merged

2023-03-17 20:06 UTC, bstansberry commented
Thanks @tadamski and @rhusar