[WFLY-17640]: Messaging ActiveMQ server cannot be created in management model because it requires dependency on legacy security domain.
wildfly/wildfly pull request #16538
Opened 2023-02-15 17:30 UTC by ehsavoie

* We no longer need to depend on a legacy security capability.
* Updating error message to be more explicit about what is required.

Jira: https://issues.redhat.com/browse/WFLY-17640

2023-02-16 02:01 UTC, bstansberry requested changes
We still need the capability check in a Host Controller.

Perhaps:

1) Remove the default value from SECURITY_DOMAIN.
2) Add a setCapabilityReference call to SECURITY_DOMAIN.

Basically in domain.xml you no longer get to skip setting security-domain=other for your profile that manages a legacy HC.

I don't know if security-enabled=true without setting either elytron-domain or security-domain is a valid config. It seems the WildFlySecurityManager is meant to allow it in certain conditions.  If it's not valid, SecurityDomainCheckHandler can just enforce that one or the other is set. Otherwise delete it.

2023-02-21 14:26 UTC, ehsavoie commented
If i remove the default value that would break existing behaviour in legacy servers right ?
I'm not sureI fully understand the issue: on a WildFly 28 hte user would be suing either elytron or disable security. On a legacy HC the control would still be in place.

2023-02-21 16:49 UTC, bstansberry commented
> On a legacy HC the control would still be in place.

The capability verification needs to happen on the DC and not rely on a secondary HC enforcing it, which might not happen until some point long in the future when that HC connects.

Yes, it would break legacy configs; they would need to explicitly configure this value and not rely upon the default. This would be something the server migration tool would need to handle (i.e. if security enabled and elytron-domain not set, set security-domain to 'other'. @emmartins FYI.

2023-04-06 19:47 UTC, bstansberry approved these changes

2023-04-06 19:48 UTC, bstansberry commented
@ehsavoie FYI looking at the class you changed led me to file https://issues.redhat.com/browse/WFLY-17860

2023-04-06 22:22 UTC, merged

2023-04-06 22:22 UTC, bstansberry commented
Thanks @ehsavoie

2023-06-23 09:02 UTC, mchoma commented on messaging-activemq/injection/src/main/java/org/wildfly/extension/messaging/activemq/logging/MessagingLogger.java
> +    @Message(id = 107, value = "You must define a elytron security doman when security is enabled.")
doman -> domain