[(nobranch,rebasingWFLY-17743)]:  [WFLY-17743]: Refactor embedded-act…
wildfly/wildfly pull request #16625
Opened 2023-03-15 17:55 UTC by ehsavoie

…ivemq and remote-activemq Galleon layers.

 * embedded-activemq layer now depends on messaging-activemq layer instead of resource-adapters.
 * remote-activemq layer now depends on messaging-activemq layer instead of resource-adapters.

Jira: https://issues.redhat.com/browse/WFLY-17743

2023-03-16 20:47 UTC, bstansberry requested changes
@ehsavoie Please include an update to https://github.com/wildfly/wildfly/blob/main/docs/src/main/asciidoc/_galleon/Galleon_layers.adoc

2023-03-17 16:21 UTC, ehsavoie commented
@bstansberry done

2023-03-17 21:14 UTC, bstansberry approved these changes

2023-03-18 21:47 UTC, merged

2023-03-18 21:47 UTC, bstansberry commented
Thanks @ehsavoie