[WFLY-13397] Add the MP config module dependency to the MP REST clien…
wildfly/wildfly pull request #16620
Opened 2023-03-14 00:29 UTC by jamezp

…t module.

[WFLY-17695] Add a test to ensure the headers are propagated.

https://issues.redhat.com/browse/WFLY-13397
https://issues.redhat.com/browse/WFLY-17695

2023-03-14 13:38 UTC, rhusar requested changes
The added test case fails under security manager:

```
&amp#27;&amp#27;01:21:00,705 ERROR [org.jboss.resteasy.core.providerfactory.DefaultExceptionMapper] (default task-1) RESTEASY002375: Error processing request GET /HeaderPropagationTestCase/api/client - org.wildfly.test.integration.microprofile.restclient.ClientResource.invokeTestClient: java.security.AccessControlException: WFSM000001: Permission check failed (permission "("java.io.FilePermission" "/opt/buildAgent/system/jetbrains.maven.runner/maven.repo.local-bt857/org/jboss/resteasy/microprofile/microprofile-rest-client-base/2.1.0.Final/microprofile-rest-client-base-2.1.0.Final.jar" "read")" in code source "(vfs:/content/HeaderPropagationTestCase.war/WEB-INF/classes <no signer certificates>)" of "null")
```

2023-03-14 21:25 UTC, jamezp commented
This is going to require a new release of resteasy-microprofile. The fixes are in and I'm working on the release now.

2023-03-15 01:38 UTC, bstansberry approved these changes

2023-03-17 02:09 UTC, merged

2023-03-17 02:09 UTC, bstansberry commented
Thanks @jamezp