Fixes for WFLY-17808, WFLY-17820, WFLY-17821, Licenses generation doesn't take into account versions resolved from Channels
wildfly/wildfly pull request #16682
Opened 2023-03-31 08:36 UTC by jfdenise

The fix for https://issues.redhat.com/browse/WFLY-17808 depends on Galleon and License plugins upgrades.
Issues:
* https://issues.redhat.com/browse/WFLY-17808
* https://issues.redhat.com/browse/WFLY-17820
* https://issues.redhat.com/browse/WFLY-17821

In addition, some cleanup has been done to filter-out not provisioned artifacts from the generated licenses files.

2023-04-03 22:01 UTC, bstansberry requested changes

2023-04-04 10:32 UTC, jfdenise commented on microprofile/galleon-common/src/main/resources/license/microprofile-feature-pack-licenses.xml
> -    </dependency>
@bstansberry , thank-you done.

2023-04-04 10:33 UTC, jfdenise commented on ee-feature-pack/galleon-feature-pack/pom.xml
> +                            <excludedArtifacts>jboss-transaction-api_1.3_spec|wildfly-standard-ee-bom|wildfly-legacy-ee-bom|wildfly-ee-feature-pack-galleon-shared|wildfly-ee-feature-pack-galleon-loca
@bstansberry , thank-you. I removed it from dependencies in a separate commit.

2023-04-04 12:30 UTC, bstansberry approved these changes

2023-04-04 21:34 UTC, merged

2023-04-04 21:34 UTC, bstansberry commented
Thanks @jfdenise