[WFLY-17869] Replace uses of ServiceName SocketBinding.JBOSS_BINDING_…
wildfly/wildfly pull request #16709
Opened 2023-04-07 03:56 UTC by soul2zimate

…NAME with use of the capability in Transaction subsystem

Issue: https://issues.redhat.com/browse/WFLY-17869

2023-04-07 14:34 UTC, tadamski approved these changes

2023-04-10 20:49 UTC, pferraro requested changes

2023-04-10 20:49 UTC, pferraro commented on transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
> +            socketBindingSupplier = builder.requires(socketBindingServiceName);
```java
socketBindingSupplier = builder.requiresCapability(SOCKET_BINDING_CAPABILITY_NAME, SocketBinding.class, socketBindingName);

2023-04-11 03:30 UTC, soul2zimate commented on transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
> +            socketBindingSupplier = builder.requires(socketBindingServiceName);
Fixed. Thanks.

2023-04-11 12:28 UTC, pferraro requested changes

2023-04-11 13:33 UTC, soul2zimate commented on transactions/src/main/java/org/jboss/as/txn/subsystem/TransactionSubsystemAdd.java
> +        Supplier<SocketBinding> socketBindingSupplier =  () -> null;
update.

2023-04-11 15:43 UTC, pferraro approved these changes

2023-04-12 12:23 UTC, merged