[WFLY-17860]: Convert ServerAdd.InstallServerHandler to CapabilityServiceTarget.
wildfly/wildfly pull request #16726
Opened 2023-04-11 17:39 UTC by ehsavoie

* Using the CapabilityServiceTarget API.

Jira: https://issues.redhat.com/browse/WFLY-17860

2023-04-11 18:23 UTC, bstansberry requested changes

2023-04-11 18:49 UTC, ehsavoie commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
> +                    RuntimeCapability.Builder.of(activeMQServiceName.getCanonicalName(), false, ActiveMQServer.class).build());
It wasn't working and I was getting missing service exceptions

2023-04-12 16:28 UTC, ehsavoie commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
> +                    RuntimeCapability.Builder.of(activeMQServiceName.getCanonicalName(), false, ActiveMQServer.class).build());
no i didn't

2023-04-12 19:44 UTC, bstansberry commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
> +                    RuntimeCapability.Builder.of(activeMQServiceName.getCanonicalName(), false, ActiveMQServer.class).build());
See also https://wildfly.zulipchat.com/#narrow/stream/210169-jboss-msc/topic/Undeprecate.20addAliases.3F

2023-04-13 19:32 UTC, bstansberry commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
> +class ActiveMQServerService implements Service<ActiveMQServer>, Supplier<ActiveMQServer> {
Why implement Supplier? I don't see any use.

2023-04-13 19:34 UTC, bstansberry commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ServerAdd.java
> +            Consumer<ActiveMQServer> consumer = serviceBuilder.provides(activeMQServiceName);
Pass ACTIVEMQ_SERVER_CAPABILITY to provides as well. That way the consumer is used for injection into dependents for both service names.

2023-04-13 19:36 UTC, bstansberry commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
> +class ActiveMQServerService implements Service<ActiveMQServer>, Supplier<ActiveMQServer> {
Also, change this to org.jboss.msc.Service and drop the getValue() method.

2023-04-13 19:44 UTC, bstansberry commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ActiveMQServerService.java
> +class ActiveMQServerService implements Service<ActiveMQServer>, Supplier<ActiveMQServer> {
Never mind this last part; I forgot about the ActiveMQActivationService.isActiveMQServerActive thing.

2023-04-14 16:32 UTC, bstansberry approved these changes

2023-04-14 21:13 UTC, merged

2023-04-14 21:13 UTC, bstansberry commented
Thanks @ehsavoie!