[WFLY-17908] Removing JDK 8 specific excludes from maven enforcer plugin configurations
wildfly/wildfly pull request #16747
Opened 2023-04-18 09:41 UTC by ropalka

https://issues.redhat.com/browse/WFLY-17908

2023-04-24 20:55 UTC, bstansberry approved these changes

2023-04-24 21:07 UTC, bstansberry requested changes
@ropalka I'm doubtful about removing the plugin config entirely from the various poms.

See https://github.com/wildfly/wildfly/pull/16747/files#diff-b2fea476e535fb7131e979d33a9af3d8a5084b5ea53a003e80c32bfcba29867cR417-R418

The feature pack maven module is not checking the modules it integrates for transitives; it counts on those modules doing it themselves. This change turns that off, so we're effectively not checking for transitives any more.

Perhaps the design could be rethought, but changing it is out of scope for WFLY-17908, which is just about the JDK 8 specifics.

2023-04-25 18:19 UTC, ropalka commented
Fixed @bstansberry - thanks for identifying this issue!

2023-04-26 00:27 UTC, bstansberry approved these changes

2023-04-26 04:31 UTC, merged

2023-04-26 04:31 UTC, bstansberry commented
Thanks @ropalka