[WFLY-17871] added test-case for managed executor service defined via…
wildfly/wildfly pull request #16775
Opened 2023-04-24 10:54 UTC by istudens

… annotation

This is a test-case for managed executor service defined via annotations. I can't see any such test in the test-suite.

Issue: https://issues.redhat.com/browse/WFLY-17871

2023-04-24 14:44 UTC, kabir commented
@istudens I see a failure in the new test case https://ci.wildfly.org/buildConfiguration/WF_PullRequest_GalleonLinuxJdk11/366184?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false&expandBuildChangesSection=true

2023-07-04 17:16 UTC, darranl commented
@emmartins it looks like this one is waiting for a review from you?

2023-07-11 21:02 UTC, bstansberry commented
/retest

2024-08-21 01:31 UTC, bstansberry requested changes
@istudens Formatting stuff aside, this is fine. If you see this and update the formatting stuff, please ping me in zulip so I know to check on it.

2024-08-21 01:31 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceAnnotationTestCase.java
> + */
Please update to the current copyright/license header.

2024-08-21 01:31 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceAnnotationBean.java
> + */
Please update to the current copyright/license header.

2024-08-21 01:31 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ee/concurrent/ManagedExecutorServiceAnnotationBean.java
> +import static jakarta.enterprise.concurrent.ContextServiceDefinition.SECURITY;
import static should come first, then import java, then the rest.

2024-08-21 12:37 UTC, istudens commented
@bstansberry done

2024-08-21 13:49 UTC, bstansberry approved these changes

2024-08-21 18:01 UTC, emmartins approved these changes

2024-08-22 00:38 UTC, merged

2024-08-22 00:39 UTC, bstansberry commented
Thanks @istudens