[WFLY-15324] Dynamically generating key/trust stores in Kafka SSL test
wildfly/wildfly pull request #16780
Opened 2023-04-25 13:37 UTC by khermano

Issue: https://issues.redhat.com/browse/WFLY-15324

2023-05-11 12:49 UTC, bstansberry requested changes

2023-05-11 12:49 UTC, bstansberry commented on testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/RunKafkaWithSslSetupTask.java
@khermano Since we're creating the store files as part of the test execution now, please delete them in the tearDown method. Thanks!

2023-05-15 09:22 UTC, kabir approved these changes

2023-05-15 09:22 UTC, khermano commented on testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/messaging/kafka/ssl/RunKafkaWithSslSetupTask.java
Sorry about that. I changed that.

2023-05-18 14:00 UTC, merged