[WFLY-12019] HostRemove should not remove services unless allow-resource-service-restart=true is set
wildfly/wildfly pull request #16902
Opened 2023-06-05 06:18 UTC by gaol

Issue: https://issues.redhat.com/browse/WFLY-12019

This PR tries to replace #16894 as that has test failures, and creating a new PR based on that will be efficient.

The test failures in #16894 is inter tests related, means that some other tests lead to a server state not cleaned, it is not easy to locate that test, but trying to reload the server when trying to modify the server can solve the test failure issue.

2023-06-07 21:01 UTC, pferraro requested changes
The fix looks good to me, my only comments are about the test itself.

2023-06-08 07:50 UTC, gaol commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/web/UndertowVirtualServerRemovalTestCase.java
> +public class UndertowVirtualServerRemovalTestCase extends ContainerResourceMgmtTestBase {
Thanks @pferraro for looking at this.

The test is trying to add a new server/host with some children resources, and remove it again during the test, and check the status after server/host removal. I don't know that we can test this within the subsystem unit test, I need to learn more before updating the tests if desirable. :)

2023-06-08 12:30 UTC, pferraro commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/api/web/UndertowVirtualServerRemovalTestCase.java
> +public class UndertowVirtualServerRemovalTestCase extends ContainerResourceMgmtTestBase {
The KernelServices abstraction from the subsystem test framework has the ability to execute operations:
https://github.com/wildfly/wildfly-core/blob/main/subsystem-test/framework/src/main/java/org/jboss/as/subsystem/test/KernelServices.java#L44

2023-06-08 12:41 UTC, darranl requested changes
Is it possible to please have a more meaningful message for the test commit, five years in the future when someone comes along with git log or annotate to check the history of the test they end up with just a Jira ID they need to manually look up.

2023-06-11 16:50 UTC, pferraro commented on undertow/src/test/java/org/wildfly/extension/undertow/UndertowServerRemovalTestCase.java
> +        super(UndertowSubsystemSchema.VERSION_14_0);
Why not always use the current schema?
e.g. UndertowSubsystemSchema.CURRENT

2023-06-11 16:53 UTC, pferraro commented on undertow/src/test/java/org/wildfly/extension/undertow/UndertowServerRemovalTestCase.java
> +            mainServices = load("undertow-14.0.xml");
You can avoid hardcoding the version via:
this.load(this.getSubsystemXml());

2023-06-12 01:37 UTC, gaol commented
@pferraro thanks Paul, I updated the test to avoid hard coding.

2023-06-12 12:12 UTC, pferraro approved these changes
Nice work!

2023-06-13 19:16 UTC, merged