WFLY-18091 Upgrade Infinispan to 14.0.10.Final
wildfly/wildfly pull request #16912
Opened 2023-06-06 20:00 UTC by pferraro

https://issues.redhat.com/browse/WFLY-18091

N.B. This PR fixes indentation in the licences.xml for ee-feature-pack, as discussed here:
https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/Formatting.20of.20feature.20pack.20licencses.2Exml

2023-06-07 08:33 UTC, rhusar requested changes
Causes failures in org.jboss.as.test.clustering.cluster.jms.ClusteredMessagingTestCase#
testClusteredQueue and #testClusteredTopic

2023-06-09 10:59 UTC, darranl commented
Hi @rhusar is this one possible to get a review?

2023-06-09 13:14 UTC, rhusar approved these changes
LGTM

2023-06-09 14:46 UTC, pferraro commented on testsuite/integration/clustering/pom.xml
> +        </dependency>
Indeed. I'll fix this later.

2023-06-09 15:44 UTC, merged