WFLY-17309: Upgrade Apache Artemis to 2.28.0 @ehsavoie
wildfly/wildfly pull request #16941
Opened 2023-06-14 13:21 UTC by ehsavoie

Jira: 
https://issues.redhat.com/browse/WFLY-17309
https://issues.redhat.com/browse/WFLY-17700

https://activemq.apache.org/components/artemis/download/release-notes-2.28.0
https://activemq.apache.org/components/artemis/download/release-notes-2.27.0
https://activemq.apache.org/components/artemis/download/release-notes-2.26.0

2023-06-21 00:18 UTC, bstansberry reviewed
@ehsavoie Why is it necessary to add getClassLoader perms to so many tests?

2023-06-21 05:35 UTC, ehsavoie commented
@bstansberry because of the change in the logging in Artemis from jboss-logging to slf4j

2023-06-21 14:51 UTC, bstansberry requested changes
We'll need to hold off on this until we have an Artemis release that doesn't have a security manager regression.

2023-08-09 12:27 UTC, ehsavoie commented
@bstansberry 2.30.0 fixes the security manager issue. We can proceed

2023-08-09 18:23 UTC, bstansberry commented on pom.xml
> +>>>>>>> 91b9b22837 ([WFLY-17309]: Upgrade Apache Artemis to 2.30.0)
@ehsavoie oops!

2023-09-12 16:07 UTC, ehsavoie commented
I'll wait for Artemis 2.31

2023-09-12 16:07 UTC, closed without merging