WFLY-18128: correct declared licenses
wildfly/wildfly pull request #16944
Opened 2023-06-15 14:32 UTC by michpetrov

Issue: [WFLY-18128](https://issues.redhat.com/browse/WFLY-18128)

The "big" change here is replacing "the antlr x.y.z license" with the standard BSD-3-Clause, as that seems to be what [they're actually using](https://www.antlr.org/license.html). If anyone knows of a reason to include the special license I'll put it back.

Also, I've removed the `org.reactivestreams:reactive-streams` from the "galleon-pack/galleon-shared" package (the github diff obfuscates it a little), since it is already defined in "ee-feature-pack/galleon-shared". That's the only removal of an entire artifact record.

2023-06-19 12:18 UTC, yersan commented
@michpetrov FYI, this got a conflict, could you rebase it?

2023-06-19 13:36 UTC, yersan requested changes
@michpetrov How we are verifying each of these changes? 

There are several artifacts with license changes, so I wondering how we are getting this license information

2023-06-20 12:49 UTC, michpetrov commented
@yersan I've ran the build without using the license file config (that way the plugin is pulling the licenses from POMs) and compared the output to the normal build. I have a script for comparing the files if you want to see it.

2023-06-20 14:10 UTC, yersan commented
@michpetrov Ok, I'm commenting on it because it seems is not always getting the expected result; I haven't checked every license but it seems that the one for Jakarta JPA is incorrect, could you take a look by doing another round? Thanks!

2023-06-20 14:59 UTC, michpetrov commented on ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml
> +                    <url>http://repository.jboss.org/licenses/gpl-2.0-ce.txt</url>
My bad, it's the resource-api, not persistence-api, that that's under EPL/GPL - https://projects.eclipse.org/projects/ee4j.jca

2023-06-20 15:00 UTC, michpetrov commented
@yersan rebased

2023-06-20 15:12 UTC, michpetrov commented
actually let me check it again, I think I skipped something

2023-06-20 15:28 UTC, michpetrov commented
@yersan should be ok now

2023-06-21 11:06 UTC, yersan requested changes
@michpetrov These additional two look wrong, could you check them?

* jakarta.resource:jakarta.resource https://github.com/wildfly/wildfly/blob/81b92ecdc3a04e7844739147a34b5f590d67927d/ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml#L949-L964
See: https://projects.eclipse.org/projects/ee4j.jca

* org.jboss.hal:hal-console https://github.com/wildfly/wildfly/blob/81b92ecdc3a04e7844739147a34b5f590d67927d/ee-feature-pack/galleon-shared/src/main/resources/license/licenses.xml#L3906-L3921
See: https://github.com/hal/console/blob/main/LICENSE

2023-06-21 11:18 UTC, yersan approved these changes
Giving my approval, with the pending detail about confirming removing MIT license from HAL. 
The other points about antlr and reactive, look correct to me too.

2023-06-21 13:01 UTC, hpehl commented
@yersan, yes, we can remove the MIT license from HAL.

2023-06-22 11:39 UTC, michpetrov commented
@yersan rebased

2023-06-22 19:39 UTC, merged

2023-06-22 19:39 UTC, bstansberry commented
Thanks @michpetrov and @yersan