WFLY-18227 Upgrade to Hibernate Search 6.2.0.Final
wildfly/wildfly pull request #17006
Opened 2023-07-07 14:28 UTC by yrodiere

https://issues.redhat.com/browse/WFLY-18227

Unfortunately I wasn't able to have WildFly default to Lucene 9 format for indexes; Hibernate Search's configuration is too dynamic to allow that reliably (see https://hibernate.atlassian.net/browse/HSEARCH-4897). We will have to handle that later.

It's still worth upgrading to 6.2 in WildFly, though. Be it just for the new [features](https://hibernate.org/search/releases/6.2/#whats-new).

2023-07-07 16:10 UTC, scottmarlow approved these changes

2023-07-07 16:17 UTC, scottmarlow commented
Copying from [WFLY-18227](https://issues.redhat.com/browse/WFLY-18227):
```
Changes since 6.2.0.CR1: https://hibernate.atlassian.net/issues/?jql=project=10061+AND+fixVersion=32168
See also https://hibernate.org/search/releases/6.2/
Migration guide from 6.1: https://docs.jboss.org/hibernate/search/6.2/migration/html_single/
```

@yrodiere I see that one of the changes is upgrading to use `Avro 1.11.2` but WildFly currently contains `avro-1.11.0.jar` (as module name=`org.apache.avro`) but I am not sure that is used by the Hibernate Search module in WildFly?

2023-07-07 16:21 UTC, scottmarlow commented
Hibernate Search in WildFly does have a module dependency on lasticsearch-rest-client-7.16.3.jar, should WildFly upgrade to `Elasticsearch 8.8.2` as part of this pull request?

2023-07-07 16:22 UTC, yrodiere commented
Ouch. You are right. Fortunately those are private modules. I'll create tickets and add that to the PR.

2023-07-07 16:28 UTC, yrodiere commented
Done. Thanks for catching that @scottmarlow!

2023-07-07 17:49 UTC, scottmarlow approved these changes

2023-07-07 17:49 UTC, scottmarlow commented
> Done. Thanks for catching that @scottmarlow!

Thank you for the quick update!

2023-07-07 17:56 UTC, scottmarlow requested changes
@yrodiere which Hibernate Search module needs access to the Avro classes?  

Can you confirm that applications using Hibernate Search do not need direct access to the Avro classes as far as you understand?

2023-07-07 18:25 UTC, yrodiere commented
> @yrodiere which Hibernate Search module needs access to the Avro classes?
> 
> Can you confirm that applications using Hibernate Search do not need direct access to the Avro classes as far as you understand?

They do not. Nothing changed in this area.

2023-07-07 19:27 UTC, scottmarlow commented
> > @yrodiere which Hibernate Search module needs access to the Avro classes?

wildfly/preview/galleon-local/src/main/resources/modules/system/layers/base/org/hibernate/search/mapper/orm/coordination/outboxpolling/main/module.xml seems to reference Avro classes in the org.hibernate.search.mapper.orm.coordination.outboxpolling module.  

Note that file wildfly/testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java also mentions Avro with a comment:
```
// Used by outboxpolling TODO this doesn't seem right
                    "org.apache.avro"
```

The HibernateSearchProcessor does reference the `org.hibernate.search.mapper.orm.coordination.outboxpolling` so it does seem like the Avro classes are indeed referenced.

> > Can you confirm that applications using Hibernate Search do not need direct access to the Avro classes as far as you understand?
> 
> They do not. Nothing changed in this area.

Got it, thanks!

2023-07-07 21:10 UTC, yrodiere commented
> ```
> // Used by outboxpolling TODO this doesn't seem right
>                     "org.apache.avro"
> ```
> 
> 
>     
>   
> 
> The HibernateSearchProcessor does reference the `org.hibernate.search.mapper.orm.coordination.outboxpolling` so it does seem like the Avro classes are indeed referenced.

I don't know where this comment comes from, but this dependency is completely expected. This module requires Avro for it's implementation. The API does not require Avro so it's not exposed to users.



> It looks like Hibernate Search has an optional dependency on the `org.hibernate.search.mapper.orm.coordination.outboxpolling`

Correct. It is not exposed to users however (this is what you asked previously).



> which I think only exists in the `WildFly Preview` build but is not in the `WildFly` build.

Correct. This technology is incubating.

> Should the Avro module also only exist in the `WildFly Preview` build since those are only used by the `org.hibernate.search.mapper.orm.coordination.outboxpolling` module?

Fine by me. Last I checked the Avro module was used by something else (I forgot what exactly), but if it's no longer the case... It can move out to preview as far as I'm concerned. It's internal anyway, isn't it?

I just hope this won't make it harder to move the outbox-polling module out of preview (which should happen eventually) :)

2023-07-10 15:08 UTC, scottmarlow commented
> I don't know where this comment comes from, but this dependency is completely expected.

https://github.com/wildfly/wildfly/blob/main/testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java contains that comment.  

>> Should the Avro module also only exist in the WildFly Preview build since those are only used by the org.hibernate.search.mapper.orm.coordination.outboxpolling module?

> Fine by me. Last I checked the Avro module was used by something else (I forgot what exactly), but if it's no longer the case... It can move out to preview as far as I'm concerned. It's internal anyway, isn't it?

I don't see any other references to the Avro module currently.

> I just hope this won't make it harder to move the outbox-polling module out of preview (which should happen eventually) :)

I defer to @bstansberry on whether Avro should also move to preview only.

2023-07-11 19:57 UTC, scottmarlow commented
org.wildfly.test.integration.microprofile.faulttolerance.micrometer.FaultToleranceMicrometerIntegrationTestCase + 
org.jboss.as.test.manualmode.messaging.ha.ReplicatedFailoverTestCase + org.jboss.as.test.clustering.cluster.web.ConcurrentCoarseWebFailoverTestCase test failures don't look related to this upgrade.

2023-07-11 19:58 UTC, scottmarlow commented
> @scottmarlow @yrodiere I filed https://issues.redhat.com/browse/WFLY-18245 to track moving the avro module to WildFly Preview. I don't see that as super-high priority though, and I think it should be handled separately from this PR as I'd like to get this merged today or tomorrow.
> 
> FYI, the related https://issues.redhat.com/browse/JBEAP-25175 is more of a priority though.

Thanks Brian

2023-07-11 19:58 UTC, scottmarlow approved these changes

2023-07-11 20:35 UTC, merged

2023-07-11 20:35 UTC, bstansberry commented
Thanks @yrodiere and @scottmarlow