[WFLY-18258] AssumeTestGroupUtil should log exception if docker is unavailable and not assume false is ok
wildfly/wildfly pull request #17042
Opened 2023-07-24 10:43 UTC by Dkafetzis

https://issues.redhat.com/browse/WFLY-18258

2023-07-26 20:17 UTC, bstansberry commented
/ok-to-test

2023-07-27 15:38 UTC, bstansberry requested changes
Thanks @Dkafetzis. I've suggested some changes below.

2023-07-27 15:38 UTC, bstansberry commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
> +            if (System.getProperty("org.wildfly.test.require.docker").equals("true")){
I kicked off a discussion at https://wildfly.zulipchat.com/#narrow/stream/174184-wildfly-developers/topic/WFLY-18258.20--.20handling.20docker.20being.20unavailable.20in.20CI re whether we should do it like this or invert it. Absent any consensus to change this, this is fine.

2023-07-28 09:09 UTC, Dkafetzis commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
> +            logger.error(String.format("Could not initialize docker, encountered exception Exception: %s", ex.getMessage()));
I agree, It has now been changed

2023-07-28 09:09 UTC, Dkafetzis commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/util/AssumeTestGroupUtil.java
> +    private static final Logger logger = Logger.getLogger(TestLogHandlerSetupTask.class);
Sorry, forgot to change it the first time

2023-08-01 14:38 UTC, bstansberry approved these changes

2023-08-03 20:29 UTC, merged

2023-08-03 20:29 UTC, bstansberry commented
Thanks @Dkafetzis