Fix for WFLY-18430 and WFLY-18790
wildfly/wildfly pull request #17153
Opened 2023-09-06 15:00 UTC by jfdenise

Issues: 
* https://issues.redhat.com/browse/WFLY-18430
* https://issues.redhat.com/browse/WFLY-18790

2023-09-14 17:05 UTC, bstansberry commented
Hey @jfdenise -- it's great to see this. Apologies as I may be a while before I can do a deep dive on this; it's not a 15 minute review!

One general comment from a quick scan is it would be good in the existing classes where we use GlowUtil to disable stuff to have comments explaining to some degree why. Over time that kind of thing will be critical to helping maintainers test correctly with Glow.

2023-09-15 13:38 UTC, jfdenise commented
@bstansberry , I have opened https://github.com/wildfly/wildfly/pull/17181 that is a subset of this Draft PR. It contains only fixes in layers metadata and layers metadata unit tests.  So no change in WildFly integration tests.

It would be great if we could have this in for WF 30.

2023-11-21 03:55 UTC, bstansberry commented
@jfdenise When playing with my WF Core stuff I realized we need to add 'overwriteProvisionedServer' to all these wildfly-maven-plugin provisioning configs. Otherwise you have to use mvn clean to get an updated provisioning if you build a module twice.  IIRC galleon-maven-plugin always re-provisions, so we should get the configure the same behavior with wildfly-maven-plugin.

I'll update https://github.com/wildfly/wildfly-core/pull/5769 tomorrow to fix that in core.

2023-11-21 10:38 UTC, jfdenise commented
@bstansberry , thank-you. Yes, I noticed that. I am currently not using it prior to reach a full green run. It could hide some wrong phase orders (eg: some resources copied to target/wildfly dir that should happen after provisioning). When all is green, I will add the 'overwriteProvisionedServer' option.

2023-11-21 17:37 UTC, bstansberry commented
@jfdenise WDYT about leaving testsuite/layers and testsuite/layers-expansion alone with this? Moving *all* provisioning (except the build/dist modules) to wildfly-maven-plugin costs us our intended test coverage of the galleon-maven plugin.

The benefit of moving to the channel is we'd detect if some updated version in a channel caused one of the many LayersTestCase installations to fail to boot. That's not really the original purpose of testing those installations, but there is *some* value there.

IOW, please regard this comment as an invitation to discuss how we'll test galleon-maven plugin now that we are dropping so much of its use. :)

2023-11-22 09:25 UTC, jfdenise commented
@bstansberry , ok to revert the changes in layers testsuite. That will keep a good coverage of the Galleon maven-plugin: layers provisioning and default configuration provisioning.
Question: Why the build/dist modules will be not using wildfly-maven-plugin + channels?

2023-11-22 13:43 UTC, jfdenise commented
@bstansberry , I reverted the changes for layers and layers-expansion.

2023-11-22 13:56 UTC, bstansberry commented
> Question: Why the build/dist modules will be not using wildfly-maven-plugin + channels?

@jfdenise Maybe they will at some point but that is out of scope for the testing work I'm trying to get done now in a short period of time. So i'm just putting that to the side. My immediate goal is being able to test an externally managed channel. Even https://issues.redhat.com/browse/WFCORE-6615 is kind of out-of-scope, but it was simple to do so I included it in https://github.com/wildfly/wildfly-core/pull/5777. But if that commit would lead to delays in the rest I'd drop it for now.

2023-11-22 13:59 UTC, bstansberry commented
> @bstansberry , ok to revert the changes in layers testsuite. That will keep a good coverage of the Galleon maven-plugin: layers provisioning and default configuration provisioning.

And feature pack creation. :)

2023-11-22 14:02 UTC, jfdenise commented
@bstansberry , for the feature-pack creation I think we are now good, The new CI that tests galleon-plugins with WildFly SNAPSHOT is in place: https://github.com/wildfly/galleon-plugins/pull/271

2023-11-29 22:05 UTC, bstansberry commented on testsuite/integration/basic/pom.xml
> -                                    <version>${testsuite.ee.galleon.pack.version}</version>
I could be wrong but I think the behavior provided by these 3 expressions is being lost.

The goal here of them is to allow control of whether the wildfly-ee or wildfly feature pack is used for provisioning. Standard test runs use the default, which is the wildfly FP. But by setting these props, nightly CI jobs can force the use of wildfly-ee, and we can thus track that that kind of provisioning results in installations that pass the tests.

https://ci.wildfly.org/viewType.html?buildTypeId=WF_MainNightlyJobs_GalleonAltFpLinuxJdk11 does this.

2023-11-29 22:14 UTC, bstansberry commented on testsuite/integration/basic/pom.xml
> -                                    <version>${testsuite.ee.galleon.pack.version}</version>
Maybe just including another feature pack here will do the trick:

https://github.com/wildfly/wildfly/pull/17153/commits/9f649d7f806acd24d12766ebd89b05932a3be244#diff-100b3a1c5caf72adb576b1434ecc9d3f53b284e79cd07baea4b2fcba616730ffR1137-R1143

If the properties are specifying wildfly-ee then it's redundant as wildfly-test-feature-pack depends on wildfly-ee. But if the props specify wildfly FP then we are bringing that FP into the provisioning.

2023-11-29 22:15 UTC, bstansberry commented
@jfdenise I made some review comments above. Is this ready to move out of draft state? It would be good to be able to merge it as soon as it's approved and passes CI.

2023-11-30 10:56 UTC, jfdenise commented
@bstansberry , I commented the usage of GlowUtil, all other comments implemented. Moved to ready for review (resynced with main right now).

2023-12-02 21:49 UTC, pferraro requested changes

2023-12-02 21:49 UTC, pferraro commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/InfinispanServerUtil.java
>                  .numServers(1)
Better to use:
```java
builder.numServers(GlowUtil.isGlowScan() ? 0 : 1);`

2023-12-07 12:38 UTC, jfdenise commented
@bstansberry , coud you tell me what is the expected fix for imports? BTW, I found some duplicated resources in tests (wrongly added by this PR) that I removed in an extra commit.

2023-12-07 13:41 UTC, bstansberry commented
@jfdenise Order is:

import static

import java
import javax

import other

2023-12-07 22:58 UTC, bstansberry approved these changes

2023-12-07 22:59 UTC, merged