WFLY-18457 Avoid creating duplicate thread groups on server reload
wildfly/wildfly pull request #17192
Opened 2023-09-18 11:56 UTC by TomasHofman

https://issues.redhat.com/browse/WFLY-18457

2023-09-18 13:42 UTC, pferraro requested changes

2023-09-18 13:42 UTC, pferraro commented on clustering/ee/infinispan/src/main/java/org/wildfly/clustering/ee/infinispan/scheduler/SchedulerTopologyChangeListener.java
> +
Creating a ThreadGroup requires a permissions check.

2023-09-18 13:42 UTC, pferraro commented on weld/subsystem/src/main/java/org/jboss/as/weld/services/bootstrap/WeldExecutorServices.java
> +    }
Creating a ThreadGroup requires a permissions check.

2023-09-18 16:52 UTC, bstansberry commented
@TomasHofman @pferraro @manovotn

Note that https://github.com/wildfly/wildfly/pull/17193 conflicts with this.

This touches on cross-cutting topics that we may want to standardize across the wildfly/wildfly and wildfly/wildfly-core code bases, so to increase visibility I posted https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/thread/2NICNYJE4NO2HK67DOFTPZUGNAKD5RRM/

My intent there isn't to make a lot of trouble; it's more that if we are going to be touching these it makes sense to think about all aspects of how we use them.

2023-09-19 08:25 UTC, TomasHofman commented
> Note that https://github.com/wildfly/wildfly/pull/17193 conflicts with this.

I'm going to update this PR to resolve the conflict, if we decide to proceed.

2023-09-19 12:03 UTC, manovotn commented
> Note that #17193 conflicts with this.

I have updated the above PR to link it to the WFLY issue and format accordingly.
The previous CI run didn't show any problems removing the thread group from Weld's subsystem.

2023-09-20 08:48 UTC, TomasHofman commented
Closing in favor of https://github.com/wildfly/wildfly/pull/17194, thanks!

2023-09-20 08:48 UTC, closed without merging