[WFLY-18403] making client-ssl-context and server-ssl-context indepent
wildfly/wildfly pull request #17211
Opened 2023-09-25 13:48 UTC by tadamski

https://issues.redhat.com/browse/WFLY-18403

This is an alternative to https://github.com/wildfly/wildfly/pull/17154 

@istudens WDYT?

2023-09-26 06:57 UTC, istudens commented
@tadamski This looks good to me.

2024-04-08 08:29 UTC, soul2zimate commented
This change blocks https://issues.redhat.com/browse/CMTOOL-351 which is a downstream dependency.

Hi @bstansberry, since this is reviewed a long time ago, would you consider merging it?

2024-04-08 10:55 UTC, darranl commented
I am not sure if we can make that change without a model version bump, it looks like this could have transformer implications as well.

2024-06-03 09:22 UTC, darranl commented
The question here is not so much about the issue type, rather do the required changes constitute a model change.  The issue type does not negate the need for model updates to be handled correctly.

If previously valid configurations could now be broken with this change and if we can not operate in mixed domain due to different validation requirements additional consideration would be needed.

2024-06-21 12:39 UTC, emmartins commented
Please note that this is needed for https://issues.redhat.com/browse/CMTOOL-351

2024-06-23 11:58 UTC, tadamski commented
@darranl I started the refactor that you suggested (upgrade schema and implement transformers - new commit in this PR) but I think I cannot simply reject/discard attributes - I think I need only to reject as one of the attributes client-ssl-context/server-ssl-context is set to true and other is set to false as this is the configuration that is going to fail in previous schemas. The only thing in the API that seems a solution for this may be a customer transformer so I tried to implement it but it never gets executed. I have added a mock reject (in the commit) to verify that the registrations are OK and the reject handler is executed. Is nonexecuting CustomTransformer a bug or am I doing something wrongly?

2025-03-14 13:35 UTC, emmartins commented
Is there any news or plan about getting this done?

2025-11-24 01:36 UTC, bstansberry commented
@tadamski I sent https://github.com/tadamski/wildfly/pull/5 to you to fix the problems with this. It passes CI. If it looks good please squash it into your commit and push this branch.

ResourceTransformationDescriptionBuilder.setCustomResourceTransformer only does resource transformation, and not operation transformation. So it can work for when a legacy host connects to the Domain Controller and asks for all the resources, but it would not properly deal with a case where the hosts are already connected but with no iiop-subsystem in the config and then the user does a /subsystem=iiop-openjdk:add. Perhaps a corner case, but, still, it should work.

But a custom RejectAttributeChecker can work and that's what I did. A RejectAttributeChecker can get access to the resource's current model and use that do checks and reject if not ok.

I believe you didn't see the transformer you passed to setCustomResourceTransformer getting called because of how the transformer test infrastructure works. It creates the 'main' KernelServices for the current version. To start the 'legacy' kernel services it works out all the ops to create the 'main' config, transforms the *operations* and then uses those transformed ops to configure the 'legacy' one. But, as I said above what's passed tp ResourceTransformationDescriptionBuilder.setCustomResourceTransformer is only used for resource transformation, and not operation transformation. So it wouldn't get called. There are other workflows where it would get called, but I assume the test failed before it got to those.

Let's try and get this merged for 39 Beta and get one more thing out of the PR queue. Please ping me in Zulip when it is ready.

2025-11-24 12:57 UTC, rhusar requested changes

2025-11-24 12:57 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
Why 3.1? We always bump major schema version in WildFly for each release. Not sure why this violates that rule. Is that's not the case any more @bstansberry ?

2025-11-24 12:57 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +    static final ModelVersion CURRENT_MODEL_VERSION = ModelVersion.create(3,1);
nitpick: run formatter (missing space)

2025-11-24 15:30 UTC, bstansberry commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
I don't care. I want this done and closed. :)

But yes, it should be 4.0.  The 'connector' modules have been our traditional violators about this.

2025-11-24 16:14 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
If you say so... 🫤 but this has been opened since Sep 25, 2023 so I do get that :)

My take on that is that violations like this proliferate, as others learn from other subsystems creating more confusion.

2025-11-24 16:15 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
Nitpick: run formatter on this block, missing space...

2025-12-02 14:05 UTC, tadamski commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +    static final ModelVersion CURRENT_MODEL_VERSION = ModelVersion.create(3,1);
fixed

2025-12-02 14:05 UTC, tadamski commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
I have updated the PR so that the version is 4.0 now

2025-12-02 14:06 UTC, tadamski commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
fixed

2025-12-02 14:08 UTC, tadamski commented
@bstansberry Thanks for transformer fix - I have merged it into this PR

@rhusar I have fixed formatting bugs and changed the schema to 4.0

2025-12-02 14:18 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +    static final ModelVersion CURRENT_MODEL_VERSION = ModelVersion.create(3,1);
Thanks! :)

2025-12-02 14:18 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/IIOPExtension.java
> +        context.setSubsystemXmlMapping(SUBSYSTEM_NAME,Namespace.IIOP_OPENJDK_3_1.getUriString(), IIOPSubsystemParser_3_1::new);
👍🏼 resolving conversation

2025-12-02 14:23 UTC, rhusar requested changes
Just a small typo, otherwise I think this looks good.

2025-12-02 14:23 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/ConfigValidator.java
> +        final boolean severSSLConfigured = IIOPRootDefinition.SERVER_SSL_CONTEXT.resolveModelAttribute(context, resourceModel).isDefined() || securityDomainConfigured;
```suggestion
        final boolean serverSSLConfigured = IIOPRootDefinition.SERVER_SSL_CONTEXT.resolveModelAttribute(context, resourceModel).isDefined() || securityDomainConfigured;
```

2025-12-02 14:23 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/ConfigValidator.java
> +        validateSSLConfig(supportSSL, severSSLConfigured, clientSSLConfigured, serverRequiresSSL, clientRequiresSSL);
```suggestion
        validateSSLConfig(supportSSL, serverSSLConfigured, clientSSLConfigured, serverRequiresSSL, clientRequiresSSL);
```

2025-12-02 14:23 UTC, rhusar commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/ConfigValidator.java
> +        validateSSLSocketBinding(context, resourceModel, severSSLConfigured, clientSSLConfigured, warnings);
```suggestion
        validateSSLSocketBinding(context, resourceModel, serverSSLConfigured, clientSSLConfigured, warnings);
```

2025-12-02 15:33 UTC, tadamski commented on iiop-openjdk/src/main/java/org/wildfly/iiop/openjdk/ConfigValidator.java
> +        final boolean severSSLConfigured = IIOPRootDefinition.SERVER_SSL_CONTEXT.resolveModelAttribute(context, resourceModel).isDefined() || securityDomainConfigured;
fixed

2025-12-02 17:36 UTC, rhusar reviewed
Hm, one last thing – do we really need a new schema? The schemas are identical. It appears to me if we are literally not changing anything in the schema, there is no need to introduce one. Just a model version bump.

```xml
[rhusar@puglia schema]$ diff wildfly-iiop-openjdk_3_0.xsd wildfly-iiop-openjdk_4_0.xsd
8,9c8,9
<            targetNamespace="urn:jboss:domain:iiop-openjdk:3.0"
<            xmlns="urn:jboss:domain:iiop-openjdk:3.0"
---
>            targetNamespace="urn:jboss:domain:iiop-openjdk:4.0"
>            xmlns="urn:jboss:domain:iiop-openjdk:4.0"
12c12
<            version="3.0">
---
>            version="4.0">
```

2025-12-03 11:29 UTC, tadamski commented
@rhusar tbh I always thought that schema file is necessary as a formal reference whenever schema version changes. If it is not the case I can just remove it as it indeed doesn't introduce any changes.

2025-12-03 16:14 UTC, rhusar commented
> @rhusar tbh I always thought that schema file is necessary as a formal reference whenever schema version changes. If it is not the case I can just remove it as it indeed doesn't introduce any changes.

I meant whether we need a new schema meaning version/parser/xsd. There are no changes in that schema, both of these were already optional.

```xml
        <xs:attribute name="server-ssl-context" type="xs:string" use="optional"/>
        <xs:attribute name="client-ssl-context" type="xs:string" use="optional"/>
```

i.e. the enforcement was never in the XSD, so making these independent and optional in the model was always the case in the XSD. What is the value of adding a new schema if they are exactly the same?

2025-12-05 10:11 UTC, tadamski commented
@rhusar I have removed 4.0 schema and left only model bump.

2025-12-05 18:11 UTC, rhusar approved these changes
LGTM, I don't see any more issues, what a saga :-)

2025-12-09 21:45 UTC, tadamski commented
I don't think those testing failures are related.

2025-12-10 11:50 UTC, rhusar commented
> I don't think those testing failures are related.

Correct, these are known to be flaky. No need to rerun.

2025-12-10 11:51 UTC, rhusar commented
Adding 39.x label so that it gets proper consideration for inclusion (since Brian suggested 39 above)

2025-12-11 14:44 UTC, bstansberry approved these changes
Thanks @tadamski !

2025-12-12 13:53 UTC, merged