[WFLY-18547] Set attributes to default values if available
wildfly/wildfly pull request #17230
Opened 2023-09-27 10:35 UTC by The-Huginn

https://issues.redhat.com/browse/WFLY-18547

2023-09-27 11:31 UTC, ehsavoie requested changes

2023-09-27 11:31 UTC, ehsavoie commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
> +                config.hasDefined(EXPIRY_DELAY.getName())
You don't have to use such circumventions:
EXPIRY_DELAY.resolveModelAttribute(context, config).asLong() will use the default value if non is defined

2023-09-27 11:31 UTC, ehsavoie commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
> +                config.hasDefined(LAST_VALUE_QUEUE.getName())
same as as ^^

2023-09-27 13:07 UTC, The-Huginn reviewed
I can see Artemis Settings already have all the values set to the default values. Should I then close this PR?

2023-09-27 13:28 UTC, ehsavoie commented
I think you misunderstood my comment.
I wasn't clear so I'll try to improve:
you don't have to check if the attribute is defined as in the following test:
 config.hasDefined(EXPIRY_DELAY.getName())
you 'just' need to set the value to the resolved value as the resolved value will be set to the default value if it is not defined thus:
 settings.setExpiryDelay(config.hasDefined(EXPIRY_DELAY.getName())? EXPIRY_DELAY.resolveModelAttribute(context, config).asLong()
                        : EXPIRY_DELAY.getDefaultValue().asLong());

can be simplified to:

settings.setExpiryDelay(EXPIRY_DELAY.resolveModelAttribute(context, config).asLong());

2023-09-27 14:39 UTC, The-Huginn commented
Yes, sorry, I didn't realize, it takes (eventually) default value in `resolveModeAttribute` internally. Thanks for the detailed explanation.

2023-09-28 08:16 UTC, ehsavoie approved these changes

2023-10-03 16:41 UTC, bstansberry commented
/ok-to-test

2023-10-04 21:28 UTC, bstansberry commented
@The-Huginn @ehsavoie CI is showing failures in AddressSettingsTestCase

2023-10-04 21:29 UTC, bstansberry requested changes

2023-10-04 21:29 UTC, bstansberry commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingAdd.java
> +import static org.wildfly.extension.messaging.activemq.CommonAttributes.EXPIRY_ADDRESS;
Please move these static imports back up to the top. That's the WildFly code style. Thanks!

2023-10-05 12:07 UTC, The-Huginn commented
After some searching, I believe the cause is in the `AddressSettings.merge()` as internally the `AddressSettings` are using boxed types (Integer) instead of primitives (int), thus default value is null instead of some, for example numerical value.
By always setting the value none of the settings is set to null, so it does not take the value from the merged.
This is the case for the test `testSpecifiedAddressSetting()`.
Due to the order of the test, after it fails it does not remove the address and the other 2 tests fail as well (Not related)

Please let me know, how you would like to proceed @ehsavoie 

I am not pushing the re-ordered imports just yet

2023-10-05 15:22 UTC, ehsavoie requested changes
@The-Huginn you are correct during the merge operation null as a special meaning: thus if we set a value on a sub-setting the super-setting won't override its value so I guess we need to ensure that the if is there for all attribute

2023-10-05 15:56 UTC, The-Huginn commented
@ehsavoie now I am wondering, if this issue is still relevant, or is obsolete now. As each getter provides a default value in `AddressSettings`

2023-10-05 15:57 UTC, ehsavoie commented
@The-Huginn I've updated the issue

2023-10-05 16:07 UTC, ehsavoie commented
@The-Huginn well in the end the attributes until MAX_READ_PAGE_BYTES should use the same if element.
Maybe we could also put some comment here

2023-10-05 17:10 UTC, bstansberry commented
It sounds like this issue has moved from one of 'use the defaults' to one of 'fix the management API read-resource-description output to better reflect what actually happens.'

2023-10-05 17:15 UTC, bstansberry commented
FYI @ehsavoie and I were chatting about some thoughts around this, but I'll bow out and leave it to him to decide what he wants.

Thanks so much @The-Huginn for the research on this!

2023-10-12 15:54 UTC, ehsavoie commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/AddressSettingDefinition.java
> +            .setDefaultValue(new ModelNode(2 * 10 * 1024 * 1024))
Leave that one to -1

2023-10-12 15:58 UTC, ehsavoie commented
The best workaround is to set the default values on the root wildcard address thus they will act as default values when the address settings are merged during resolution.

2023-12-07 09:55 UTC, ehsavoie approved these changes

2023-12-07 09:57 UTC, ehsavoie approved these changes

2024-07-03 00:40 UTC, bstansberry commented
I added the Critical label to this as it fell into a crack and needs to be rescued and merged.

2024-07-09 21:48 UTC, bstansberry commented
Superseded by #18026, which resolves the conflicts.

2024-07-09 21:48 UTC, closed without merging