WFLY-18688 Update JBeret to 2.1.3.Final
wildfly/wildfly pull request #17339
Opened 2023-10-24 15:55 UTC by liweinan

https://issues.redhat.com/browse/WFLY-18688

2023-10-26 19:41 UTC, bstansberry requested changes
@liweinan Can you add a release note or git diff link to the JIRA description so we can see what is coming in? Thanks.

2023-10-27 03:37 UTC, liweinan commented
@bstansberry Yes sir! I have added the release note and updated the fix version accordingly: 

- https://issues.redhat.com/browse/WFLY-18688

2023-10-27 20:22 UTC, bstansberry approved these changes

2023-10-27 21:24 UTC, merged

2023-10-27 21:25 UTC, bstansberry commented
Thanks @liweinan!