[WFLY-18499] adds resteasy mp client useful artifacts to WildFly BOMs
wildfly/wildfly pull request #17445
Opened 2023-11-27 13:09 UTC by emmartins

Issue: https://issues.redhat.com/browse/WFLY-18499
Adds deps needed by apps, such as MP REST Client quickstart

2023-11-27 15:51 UTC, jamezp requested changes

2023-11-27 15:51 UTC, jamezp commented on boms/user/ee/ee-with-tools/pom.xml
> +                                </dependency>
We should not add this. This is for the Jakarta REST `SeBootstrap` which is for SE only environments and should not be used in a Jakarta EE Container.

2023-11-27 16:52 UTC, jamezp approved these changes

2023-11-28 21:26 UTC, merged

2023-11-28 21:26 UTC, bstansberry commented
Thanks @emmartins and @jamezp