[WFLY-18799] Fix linking for distributed-realm and failover-realm so their documentation is rendered
wildfly/wildfly pull request #17451
Opened 2023-11-29 16:11 UTC by Skyllarr

https://issues.redhat.com/browse/WFLY-18799

2023-11-29 18:58 UTC, bstansberry requested changes
@Skyllarr This doesn't work because the docs you are linking to are not incorporated into the overall guide; they are just files in the source.

The list of includes in https://raw.githubusercontent.com/wildfly/wildfly/main/docs/src/main/asciidoc/_elytron/Subsystem_Component_Documentation.adoc needs to include all the adoc files.

Also, I think it would be good to alphabetize the realms table (https://docs.wildfly.org/30/WildFly_Elytron_Security.html#realms) and any other tables that are not alphabetized. Doing them all is reasonably out of scope for this JIRA, but I think at least fixing the 'Realms' table as part of this would be good.

2023-12-04 14:00 UTC, Skyllarr commented
> @Skyllarr This doesn't work because the docs you are linking to are not incorporated into the overall guide; they are just files in the source.
> 
> The list of includes in https://raw.githubusercontent.com/wildfly/wildfly/main/docs/src/main/asciidoc/_elytron/Subsystem_Component_Documentation.adoc needs to include all the adoc files.
> 
> Also, I think it would be good to alphabetize the realms table (https://docs.wildfly.org/30/WildFly_Elytron_Security.html#realms) and any other tables that are not alphabetized. Doing them all is reasonably out of scope for this JIRA, but I think at least fixing the 'Realms' table as part of this would be good.

@bstansberry Thank you! I fixed it and alphabetized the security realms table

2023-12-12 21:11 UTC, bstansberry approved these changes

2023-12-12 21:11 UTC, merged

2023-12-12 21:11 UTC, bstansberry commented
Thanks @Skyllarr