[WFLY-18818]:Print warning message to let user know the cxf dependenc…
wildfly/wildfly pull request #17479
Opened 2023-12-11 08:52 UTC by jimma

https://issues.redhat.com/browse/WFLY-18818

2023-12-12 19:42 UTC, bstansberry commented
@jimma Any logging that was reasonably likely to be unnecessary would need to be INFO or lower, as many users treat WARN as something they have to deal with and get annoyed about anything incorrect.

2023-12-13 00:15 UTC, jamezp commented
If I'm understanding correctly a warning might be right here. What his is doing is checking if there is a module dependency on `org.apache.cxf`, `org.apache.cxf.impl` or `org.jboss.ws.cxf.jbossws-cxf-client`. If the dependency is not there and there is an annotation with a package prefix of `org.apache.cxf`, it warns that a module dependency is required for this to work.

I'm not sure we need to log a warning for every annotation, but it does feel a warning or even error might be appropriate. I assume the deployment will not work as expected.

2023-12-13 05:27 UTC, jimma commented
> @jimma Any logging that was reasonably likely to be unnecessary would need to be INFO or lower, as many users treat WARN as something they have to deal with and get annoyed about anything incorrect.

@bstansberry This changed to not check the cxf module dependency in parent deployment and sibling deployment because of the ModuleSpecification isn't thread safe. I think this covers most of the dependency declaration. If this deployment processor doesn't find the cxf module dependency in the current deployment, it prints some warning message to ask user checks manually. This warning message is kind of reminder or request for user to check the module dependency is correctly configured. Even we can check the cxf module dependency in parent and sibling deployment after we fix [WFCORE-6639](https://issues.redhat.com/browse/WFCORE-6639), the warning message can still be incorrect when user configure this cxf dependency as a global module.

2023-12-13 05:39 UTC, jimma commented
> If I'm understanding correctly a warning might be right here. What his is doing is checking if there is a module dependency on `org.apache.cxf`, `org.apache.cxf.impl` or `org.jboss.ws.cxf.jbossws-cxf-client`. If the dependency is not there and there is an annotation with a package prefix of `org.apache.cxf`, it warns that a module dependency is required for this to work.
> 
That's correct. I only removed the check the module dependency from parent and sibling deployment because of the  ModuleSpecification thread safe issue.  

> I'm not sure we need to log a warning for every annotation, but it does feel a warning or even error might be appropriate. I assume the deployment will not work as expected.
Good point about log a waring message for every annotation @jamezp. This can be improved to print only one warning message as it is only one module dependency is required for this deployment. 
If there isn't cxf module dependency in the current deployment and it is in parent ear or it is in the sibling deployment, it still works, but it beyonds the current deployment processor duty and we can print a warning message to remind user it needs this cxf dependency and user should make sure there is this module dependency whether from parent, sibling or the global module.

2023-12-13 21:44 UTC, jamezp commented on webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
> +                        }
I would just return here after you log.

2023-12-18 12:31 UTC, jimma commented on webservices/server-integration/src/main/java/org/jboss/as/webservices/deployers/WSClassVerificationProcessor.java
> +                        }
Done.

2024-12-17 01:33 UTC, bstansberry commented
@jimma Leaving this message at WARN will essentially regress the https://issues.redhat.com/browse/WFLY-13832 / https://issues.redhat.com/browse/JBEAP-19682 bug fix.

Changing it to INFO avoids that; otherwise we can go with https://issues.redhat.com/browse/WFCORE-7100 / https://github.com/wildfly/wildfly-core/pull/6285 and bend the rule about how to use ModuleSpecification.

2024-12-18 08:11 UTC, jimma commented
@bstansberry @jamezp  Fixed. Please review again. Thanks.

2024-12-18 18:57 UTC, bstansberry requested changes
The main change LGTM; thanks!

I requested some things be restored to the logger file.

2024-12-18 18:57 UTC, bstansberry commented on webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
> -    //void methodInvocationFailed(@Cause Throwable cause, String message);
Please restore the commented methods. They provide documentation of what the message id was used for and help prevent reuse for other purposes by showing any gaps in the currently used id #s was intentional.

2024-12-18 18:57 UTC, bstansberry commented on webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
> -    void missingModuleDependency(String annotation, String clazz, String module);
Please restore this but comment it out.

2024-12-18 18:57 UTC, bstansberry commented on webservices/server-integration/src/main/java/org/jboss/as/webservices/logging/WSLogger.java
> -//    IllegalArgumentException invalidPasswordType();
Please restore.

2024-12-19 17:35 UTC, bstansberry commented
Simple via of TC test status (mostly for my own benefit this today): https://ci.wildfly.org/project.html?projectId=WF_PullRequest&branch_WF_PullRequest=pull%2F17479

2024-12-19 22:13 UTC, merged