[WFLY-18952] Migrate operations for MP OpenTracing and MP Metrics are failing
wildfly/wildfly pull request #17559
Opened 2024-01-25 00:01 UTC by jasondlee

https://issues.redhat.com/browse/WFLY-18952

Correct the path handling code in the migrate ops
Fix typo on extension name for MP Metrics

2024-01-25 01:27 UTC, bstansberry requested changes
This won't work as readResourceFromRoot(address, false) will return a resource that has no grandchildren (the javadoc explains the details).  So root.navigate will not work properly in a domain, where the subsystem resource is a grandchild of the root, not a child.

My specific comments below will fix it.

2024-01-25 01:27 UTC, bstansberry commented on legacy/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/MigrateOperation.java
> +        PathAddress subsystemAddress = context.getCurrentAddress()
PathAddress parentAddress = context.getCurrentAddress().getParent();

2024-01-25 01:27 UTC, bstansberry commented on legacy/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/MigrateOperation.java
>          Resource root = context.readResourceFromRoot(PathAddress.EMPTY_ADDRESS, false);
Resource root = context.readResourceFromRoot(parentAddress, false);

2024-01-25 01:27 UTC, bstansberry commented on legacy/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/MigrateOperation.java
> +            root.navigate(subsystemAddress);
Remove new lines 174, 175, 177; restore old line 171

2024-01-25 01:27 UTC, bstansberry commented on legacy/opentracing-extension/src/main/java/org/wildfly/extension/microprofile/opentracing/MigrateOperation.java
> -        PathAddress address =  pathAddress(OPENTELEMETRY_SUBSYSTEM_ELEMENT);
PathAddress subsystemAddress = parentAddress.append(OPENTELEMETRY_SUBSYSTEM_ELEMENT);

2024-01-25 14:09 UTC, jasondlee commented
> My specific comments below will fix it.

Changes made and pushed.

2024-01-26 15:49 UTC, emmartins approved these changes
Tested manually with the migration tool (cherry-picking this commit to xp5 dev branch), all good, both ops did run successfully, no sign of the reported issues.

2024-02-01 17:41 UTC, merged