[WFLY-19012] Remove Stage.RUNTIME uses of capability 'org.wildfly.legacy-security' in webservices subsystem
wildfly/wildfly pull request #17601
Opened 2024-02-07 10:34 UTC by soul2zimate

Issue: https://issues.redhat.com/browse/WFLY-19012

[WFLY-19012] Remove Stage.RUNTIME uses of capability 'org.wildfly.legacy-security' in webservices subsystem

2024-02-09 13:58 UTC, pferraro requested changes

2024-02-09 13:58 UTC, pferraro commented on webservices/server-integration/src/main/java/org/jboss/as/webservices/service/EndpointService.java
>          }
Remove this whole block.  This can never be null.

2024-02-18 03:45 UTC, jimma approved these changes

2024-02-19 16:51 UTC, merged

2024-02-19 16:52 UTC, bstansberry commented
Thanks @soul2zimate, @jimma and @pferraro