WFLY-19071/WFLY-19072: Fixing AddressSettings default values and Artemis 2.32 dependencies
wildfly/wildfly pull request #17670
Opened 2024-02-27 10:26 UTC by ehsavoie

* Setting the default values on the root of AddressSettings so that
    they are used by all child AddressSettings.
  * Fixing the JSON produced to be retro compatible.
  * Adding module de.dentrassi.crypto.pem-keystore
  * Moving from sunb.jdk to java.base   

Jira: https://issues.redhat.com/browse/WFLY-19072
      https://issues.redhat.com/browse/WFLY-19071

2024-02-27 19:07 UTC, rhusar requested changes

2024-03-08 01:24 UTC, bstansberry requested changes
@ehsavoie Just one minor change, plus I wanted to make Farah (and @darranl) aware of this new crypto lib.

2024-03-08 01:24 UTC, bstansberry commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
>              // TODO see if org.apache.activemq.artemis.client can use specific JDK module(s)
Please remove the TODO comment.

2024-03-08 01:24 UTC, bstansberry commented on ee-feature-pack/galleon-shared/src/main/resources/modules/system/layers/base/de/dentrassi/crypto/pem-keystore/main/module.xml
> +<module xmlns="urn:jboss:module:1.9" name="de.dentrassi.crypto.pem-keystore">
@fjuma FYI about this new module.

2024-03-08 18:28 UTC, bstansberry approved these changes

2024-03-12 10:54 UTC, rhusar requested changes
Also, `ADDESS_SETTINGS_ATTRIBUTES` is never used, what's up with that? :)

2024-03-12 10:54 UTC, rhusar commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ManagementUtil.java
> +    private static final Map<String, AttributeDefinition> ADDESS_SETTINGS_ATTRIBUTES =
This should be `ADDRESS_SETTINGS_ATTRIBUTES`

2024-03-12 10:54 UTC, rhusar commented on messaging-activemq/subsystem/src/main/java/org/wildfly/extension/messaging/activemq/ManagementUtil.java
> +            Arrays.stream(AddressSettingDefinition.ATTRIBUTES).collect(Collectors.toMap(AttributeDefinition::getName, att -> att)) ;
Replace with `Function.identity()`

2024-03-13 11:19 UTC, rhusar approved these changes
LGTM now, feedback has been addressed.

2024-03-15 01:27 UTC, merged

2024-03-15 01:27 UTC, bstansberry commented
Thanks @ehsavoie and @rhusar