[WFCORE-4917]: Experimental - Provide a cool boot banner.
wildfly/wildfly pull request #17703
Opened 2024-03-11 17:26 UTC by ehsavoie

* Add support for a cool ASCII art banner via a banner.txt.

Jira: https://issues.redhat.com/browse/WFCORE-4917

2024-03-12 20:44 UTC, bstansberry commented on ee-feature-pack/galleon-local/src/main/resources/packages/banner/content/bin/banner.txt
> +                         /____/                                /_/
WildFly Full isn't really a thing.

2024-03-19 22:01 UTC, bstansberry requested changes
@ehsavoie This won't work correctly for WildFly Preview, as all of the wiring is defined in ee-feature-pack/galleon-local, which is not used in building the wildfly-preview feature pack.

YMMV but I think:

1) The configs/standalone/model change needs to be applied in preview as well
2) The packages/banner stuff should go to ee-feature-pack/galleon-shared, EXCEPT the banner.txt file which stays where it is.
3) There should be a banner.txt in preview/galleon-local as well, but one that says "WildFly Preview". WFP does exist; WildFly Experimental does not.

2024-03-20 11:00 UTC, ehsavoie commented
@bstansberry I hope to have addressed all your concerns :)

2024-03-21 22:00 UTC, bstansberry approved these changes

2024-03-25 18:24 UTC, merged