[WFLY-19190] Update the jaxrs subsystem resource descriptions to be more useful.
wildfly/wildfly pull request #17780
Opened 2024-04-02 04:37 UTC by soul2zimate

issue: https://issues.redhat.com/browse/WFLY-19190

[WFLY-19190] Update the jaxrs subsystem resource descriptions to be more useful.

2024-04-24 18:06 UTC, jamezp requested changes
I think we should remove the property prefix too, e.g. 
> resteasy.add.charset configuration parameter.

I don't see a need for keeping the property name there.

2024-04-24 18:06 UTC, jamezp commented on jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
> +jaxrs.resteasy-prefer-jackson-over-jsonb=resteasy.prefer-jackson-over-jsonb configuration parameter.  Specifies that the Jackson JSON provider should be preferred over the default Jettison JSON provi
This should be:
> Specifies that the Jackson JSON provider should be preferred over the default Jakarta JSON Processing provider for JSON binding.

2024-04-25 01:33 UTC, soul2zimate commented on jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
> +jaxrs.jaxrs-2-0-request-matching=jaxrs.2.0.request.matching configuration parameter. In searching for a matching resource method with which to respond to a request, consider only resource methods wit
Fixed.

2024-04-25 01:33 UTC, soul2zimate commented on jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
> +jaxrs.resteasy-prefer-jackson-over-jsonb=resteasy.prefer-jackson-over-jsonb configuration parameter.  Specifies that the Jackson JSON provider should be preferred over the default Jettison JSON provi
Fixed.

2024-04-25 01:33 UTC, soul2zimate commented on jaxrs/src/main/resources/org/jboss/as/jaxrs/LocalDescriptions.properties
> +jaxrs.resteasy-disable-providers=resteasy.disable.providers configuration parameter. A comma delimited list of fully qualified JAX-RS @Provider class names that will be disabled.
Fixed

2024-04-25 01:34 UTC, soul2zimate commented
Thank you. I have rebased as per your review comments.

2024-05-08 17:07 UTC, jamezp commented
/retest

2024-05-08 17:08 UTC, jamezp approved these changes

2024-05-15 16:50 UTC, merged

2024-05-15 16:50 UTC, bstansberry commented
Thanks @soul2zimate and @jamezp