[WFLY-19286] Add ServerSetupTasks to reload server to a desired stabi…
wildfly/wildfly pull request #17849
Opened 2024-04-26 15:13 UTC by kabir

…lity level

https://issues.redhat.com/browse/WFLY-19286

2024-05-07 19:58 UTC, jamezp commented on testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
> +    public void tearDown(ManagementClient managementClient, String containerId) throws Exception {
Should this be a final method with a `doTearDown()` to ensure the snapshot is always restored?

2024-05-16 13:34 UTC, kabir commented
@jamezp fixed (sorry for the delay)

2024-05-16 22:39 UTC, bstansberry requested changes
@kabir In general this LGTM to me but...

1) I have some minor comments
2) Please rebase as this branch now has two unrelated commits that have equivalents that are already in main.

Please feel free to merge this when ready; i.e. don't wait for my formal approval of the above as I'll not be around for a while.

2024-05-16 22:39 UTC, bstansberry commented on testsuite/integration/smoke/src/test/java/org/jboss/as/test/smoke/stability/AbstractStabilityServerSetupTaskTest.java
> +import static org.jboss.as.controller.descriptions.ModelDescriptionConstants.CORE_SERVICE;
Static imports first.

2024-05-16 22:39 UTC, bstansberry commented on testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
> +import static org.junit.Assert.fail;
Static imports first.

2024-05-16 22:39 UTC, bstansberry commented on testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
> +import java.util.Set;
java and javax after statics but before others

2024-05-16 22:39 UTC, bstansberry commented on testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
> + * it takes a snapshot of the server configuration in the setup() method, and
and ..... ?

2024-05-16 22:39 UTC, bstansberry commented on testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
> +                String.format("%s is not a supported stability level", desiredStability, supportedStabilityLevels),
This is not a valid statement -- two vars but only one expression in the format string

2024-05-16 22:39 UTC, bstansberry commented on testsuite/shared/src/main/java/org/wildfly/test/stabilitylevel/StabilityServerSetupSnapshotRestoreTasks.java
> +                fail("Reload operation didn't finish successfully: " + result.asString());
s/Reload/take-snapshot

2024-05-17 10:00 UTC, merged