[WFLY-19223] LayersTestCase should pass with new org.wildfly.security.elytron-dynamic-ssl module
wildfly/wildfly pull request #17862
Opened 2024-05-01 14:39 UTC by Skyllarr

https://issues.redhat.com/browse/WFLY-19223

2024-05-03 07:57 UTC, Skyllarr commented
@yersan this PR solves the LayersTestCase failures happening on https://github.com/wildfly/wildfly-core/pull/5947

2024-05-03 10:33 UTC, yersan requested changes
@Skyllarr I think this PR can be closed, in my opinion, this is not the expected fix.

2024-05-03 10:33 UTC, yersan commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
> +            "org.wildfly.security.elytron-dynamic-ssl",
In my opinion, this is not the expected fix.

`test-all-layers` installation contains the `elytron` galleon layer, so the `org.wildfly.security.elytron-dynamic-ssl` should have been provisioned by the `test-all-layers`, which makes this change unnecessary.

The fix should be in WildFly Core PR, I'll comment more about it there. The problem is that `elytron` galleon layer is not provisioning `org.wildfly.security.elytron-dynamic-ssl` package.

2024-05-03 10:47 UTC, yersan commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/LayersTestBase.java
> +            "org.wildfly.security.elytron-dynamic-ssl",
@bstansberry I guess we also are going to need a solution to tweak all of these galleon layers tests based on provisioning stability levels. Not sure if we have already discussed the approach for them.

2024-05-07 18:11 UTC, Skyllarr commented
@yersan Thank you for looking into this and explaining, I'm closing this PR

2024-05-07 18:11 UTC, closed without merging