WFLY-19357 Replace wildfly-clustering-common dependency w/wildfly-subsystem in OpenAPI subsystem
wildfly/wildfly pull request #17909
Opened 2024-05-23 21:48 UTC by pferraro

https://issues.redhat.com/browse/WFLY-19357

2024-06-24 17:50 UTC, bstansberry requested changes
@pferraro Other than the one small point below this LGTM.

I did a diff of the read-resource-description output of main vs this branch and it has a couple noteworthy things in the description of the add operation:

```
--- main-rrd.txt	2024-06-24 12:31:04
+++ pr-rrd.txt	2024-06-24 12:34:12
@@ -15,8 +15,8 @@
                 "description" => "Add the MicroProfile OpenAPI subsystem",
                 "request-properties" => {},
                 "reply-properties" => {},
-                "stability" => "default",
                 "read-only" => false,
+                "restart-required" => "all-services",
                 "runtime-only" => false
             },
             "read-children-types" => {
```

The addition of the 'restart-required' is a bug fix, so that's good. Dropping the stability attribute seems wrong, but I believe any problem there would be with the WF Core stuff, not with this PR.

I also did a diff of the undertow subsystem r-r-d output, and as expected there are no changes.

2024-06-24 19:33 UTC, pferraro commented
> Dropping the stability attribute seems wrong, but I believe any problem there would be with the WF Core stuff, not with this PR.

Ah.  While I added the stability attribute to DefaultOperationDescriptionProvider as part of WFCORE-6668, I neglected to update DefaultResourceAddDescriptionProvider as well.
I filed https://issues.redhat.com/browse/WFCORE-6865 to fix this.

The registration logic in wildfly-clustering-common was not overriding the description provider for add operations to use DefaultResourceAddDescriptionProvider, hence the use of DefaultOperationDescriptionProvider.
I filed https://issues.redhat.com/browse/WFLY-19454 to fix this for consumers of wildfly-clustering-common, until those subsystems migrate to wildfly-subsystem.

2024-06-25 12:27 UTC, bstansberry approved these changes

2024-06-25 12:28 UTC, merged

2024-06-25 12:28 UTC, bstansberry commented
Thanks @pferraro