[WFLY-19438] Add hook to disable Snappy compression
wildfly/wildfly pull request #17964
Opened 2024-06-19 15:42 UTC by kabir

https://issues.redhat.com/browse/WFLY-19438

2024-06-20 18:51 UTC, bstansberry commented on microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/KafkaReactiveMessagingSslConfigProcessor.java
> +import static org.wildfly.microprofile.reactive.messaging.config.kafka.ssl.context._private.MicroProfileReactiveMessagingKafkaLogger.LOGGER;
Order of import sections is reversed from what it should be.

2024-06-20 18:55 UTC, bstansberry commented on microprofile/reactive-messaging-smallrye/kafka/src/main/java/org/wildfly/microprofile/reactive/messaging/config/kafka/ssl/context/_private/MicroProfileReactiveMessagingKafkaLogger.java
> +    @Message(id = 3, value = "Snappy compression is not supported when running on Windows. The MicroProfile Config " +
s/Windows/Windows or OSX/g

2024-06-20 18:55 UTC, bstansberry requested changes
Minor point about the error message.

It looks like your IDE import settings need a tweak. ;)

2024-06-21 10:59 UTC, kabir commented
@bstansberry Updated

2024-06-21 14:20 UTC, bstansberry approved these changes

2024-06-21 16:41 UTC, merged