[WFCORE-6960]: Documentation for read-config-as-xml-file
wildfly/wildfly pull request #18159
Opened 2024-08-30 10:04 UTC by ehsavoie

Updating CLI recipes for this new operation.

Jira: https://issues.redhat.com/browse/WFCORE-6960

2024-08-30 10:21 UTC, fabiobrz requested changes
Thanks for this PR @ehsavoie - I've dropped a couple of comments and suggestions.
Also please take the following one into account: https://docs.wildfly.org/33/Admin_Guide.html#operations here too the new operation should be mentioned.

2024-08-30 10:21 UTC, fabiobrz commented on docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
> -[domain@localhost:9990 /] /host=primary:read-config-as-xml
The new text should be added and the old one should NOT be removed now, since the `read-config-as-xml` still exists.

2024-08-30 10:21 UTC, fabiobrz commented on docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
> -[domain@localhost:9990 /] :read-config-as-xml
Same as above, let's add rather than replace.

2024-08-30 10:21 UTC, fabiobrz commented on docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
> +[domain@localhost:9990 /] attachment display --operation=:read-config-as-xml
According to the analysis document we'd actually need to use `read-config-as-xml-as-file`, right?

2024-08-30 10:21 UTC, fabiobrz commented on docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
> +[standalone@localhost:9990 /] attachment save --operation=:read-config-as-xml --file=/home/wildfly/tmp/standalone-runtime.xml
According to the analysis document we'd actually need to use `read-config-as-xml-as-file`, right?

2024-09-01 16:05 UTC, fabiobrz requested changes
Thanks @ehsavoie for addressing my remarks.
I am ok about not advertising `read-config-as-xml` and the deprecation note you added.
I added just one comment for what seems to be a leftover typo.

2024-09-01 16:05 UTC, fabiobrz commented on docs/src/main/asciidoc/_admin-guide/CLI_Recipes.adoc
> +Please note that the operation"
Leftover? It seems the sentence which is started by these words has been added above already.

2024-09-02 08:53 UTC, fabiobrz approved these changes
Thanks @ehsavoie, for fixing the typos. Changes LGTM, approving.

2024-09-04 22:30 UTC, merged

2024-09-04 22:30 UTC, bstansberry commented
Thanks @ehsavoie and @fabiobrz