WFLY-19729 *TxClientEJBForwardingTestCase fail while trying to configure legacy security-realm and with security manager
wildfly/wildfly pull request #18188
Opened 2024-09-13 16:38 UTC by rhusar

Resolves
https://issues.redhat.com/browse/WFLY-19729

2024-09-13 16:39 UTC, rhusar commented
@tadamski @rachmatowicz Can you guys review the updated security configuration in the `ServerSetupTask` or should I ask someone from the security team? Thanks

2024-09-20 11:25 UTC, rhusar commented
Hi @fjuma could you or someone from your team please review the elytron configuration bit[^1] of the PR? Much appreciated!

[^1]: specifically lines https://github.com/wildfly/wildfly/pull/18188/files#diff-63ef7e85a9f1b9907ab663d0c705cecc84a3452cfc8f8519f01497f9a230583cL243-R268

2024-10-14 14:40 UTC, rhusar commented
Happy 1 month 🍰  anniversary to this PR!

2025-01-24 14:01 UTC, darranl requested changes
The security changes do look good but I am not sure is this test ignored on CI so we don't have real results here.

2025-01-24 14:01 UTC, darranl commented on testsuite/shared/src/main/resources/application-users.properties
> +# remoteejbuser=rem@teejbpasswd1
Is there a reason for this additional space?  I don't see where this line gets uncommented.

2025-01-24 14:04 UTC, rhusar commented
> The security changes do look good but I am not sure is this test ignored on CI so we don't have real results here.

That's correct. This test is marked as intermittently failing, that's why it's not running in CI.

However, it's not failing intermittently any more - but consistently hence this PR. 

This PR will make the test  runnable again when intermittent tests are enabled. Then the investigation of intermittent failures can continue.

2025-01-24 14:07 UTC, rhusar commented on testsuite/shared/src/main/resources/application-users.properties
> +# remoteejbuser=rem@teejbpasswd1
The reason legibility and to follow the same convention as the example `# login=password` above.

It doesn't get uncommented since the password is already encoded on line 13. This is un-encoded version of that password.

2025-01-24 14:11 UTC, darranl commented on testsuite/shared/src/main/resources/application-users.properties
> +# remoteejbuser=rem@teejbpasswd1
Thank you, GitHub cut off at line 12 - I see now.

2025-01-24 14:11 UTC, darranl approved these changes
Thank you for the information, I will merge as is so investigation can continue.

2025-01-24 14:12 UTC, merged

2025-01-24 14:54 UTC, rhusar commented
Thanks @darranl !