Wfly 19590
wildfly/wildfly pull request #18191
Opened 2024-09-13 20:57 UTC by jasondlee

Thanks for submitting your Pull Request!

Please delete this text, and add a link to the Jira issue solved by this PR.

If this PR is not for the 'main' branch you must add a link to the equivalent change in 'main'.

Remember to use the Jira issue ID in the PR title and any commits.

2024-09-16 18:56 UTC, bstansberry requested changes
@jasondlee I made a bunch of comments all related to what's needed for this to be a WildFly Preview only feature, which per Friday discussion is the short term goal.

I didn't comment on the testsuite stuff because it wasn't clear to me if those changes required the production code changes, or if they'd work fine in the existing standard WF.

I also didn't comment on the couple System.out.println in the ts, because those are OT to my goal of discussing the 'how to do it in WFP only' topic.

2024-09-16 18:56 UTC, bstansberry commented on galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/grpc/main/module.xml
This file remains unchanged and instead a new module needs to be created in preview/galleon-local.

2024-09-16 18:56 UTC, bstansberry commented on galleon-pack/galleon-shared/src/main/resources/modules/system/layers/base/io/opentelemetry/instrumentation/api/main/module.xml
This file remains unchanged and instead a new module needs to be created in preview/galleon-local.

2024-09-16 21:31 UTC, jasondlee commented on boms/common-expansion/pom.xml
I think have made all of the requested changes.

2024-09-16 21:34 UTC, jasondlee commented on observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemRegistrar.java
> +            "io.opentelemetry.context",
@bstansberry  This change is not strictly necessary for WF Standard, but it also does not hurt. Unless you feel strongly, I'm going to leave this here for simplicity's sake, which means, I guess, the Class.forName() above is not necessary here.

2024-09-17 00:06 UTC, bstansberry commented on observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemRegistrar.java
> +            "io.opentelemetry.context",
OK. This is one that was exported in WF 33 anyway.

2024-10-02 16:43 UTC, bstansberry commented on preview/galleon-local/src/main/resources/modules/system/layers/base/io/opentelemetry/api/main/module.xml
> +        <module name="jdk.management"/>
See my comment at https://github.com/wildfly/wildfly/pull/18266#discussion_r1784844657

2024-10-02 20:25 UTC, bstansberry approved these changes

2024-10-03 00:53 UTC, merged

2024-10-03 00:53 UTC, bstansberry commented
Thansk @jasondlee and @jamezp