[Community] [WFLY-19715] Add documentaion for the new attributes added to control resource constraints for the HTTP management interface.
wildfly/wildfly pull request #18193
Opened 2024-09-15 16:53 UTC by darranl

This PR depends on the following feature being merged to WildFly Core and WildFly upgrading to the corresponding version - https://github.com/wildfly/wildfly-core/pull/6166

https://issues.redhat.com/browse/WFLY-19715

2024-09-16 20:27 UTC, bstansberry requested changes

2024-09-16 20:27 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/Management_Clients.adoc
> +attributes are available to set to control the resource constraints for the HTTP management
s/to set to control/to control/g

2024-09-16 20:27 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/Management_Clients.adoc
> +future release so where possible you should use the attributes defined in the management model.
s/levels this/levels, this/g
s/release so/release. So/g

2024-09-18 16:20 UTC, darranl commented on docs/src/main/asciidoc/_admin-guide/Management_Clients.adoc
> +----
I will have a look, I think I am also Ok without examples - the examples are in the analysis.

Some of the doc in this area is quite old so was more repeating the pattern we had used in other sections.

2024-09-18 16:56 UTC, darranl commented
@bstansberry I have applied the suggestions and removed the examples.

2024-09-19 14:11 UTC, bstansberry approved these changes

2024-09-24 01:24 UTC, merged

2024-09-24 01:24 UTC, bstansberry commented
Thanks @darranl