[WFLY-19397] Jakarta Data support in WildFly Preview
wildfly/wildfly pull request #18227
Opened 2024-09-23 13:14 UTC by bstansberry

https://issues.redhat.com/browse/WFLY-19397

@scottmarlow Doing this is 97% boilerplate, so since I'm sadly responsible for most of the boilerplate details I took a shot at this while watching sports yesterday.

It's a new jakarta.data.api module, a minimal subsystem and a DUP to add the api to the deployment. Plus a galleon layer to allow adding the extension/subsystem. The new module, subsystem and layer are only integrated in WildFly Preview.

We need a subsystem so we can evolve any configuration or add any /deployment=foo.war/subsystem=jakarta-data stuff in the future without breaking people who were accustomed to not needing one. Plus it's just the normal way of adding technologies.

I'll spend a bit of time today trying to port https://github.com/jakartaredhat/hibernate-data-tck/tree/main/runner-web to wildfly-tck-runners. The TCK would be the primary way this would be tested initially.

2024-09-23 17:33 UTC, darranl requested changes
FYI the test failure does relate to the new extension.

2024-09-23 23:58 UTC, bstansberry commented
@darranl That should be fixed now.

2024-09-24 00:03 UTC, bstansberry commented
@darranl @scottmarlow @jamezp A build of this branch passes the Jakarta Data TCK when I use the proposed runner at https://github.com/wildfly/wildfly-tck-runners/pull/184.  So I've moved this out of draft state.

For 34 Final this needs a smoke test, but I don't have time today so I focused on getting the TCK to run and pass, as that's a better proof of the basic validity of the integration for 34 Beta.

@gavinking @starksm64 FYI

2024-09-24 00:44 UTC, jamezp approved these changes

2024-09-24 06:42 UTC, gavinking commented
Great to see

2024-09-24 09:43 UTC, darranl commented
@bstansberry I have a fix for the failure, sending a replacement PR

2024-09-24 20:34 UTC, merged