[WFLY-19833] Refactor the jaxrs subsystem to use the newer subsystem API's
wildfly/wildfly pull request #18315
Opened 2024-10-22 00:01 UTC by jamezp

https://issues.redhat.com/browse/WFLY-19833

I attempted to put these into separate logical commits. These could be squashed, but it seems it will be easier to review with separate commits.

2024-11-21 17:55 UTC, bstansberry commented
@jamezp Please sort the https://github.com/wildfly/wildfly-proposals/pull/367 discussion with @jimma and if the RFE is going first please put a 36.x label on this. Otherwise please make noise on zulip to ensure this gets in ASAP and unblocks Jim.

If Jim's is going first and gets done in plenty of time perhaps 36.x label can come off, but we'll be busy in December.

2024-11-21 23:17 UTC, jamezp commented
@bstansberry Yes. I think @pferraro is going to have some time to review this tomorrow. Once this is resolved, it will make adding new attributes much easier. Plus we'll have an easier way to write tests for new attributes.

2024-11-26 19:46 UTC, pferraro requested changes

2024-11-26 20:05 UTC, jamezp commented on jaxrs/src/main/java/org/jboss/as/jaxrs/JaxrsAttribute.java
> +    private static final AttributeParser ELEMENT_PARSER = new AttributeParser() {
I will test that. I was looking for one and may have just missed it. Thank you!

2024-11-27 21:05 UTC, pferraro approved these changes

2024-11-27 21:06 UTC, merged

2024-11-27 21:06 UTC, bstansberry commented
Thanks @jamezp and @pferraro