[WFLY-19835][WFLY-19836] Integrate Reactive Messaging's AMQP and Kafka connectors with OpenTelemetry
wildfly/wildfly pull request #18320
Opened 2024-10-23 16:48 UTC by kabir

https://issues.redhat.com/browse/WFLY-19835 / https://github.com/wildfly/wildfly-proposals/pull/638
https://issues.redhat.com/browse/WFLY-19836 / https://github.com/wildfly/wildfly-proposals/pull/639

Opening this as an unpolished draft so others can get an idea of the size.

Note that this needs MP Telemetry 2.0, so it is currently includes https://github.com/wildfly/wildfly/pull/18305 (which targets the mp-7-wip branch).

I still need to do the following:
- Community docs
- Add the capability/requirement on MP Telemetry
- Enable the transformers tests (I think I need to fix something in the subsystem test framework in WildFly Core)

But apart from that the feature works as expected from my side, and includes the integration tests I mention in the analysis documents.

2024-11-22 16:28 UTC, istraka requested changes

2024-11-22 16:28 UTC, istraka commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
> +** `mp.messaging.outgoing.[channel-name].tracing-enabled` - Tracubg setting for an incoming channel. The type of connector used by the channel is determined by the value of the `mp.messaging.outgoing
Typo in `Tracubg`

2024-11-22 16:28 UTC, istraka commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Reactive_Messsaging_SmallRye.adoc
> +First we check the lowest level property, i.e on the channel level. If that is not set, we check the value on the connector level, and if it is set we use the channel level value. The resultant value
Shouldn't there be `connector` instead of `channel` in `and if it is set we use the channel level value`?

2024-11-22 17:03 UTC, kabir commented
@istraka thanks, I've incorporated your docs suggestions

2024-12-06 23:34 UTC, bstansberry commented
@kabir Please change the target of this PR to 'main'. The mp-7-wip branch has been merged.

2024-12-09 17:45 UTC, kabir commented
@bstansberry @jasondlee The security manager failure is not related. For the Preview tests, there were a lot of ones blowing up in https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WildFlyPreviewLinuxJdk21/472980 but the [previous run](https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WildFlyPreviewLinuxJdk21/472999) passed and all I did was squash some commits.

I am rerunning these tests [here](https://ci.wildfly.org/buildConfiguration/WF_PullRequest_WildFlyPreviewLinuxJdk21/473054)

The PR contains a commit with some printlns. Those are there because on Friday, I was seeing some intermittent failures. I now think it might have been my environment since I am not able to reproduce any longer, and also have not seen those failures on CI.
My thinking has been to leave those printlns in, just in case. But perhaps it is better to remove them. If so, perhaps we could create a Jira for after this has been merged?

2024-12-10 14:54 UTC, jasondlee approved these changes

2024-12-11 09:12 UTC, rhusar commented on testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/reactive/RunArtemisAmqpSetupTask.java
> +        }
Is this some remnant of testing? I don't think that's ever used.

2024-12-11 09:14 UTC, rhusar requested changes

2024-12-11 09:14 UTC, rhusar commented on microprofile/reactive-messaging-smallrye/extension/src/test/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingAdditionalInitialization.java
> +public class MicroProfileReactiveMessagingAdditionalInitialization extends AdditionalInitialization {
This class is never used.

2024-12-11 09:23 UTC, rhusar commented on microprofile/reactive-messaging-smallrye/config/src/test/java/org/wildfly/microprofile/reactive/messaging/config/KafkaTracingTypeConfigTestCase.java
> +        protected void setInterceptorFactoryTracingType(TracingType tracingType) {
Please run a formatter on this class.

2024-12-11 09:24 UTC, rhusar commented on microprofile/reactive-messaging-smallrye/extension/src/main/java/org/wildfly/extension/microprofile/reactive/messaging/MicroProfileReactiveMessagingConnectorOpenTelemetryTracingResourceDefinition.java
> +    }
Please run a formatter on this class.

2024-12-11 11:53 UTC, darranl commented
CI Green when included in https://github.com/wildfly/wildfly/pull/18500

2024-12-11 11:53 UTC, merged