[WFLY-19910] Add logicalVersion to WildFly manifests
wildfly/wildfly pull request #18344
Opened 2024-11-01 10:39 UTC by spyrkob

Issue: https://issues.redhat.com/browse/WFLY-19910

2024-11-04 15:30 UTC, rhusar requested changes

2024-11-04 15:30 UTC, rhusar commented on pom.xml
> +>>>>>>> 4a3e0fab1f5 ([WFLY-19910] Add logicalVersion to WildFly manifests)
Rebase went bad.

2024-11-21 10:35 UTC, rhusar requested changes

2024-11-21 10:35 UTC, rhusar commented on preview/channel/pom.xml
> +                    <manifestLogicalVersion>WildFly preview ${project.version}</manifestLogicalVersion>
We are calling this distribution 'WildFly Preview' - notice the capital P.

2024-11-21 23:12 UTC, bstansberry commented
@spyrkob @jamezp I suspect there's a needed update to the WildFly Maven Plugin to handle the new manifest schema

2024-11-21 23:25 UTC, jamezp commented
I just released 5.1.0.Alpah2 today. I hope that's enough.

I'd really like to find a way where we can release these types of things independently.

2024-11-26 14:01 UTC, spyrkob commented
@bstansberry I think this should be ready now

2024-11-27 13:32 UTC, jfdenise commented
I have logged https://issues.redhat.com/browse/WFLY-20028 to track the WildFly Galleon Plugins upgrade to 7.3.1.Final

2024-11-27 17:28 UTC, mchoma commented on pom.xml
> +        <version.org.wildfly.galleon-plugins>7.3.1.Final</version.org.wildfly.galleon-plugins>
I was told by @fabiobrz and @jbliznak that we are waiting for this line to be merged to ublock our testing with wildfly snapshot.

Please can we work to merge this and unblock wildfly snapshot testing.

2024-11-27 18:13 UTC, jamezp approved these changes

2024-11-27 19:09 UTC, merged