[WFLY-19846] [cleanup] Promote MicroProfile Telemetry 2.0 to WildFly Standard
wildfly/wildfly pull request #18353
Opened 2024-11-07 21:18 UTC by jasondlee

https://issues.redhat.com/browse/WFLY-19846

- Revert changes to shared OpenTelemetryServerSetupTask
- Create private/local ServerSetupTask for BasicOpenTelemetryTestCase
- Add helper method for metric handling
- Clean up debug logging

2024-11-08 09:27 UTC, rhusar requested changes
This actually needs changes:

1. Makes a BasicOpenTelemetryTestCase fail with java.lang.IllegalStateException: Could not connect to Ryuk at localhost:34003
2. needs a git squash

2024-11-08 14:48 UTC, jasondlee commented
> This actually needs changes:
> 
>     1. Makes a BasicOpenTelemetryTestCase fail with java.lang.IllegalStateException: Could not connect to Ryuk at localhost:34003
> 
>     2. needs a git squash

1. It passed for me locally, but I have `TESTCONTAINERS_RYUK_DISABLED=true` in my env. I may just add that to the surefire config. Ryuk is almost always the culprit in these test failures.
2. Yes, but git was behaving oddly, trying to squash ~10 commits when I told it 3. I'll try again Monday.

2024-11-11 17:40 UTC, jasondlee commented
> This actually needs changes:
> 
>     1. Makes a BasicOpenTelemetryTestCase fail with java.lang.IllegalStateException: Could not connect to Ryuk at localhost:34003
> 
>     2. needs a git squash

Squash done. We'll see how the CI likes #1...

2024-11-12 09:23 UTC, rhusar requested changes

2024-11-12 09:23 UTC, rhusar commented on testsuite/integration/microprofile/pom.xml
> +                        <TESTCONTAINERS_RYUK_DISABLED>true</TESTCONTAINERS_RYUK_DISABLED>
I don't think we want this. IIRC Ryuk is used to reap containers on platforms like Linux and disabling it especially on CI will cause problems.

Case in point, the tests fail with something that sounds like it's a direct result of this:

```
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [33376, 33377, 33374, 33375] should be listening)
```

2024-12-02 10:34 UTC, rhusar requested changes
Needs a rebase (leaving this comment so this gets attention if it needs to).

2024-12-02 10:37 UTC, rhusar commented on testsuite/integration/microprofile/pom.xml
> +                        <testcontainers.reuse.enable>false</testcontainers.reuse.enable>
What's the purpose of this?

Reading https://java.testcontainers.org/features/reuse/ - 'Those containers won't stop after all tests are finished.' so this is definitely disabled by default, so I am not sure why this is desired here.

2024-12-02 15:04 UTC, rhusar commented on testsuite/integration/microprofile/pom.xml
> +                        <testcontainers.reuse.enable>false</testcontainers.reuse.enable>
👍🏼

2024-12-02 18:06 UTC, jasondlee commented
/retest

2024-12-02 18:35 UTC, jamezp commented
/retest

2024-12-06 23:34 UTC, bstansberry commented
@jasondlee Please change the target of this PR to 'main'. The mp-7-wip branch has been merged.

2024-12-07 04:34 UTC, jasondlee commented
> @jasondlee Please change the target of this PR to 'main'. The mp-7-wip branch has been merged.

@bstansberry Retargeted.

2025-12-07 18:58 UTC, bstansberry commented
@jasondlee I put the 39.x label on this not because it has to be done for 39, but just to draw a bit of attention to it. But that was a misuse of that label, so I'm going to remove it.

 It had the Feature label even though the feature was long since done, which probably helped this fall into a crack. Anyone this looks like one of those WIP things that we should try and bring to conclusion.

2025-12-08 11:33 UTC, rhusar requested changes

2025-12-08 11:33 UTC, rhusar commented on testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/OpenTelemetrySetupTask.java
> +        otelCollectorContainer.stop();
IIRC This needs to be last, not first, otherwise you are going to get unnecessary connection errors.

I already fixed this in org.jboss.as.test.shared.observability.setuptasks.OpenTelemetryWithCollectorSetupTask

2025-12-08 11:33 UTC, rhusar commented
Also, needs a BIG rebase :)

2026-02-03 22:23 UTC, closed without merging