WFLY-19591 Community doc updates for MicroProfile OpenAPI 4.0.
wildfly/wildfly pull request #18360
Opened 2024-11-12 10:31 UTC by pferraro

https://issues.redhat.com/browse/WFLY-19591

2024-11-12 12:02 UTC, rhusar commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
> +{"openapi": "{OpenAPIVersion}.0" ... }
FWIW for some reason this doesn't render on GitHub - https://github.com/wildfly/wildfly/blob/44db5eefc1b340055f7b9e45cf23e947f99cf2df/docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc#https-endpoint - but that doesn't matter.

2024-11-12 12:05 UTC, rhusar requested changes

2024-11-12 12:05 UTC, rhusar commented
Also, no need to run CI on these. Cancelling manually.

2024-11-13 11:28 UTC, rhusar commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
> +{"openapi": "{OpenAPIVersion}.0" ... }
You need to add subs="attributes+" to the block:

```[source,shell,subs="attributes+"]```

2024-11-14 08:32 UTC, pferraro commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
> +{"openapi": "{OpenAPIVersion}.0" ... }
This is the same code block.

2024-11-14 08:33 UTC, pferraro commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc
> +{"openapi": "{OpenAPIVersion}.0" ... }
Perfect, thanks!

2024-11-14 10:34 UTC, rhusar approved these changes
Looks good now, ready to go @kabir

2024-11-14 10:34 UTC, rhusar commented
Also, no need to run CI but cancelling it last time did not work.

2024-11-14 10:44 UTC, merged