[WFLY-19370] add more log messages for debugging
wildfly/wildfly pull request #18381
Opened 2024-11-14 16:37 UTC by rsearls

https://issues.redhat.com/browse/WFLY-19370

this supersede PR https://github.com/wildfly/wildfly/pull/18342

2026-01-28 14:15 UTC, rhusar commented
> @[wildfly-bot](https://github.com/apps/wildfly-bot) wildfly-bot bot requested a review from [tadamski](https://github.com/tadamski) [2 years ago](https://github.com/wildfly/wildfly/pull/18381#event-15301462170)

Any chance @tadamski you had a chance to look at it in the last 2 years? :)

IIUC this is adding debut output to investigate JWTIdentityPropagationTestCase – https://issues.redhat.com/browse/WFLY-19370

Also, @rsearls needs a rebase.

2026-01-28 14:30 UTC, tadamski requested changes

2026-01-28 14:30 UTC, tadamski commented on ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
> +            ROOT_LOGGER.debug("## EJBComponent getIncomingRunAsIdentity ");
@rsearls could you please remove trailing space in the message

2026-01-28 14:30 UTC, tadamski commented on ejb3/src/main/java/org/jboss/as/ejb3/component/EJBComponent.java
> +        if (ROOT_LOGGER.isTraceEnabled()) {
those lines perform isTraceEnabled check and later print debug message. I think it should be isDebugEnabled

2026-01-28 14:31 UTC, tadamski commented
@rhusar nope, sorry, I missed this PR - I think it is ok but some minor changes are needed. I added them to the review. cc @rsearls

2026-04-14 15:38 UTC, darranl commented
Closing as investigation moved over to @rhusar

2026-04-14 15:38 UTC, closed without merging