WFLY-19974 Update Arquillian Testcontainers to 1.0.0.Alpha3
wildfly/wildfly pull request #18405
Opened 2024-11-19 21:13 UTC by jasondlee

https://issues.redhat.com/browse/WFLY-19974

* Bump version
* Move version info to managed property
* Remove explicit Exception use in annotation so tests will fail if the container engine is not available
* Add profile to skip tests where docker is not required

2024-11-19 22:13 UTC, jamezp reviewed
I feel like it might be best to add a profile for setting the system property rather than setting it on CI. Something like `skip-testcontainer-tests`.

2024-11-19 22:14 UTC, jasondlee commented
> I feel like it might be best to add a profile for setting the system property rather than setting it on CI. Something like `skip-testcontainer-tests`.

That's a good idea. I can add a profile to this PR.

2024-11-20 15:08 UTC, rhusar requested changes
This is missing a profile activation that changes this exception so that tests get skipped on ~~Windows hosts~~ hosts that don't have a container runtime.

2024-11-21 20:43 UTC, jamezp approved these changes, later dismissed

2024-11-21 20:47 UTC, rhusar requested changes
@jasondlee These files need to be updated too:

```
testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/microprofile/faulttolerance/micrometer/FaultToleranceMicrometerIntegrationDisabledTestCase.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/BaseContainer.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/MicrometerSetupTask.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/OpenTelemetryWithCollectorSetupTask.java:@DockerRequired(AssumptionViolatedException.class)
```

2024-11-26 20:13 UTC, rhusar requested changes
@jasondlee These classes  in this branch still haven't been updated, I think you have have mixed up the branches...

```
testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/ContextPropagationTestCase.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/integration/microprofile/src/test/java/org/wildfly/test/integration/observability/opentelemetry/OpenTelemetryIntegrationTestCase.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/preview/expansion/src/test/java/org/wildfly/test/preview/microprofile/telemetry/MetricsTestCase.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/containers/BaseContainer.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/MicrometerSetupTask.java:@DockerRequired(AssumptionViolatedException.class)
testsuite/shared/src/main/java/org/jboss/as/test/shared/observability/setuptasks/OpenTelemetrySetupTask.java:@DockerRequired(AssumptionViolatedException.class)
```

2024-11-26 20:15 UTC, jasondlee commented
@rhusar Strange. I thought I had searched the whole code base, but I'll double check.

2024-11-26 20:19 UTC, rhusar commented
The problem with leaving those (the default exception) in there is that they will continue to be skipped silently and appear all green here on CI status checks.

2024-11-26 20:21 UTC, jasondlee commented
Right. I think I just didn't search widely enough. Fixed and testing locally.

2024-11-26 20:28 UTC, rhusar approved these changes
Code looks good now, I ll be asleep when CI runs finish, so leaving 👍🏼  here now.

2024-11-27 02:09 UTC, merged

2024-11-27 02:09 UTC, bstansberry commented
Thanks @jasondlee, @rhusar and @jamezp