[WFLY-20008] Remove all non-breaking uses of ModuleIdentifier in Pojo Subsystem
wildfly/wildfly pull request #18436
Opened 2024-11-26 04:34 UTC by soul2zimate

Issue: https://issues.redhat.com/browse/WFLY-20008

[WFLY-20008] Remove all non-breaking uses of `ModuleIdentifier` in Pojo Subsystem

2024-11-26 17:33 UTC, ropalka approved these changes
Except one minor issue it LGTM

2024-11-26 17:33 UTC, ropalka commented on pojo/src/main/java/org/jboss/as/pojo/KernelDeploymentModuleProcessor.java
> +    private String POJO_MODULE = "org.jboss.as.pojo";
POJO_MODULE field should be final

2024-11-26 20:42 UTC, bstansberry commented
I put the hold label on this pending resolution of https://wildfly.zulipchat.com/#narrow/channel/174184-wildfly-developers/topic/ModuleIdentifier.20deprecation/near/484590414

2024-11-27 01:48 UTC, soul2zimate commented on pojo/src/main/java/org/jboss/as/pojo/KernelDeploymentModuleProcessor.java
> +    private String POJO_MODULE = "org.jboss.as.pojo";
made it `final`

2024-12-06 20:48 UTC, bstansberry commented
I added the core-upgrade-needed label because this needs to use something like https://github.com/wildfly/wildfly-core/pull/6270 to handle module name strings passed in from outside.

2024-12-06 20:50 UTC, bstansberry requested changes
I added the core-upgrade-needed label because this needs to use something like https://github.com/wildfly/wildfly-core/pull/6270 to handle module name strings passed in from outside.

2024-12-11 02:08 UTC, bstansberry commented
@soul2zimate The https://github.com/wildfly/wildfly-core/pull/6270 API is now available.

2024-12-16 00:28 UTC, soul2zimate commented
/retest

Hi @bstansberry , The change here doesn't need the wildfly-core API.

2024-12-16 14:26 UTC, ropalka approved these changes

2024-12-16 22:08 UTC, bstansberry commented
@soul2zimate @ropalka 

See KernelDeploymentXmlDescriptorParser L354

```
    private ModuleConfig parseModuleConfig(final XMLExtendedStreamReader reader) throws XMLStreamException {
        final ModuleConfig moduleConfig = new ModuleConfig();
        final int count = reader.getAttributeCount();
        final Set<Attribute> required = EnumSet.of(Attribute.NAME);
        for (int i = 0; i < count; i++) {
            final Attribute attribute = Attribute.of(reader.getAttributeLocalName(i));
            required.remove(attribute);
            final String attributeValue = reader.getAttributeValue(i);

            switch (attribute) {
                case NAME:
                    moduleConfig.setModuleName(attributeValue);
```

That 'attributeValue' is what gets passed through to ConfigVisitor.loadModule via ModuleConfig.visit.

I think canonicalizing it in the KernelDeploymentXmlDescriptorParser code is fine. I have a vague general preference for doing it as close to the user input as possible so it doesn't end up getting done repeatedly or for strings that come from our own presumably 'safe' static module names.

2024-12-17 02:00 UTC, bstansberry approved these changes

2024-12-17 11:15 UTC, ropalka approved these changes
Good catch @bstansberry !

2024-12-17 12:59 UTC, merged