[WFLY-20009] Remove all non-breaking uses of ModuleIdentifier in MP Config Subsystem
wildfly/wildfly pull request #18437
Opened 2024-11-26 07:22 UTC by soul2zimate

Issue: https://issues.redhat.com/browse/WFLY-20009

[WFLY-20009] Remove all non-breaking uses of ModuleIdentifier in MP Config Subsystem

2024-11-26 17:35 UTC, ropalka approved these changes

2024-12-06 20:51 UTC, bstansberry requested changes
I added the core-upgrade-needed label because this needs to use something like https://github.com/wildfly/wildfly-core/pull/6270 to handle module name strings passed in from outside.

2024-12-11 02:07 UTC, bstansberry commented
@soul2zimate The https://github.com/wildfly/wildfly-core/pull/6270 API is now available.

2024-12-11 22:21 UTC, bstansberry commented
This is another one that can use ModuleIdentifierUtil.MODULE_NAME_CORRECTOR.

2024-12-16 00:43 UTC, soul2zimate commented
PR is updated.

2024-12-16 14:25 UTC, ropalka approved these changes

2024-12-16 22:10 UTC, bstansberry approved these changes

2024-12-16 22:11 UTC, merged

2024-12-16 22:11 UTC, bstansberry commented
Thanks @soul2zimate and @ropalka