[WFLY-20102] only encode and log route for first getRoute call
wildfly/wildfly pull request #18518
Opened 2024-12-13 00:22 UTC by aogburn

https://issues.redhat.com/browse/WFLY-20102

2024-12-17 18:04 UTC, bstansberry commented
@fl4via Please review.

2025-02-10 12:35 UTC, soul2zimate commented
Hi @fl4via , Could you review this one ? We need same fix in downstream. Thanks.

2025-02-10 13:53 UTC, pferraro requested changes

2025-02-10 13:53 UTC, pferraro commented on undertow/src/main/java/org/wildfly/extension/undertow/Server.java
> +        if (this.finalRoute != null) {
Since this is a dynamically generated value, it would be best to establish this within Service.start(...).

2025-02-10 13:53 UTC, pferraro commented on undertow/src/main/java/org/wildfly/extension/undertow/Server.java
> +    private String finalRoute = null;
This needs to be volatile.

2025-02-19 01:40 UTC, bstansberry commented on undertow/src/main/java/org/wildfly/extension/undertow/Server.java
> +        if (this.finalRoute != null) {
Note that doing that may require changes to some unit test stuff that uses a Server but doesn't call start/stop on it.

org.wildfly.mod_cluster.undertow.UndertowEngineTestCase, perhaps others.

2025-03-01 14:36 UTC, closed without merging