WFLY-19314 added integration tests for oidc logout
wildfly/wildfly pull request #18523
Opened 2024-12-13 15:08 UTC by rsearls

https://issues.redhat.com/browse/WFLY-19314 Logout support for OIDC

depends on:  https://issues.redhat.com/browse/ELY-2534 Logout support for OIDC  
        - draft PR: https://github.com/wildfly-security/wildfly-elytron/pull/2245

2024-12-18 22:35 UTC, fjuma requested changes
@rsearls Thanks very much for this PR! I've starting adding some comments. Feel free to let me know if you have any questions.

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
> +    public static void setBackchannelLogoutUrl(ClientRepresentation client,
s/setBackchannelLogoutUrl/setBackChannelLogoutUrl

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(RP_INITIATED_LOGOUT_APP, "GOOD");
Just to check, why is the expected text "GOOD" here? Wouldn't that indicate that the user is still logged in?

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(FRONT_CHANNEL_LOGOUT_APP, "GOOD");
Just to check, why is the expected text "GOOD" here? Wouldn't that indicate that the user is still logged in?

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(POST_LOGOUT_APP, "GOOD");
Just to check, why is the expected text "GOOD" here? Wouldn't that indicate that the user is still logged in?

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +    public static void loginToApp(String username, String password,
Just to check, I think there's a similar method in OidcBaseTest, right? Can we use a common method implementation for both?

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +    public static class KeycloakSetup implements ServerSetupTask {
This class and the code below is also a duplicate of code in OidcBaseTest, right? Would it make sense to have common code that both classes could make use of?

2024-12-18 22:35 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/logout/BackChannelLogoutApp-oidc.json
> +{
Do we have any tests that make use of the new json and subsystem options for specifying a custom logout URI, custom callback URI, etc.?

2024-12-18 22:37 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/logout/BackChannelLogoutApp-oidc.json
> +{
Actually, just realized that I don't see the new subsystem attributes in this PR yet. I know we discussed leaving these out before but now that we're targeting the Preview stability level, they can be added.

2025-01-06 14:44 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
> +    public static void setBackchannelLogoutUrl(ClientRepresentation client,
Done

2025-01-06 15:05 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
> +    public static void setBackchannelLogoutUrl(ClientRepresentation client,
@fjuma  This method is a wrapper for oidcAdvancedConfigWrapper.setBackchannelLogoutUrl
Don't we want to continue using the same method name as in
org.keycloak.protocol.oidc.OIDCAdvancedConfigWrapper?

2025-01-06 15:48 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/KeycloakConfiguration.java
> +    public static void setBackchannelLogoutUrl(ClientRepresentation client,
Ah, what you have is fine then.

2025-01-06 16:28 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(RP_INITIATED_LOGOUT_APP, "GOOD");
"GOOD" is RESPONSE_BODY returned by 
org.jboss.as.test.integration.security.common.servlets.SimpleServlet which is an unsecured endpoint.  RESPONSE_BODY is a public static. I have switched the code to referencing it.

2025-01-06 16:29 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(FRONT_CHANNEL_LOGOUT_APP, "GOOD");
"GOOD" is the response body to the unsecured endpoint so the user is logged out.

2025-01-06 16:30 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(POST_LOGOUT_APP, "GOOD");
Same as previous

2025-01-06 16:30 UTC, fjuma commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +        assertUserLoggedOut(RP_INITIATED_LOGOUT_APP, "GOOD");
I think we should try accessing a secured endpoint here to make sure that it cannot be accessed.

2025-01-06 16:33 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +    public static void loginToApp(String username, String password,
There is a similar method but is contains a bunch of code these tests will not need.

2025-01-06 16:38 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/java/org/wildfly/test/integration/elytron/oidc/client/logout/OidcLogoutBaseTest.java
> +    public static class KeycloakSetup implements ServerSetupTask {
That was a consideration.  At the time it was a concern that changes these tests required would break the existing tests.  Once all tests for this, oidc.json and server config tests are in place I will reevaluate what can be shared.

2025-01-06 16:41 UTC, rsearls commented on testsuite/integration/elytron-oidc-client/src/test/resources/org/wildfly/test/integration/elytron/oidc/client/logout/BackChannelLogoutApp-oidc.json
> +{
As we discussed before the holiday break oidc.json and server config tests will be added to the initial set of tests.  Those will be started soon.

2025-12-09 13:25 UTC, skyllarr commented
@rsearls Is this draft PR superceded by the https://github.com/wildfly/wildfly/pull/18781 ? If so, can this be closed?

2025-12-09 14:01 UTC, rsearls commented
this PR is superceded by the #18781

2025-12-09 14:01 UTC, closed without merging