WFLY-20041 - Log a warning if more than one metrics system is enabled
wildfly/wildfly pull request #18549
Opened 2024-12-16 16:06 UTC by jasondlee

https://issues.redhat.com/browse/WFLY-20041

- Add Capability checks to the metrics, micrometer, and opentelemetry subsystems
- Add new log messages

2025-02-13 11:01 UTC, rhusar commented
@jasondlee Please resolve the SCM conflict since the other PR got merged.

2025-02-13 11:04 UTC, rhusar requested changes

2025-02-13 11:04 UTC, rhusar commented on metrics/src/main/java/org/wildfly/extension/metrics/_private/MetricsLogger.java
> +    @Message(id = 6, value = "The system may have more than one metrics gathering system enabled. Please see the administration guide for more information.")
Lets be more specific here, i.e. "multiple metrics collection systems"

2025-02-13 11:04 UTC, rhusar commented on observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
> +    @Message(id = 12, value = "The system may have more than one metrics gathering system enabled. Please see the administration guide for more information.")
Lets be more specific here, i.e. "multiple metrics collection systems"

2025-02-18 18:14 UTC, jasondlee commented on metrics/src/main/java/org/wildfly/extension/metrics/_private/MetricsLogger.java
> +    @Message(id = 6, value = "The system may have more than one metrics gathering system enabled. Please see the administration guide for more information.")
Updated

2025-02-18 18:14 UTC, jasondlee commented on observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
> +    @Message(id = 12, value = "The system may have more than one metrics gathering system enabled. Please see the administration guide for more information.")
Updated

2025-02-18 23:22 UTC, bstansberry commented on observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
> +    @Message(id = 12, value = "Additional metrics systems discovered while configuring Micrometer: %s. Please see the administration guide for more information.")
@jasondlee 

1) Where is this covered in the administration guide?
2) This approach is problematic for downstream, where the documentation is completely different.

2025-02-18 23:38 UTC, bstansberry commented on observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemRegistrar.java
> +        }
This is a tangent to this PR, sparked by my thinking about the problem you're solving here.

https://opentelemetry.io/docs/languages/java/configuration/#properties-exporters lists 'none' as a valid value for otel.metrics|traces|logs.exporter, which implies that in the future we could perhaps allow the disabling any of those via the subsystem API. With otel.metrics.exporter=none being the one that's relevant to the problem you're addressing here.

2025-02-18 23:44 UTC, jasondlee commented on observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
> +    @Message(id = 12, value = "Additional metrics systems discovered while configuring Micrometer: %s. Please see the administration guide for more information.")
Hrm. It looks like the only mention is here: https://docs.wildfly.org/35/Admin_Guide.html#MicroProfile_Telemetry

2025-02-18 23:45 UTC, jasondlee commented on observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemRegistrar.java
> +        }
I've thought of that, too, but it gets complicated as that's "just" a system property for OpenTelemetry, but, for MicroProfile Telemetry, it would have to come from a MicroProfile ConfigSource to be exhaustive, and it didn't seem prudent (or currently possible) to do a check like that in the subsystem code.

2025-02-18 23:46 UTC, jasondlee commented on observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetrySubsystemRegistrar.java
> +        }
And we could actually add those now via the in-flight WFLY-20296...

2025-02-19 16:28 UTC, jasondlee commented on observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
> +    @Message(id = 12, value = "Additional metrics systems discovered while configuring Micrometer: %s. Please see the administration guide for more information.")
I have update the documentation to give more information about the log message.

2025-02-22 15:38 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Observability_Tracing.adoc
This comment is out of scope for this PR, but renaming this file would be good. It took me a while to figure out how it fit into the overall docs, i.e. that it was the OTel subsystem section.

2025-02-22 15:44 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Observability_Tracing.adoc
This OTel section should say something about the metrics conflict as well.

2025-02-22 15:48 UTC, bstansberry commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Metrics.adoc
This document should say something about the 'conflicting' subsystems as well.

2025-02-22 15:58 UTC, bstansberry requested changes
I've made a number above about improvements, but the simple copy editing ones below are the blockers for the PR.

2025-02-22 15:58 UTC, bstansberry commented on metrics/src/main/java/org/wildfly/extension/metrics/_private/MetricsLogger.java
> +    @Message(id = 6, value = "Additional metrics systems discovered while configuring WildFly Metrics: %s. Please refer to the documentation more information.")
s/more/for more/g

2025-02-22 15:58 UTC, bstansberry commented on observability/micrometer/src/main/java/org/wildfly/extension/micrometer/MicrometerExtensionLogger.java
> +    @Message(id = 12, value = "Additional metrics systems discovered while configuring Micrometer: %s. Please refer to the documentation more information.")
s/more/for more/g

2025-02-22 15:58 UTC, bstansberry commented on observability/opentelemetry/src/main/java/org/wildfly/extension/opentelemetry/OpenTelemetryExtensionLogger.java
> +    @Message(id = 14, value = "Additional metrics systems discovered while configuring OpenTelemetry: %s. Please refer to the documentation more information.")
s/more/for more/g

2025-02-22 16:05 UTC, bstansberry commented
In the future WDYT about a table that outlines what the various options provide? That could be a separate adoc file included in each subsystem guide, a la the way we have a common doc for the galleon layers that's used in different docs about different ways to provision WF.

Right now we have all these options but it's hard to understand what each brings.

So perhaps a col for each of the four subsystems and then a row for different things

JVM Metrics
Server metrics
Custom application metrics
OTLP Export
Prometheus scrapes
Configuration via MicroProfile Config
Other rows as things evolve (e.g. if we support specific bindings to OTel or Micrometer, e.g. Hibernate, etc)

2025-02-24 14:55 UTC, jasondlee commented
@bstansberry That's a great idea. Captured here: https://issues.redhat.com/browse/WFLY-20418

2025-02-24 14:57 UTC, jasondlee commented on docs/src/main/asciidoc/_admin-guide/subsystem-configuration/Observability_Tracing.adoc
Rename captured: https://issues.redhat.com/browse/WFLY-20419

2025-02-24 15:15 UTC, bstansberry approved these changes

2025-02-24 15:16 UTC, merged