[WFLY-6545] Upgrade jsf-impl to 2.2.13.SP2 and add support for a 'disallow-doctype-decl' attribute to the JSF subsystem
wildfly/wildfly pull request #9076
Opened 2016-07-27 17:50 UTC by fjuma

https://issues.jboss.org/browse/WFLY-6545

2017-10-30 20:43 UTC, bstansberry requested changes

2017-10-30 20:43 UTC, bstansberry commented on jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFSubsystemAdd.java
> +                JSFResourceDefinition.DISALLOW_DOCTYPE_DECL.resolveModelAttribute(context, model).asBoolean() : null;
```
final Boolean disallowDoctypeDecl = JSFResourceDefinition.DISALLOW_DOCTYPE_DECL.resolveModelAttribute(context, model).asBooleanOrNull();
```

2017-10-30 20:43 UTC, bstansberry commented on jsf/subsystem/src/main/java/org/jboss/as/jsf/subsystem/JSFExtension.java
> +            JSFResourceDefinition.registerTransformers(subsystem);
There's a new ServiceLoader based way of registering transformers that should be used -- see implementations of org.jboss.as.controller.transform.ExtensionTransformerRegistration

2017-10-30 20:43 UTC, bstansberry commented on jsf/subsystem/src/main/java/org/jboss/as/jsf/deployment/JSFMetadataProcessor.java
> +        boolean paramFound = contextParams.stream().anyMatch(param -> name.equals(param.getParamName()) && param.getParamValue() != null);
Please switch to a basic for loop. Lambdas are expensive in terms of class storage space.

2017-10-31 19:56 UTC, fjuma commented
Fixed and rebased. Note that the upgrade to jsf-impl 2.2.13.SP2 is no longer needed since master is already on jsf-impl 2.2.13.SP4.

2017-10-31 21:33 UTC, fjuma commented
retest this please

2017-11-01 13:47 UTC, fjuma commented
retest this please

2017-11-01 18:40 UTC, bstansberry approved these changes

2017-11-01 18:40 UTC, merged