[WFCORE-1463] Testsuite: added test checking for X-frame-options header in management console
wildfly/wildfly pull request #9153
Opened 2016-08-25 09:06 UTC by honza-kasik

Added tests for presence of X-Frame-Options header in response from management console.
Tests for: https://issues.jboss.org/browse/WFCORE-1463
Fix merged in: https://github.com/wildfly/wildfly-core/pull/1722

2016-08-26 15:28 UTC, luck3y commented
This is OK to test.

2016-08-26 15:31 UTC, bstansberry commented
this is ok to test

2016-08-26 16:39 UTC, luck3y commented
this is ok to test

2016-08-26 16:51 UTC, jamezp commented
Just testing closing this to see if the repeated comment issue goes away. I will reopen it,

2016-08-30 09:35 UTC, kabir commented
@honza-kasik The test failures seem valid. Both the Windows and Linux jobs include the same test failures, and so do the downstream ones.

2016-11-14 09:46 UTC, kabir commented
Retest this please

2016-12-01 22:56 UTC, bstansberry commented
retest this please

2017-06-23 10:19 UTC, ctomc requested changes

2017-06-23 10:19 UTC, ctomc commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/console/XFrameOptionsHeaderTestCase.java
> +import org.wildfly.core.testrunner.ManagementClient;
you are importing wrong management client that is why it is failing.
you need org.jboss.as.arquillian.container.ManagementClient

2017-06-26 09:38 UTC, ctomc commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/console/XFrameOptionsHeaderTestCase.java
> +    @ArquillianResource
@Inject should work

2017-06-28 06:00 UTC, honza-kasik commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/management/console/XFrameOptionsHeaderTestCase.java
> +    @ArquillianResource
Thanks! Looks like `@ContainerResource` worked! Strange - `@ArquillianResource` was OK when I run it locally...

2017-06-28 11:43 UTC, honza-kasik commented
@kabir @ctomc Looks like it fails only with Elytron now, but the fail looks unrelated to test...

2017-06-28 14:14 UTC, luck3y commented
retest this please

2017-06-28 16:36 UTC, luck3y commented
This failure doesn't look related to me ... lets have one more go.

2017-06-28 16:36 UTC, luck3y commented
retest this please

2017-06-29 13:43 UTC, honza-kasik commented
@bstansberry @kabir @luck3y The tests which are failed are different and looks like not related. Can you please merge this?

2017-06-29 17:25 UTC, bstansberry approved these changes
This looks fine and I'm not concerned about the latest CI failures but the 7.x variant will need to be synced to this and an acceptable CI run obtained there before this can be merged.

2017-06-30 18:29 UTC, merged