[WFLY-7068] Typo in help for Infinispan subsystem
wildfly/wildfly pull request #9176
Opened 2016-09-07 08:33 UTC by treblereel

Jira: https://issues.jboss.org/browse/WFLY-7068

2016-10-04 20:34 UTC, bstansberry commented
Please link a 7.x PR as we are not merging changes to WildFly full without also updating 7.x.

2016-10-11 13:15 UTC, rhusar requested changes
Missing a corresponding EAP PR.

2016-10-13 16:13 UTC, treblereel commented
@bstansberry done

2016-10-13 23:15 UTC, rhusar approved these changes

2016-10-16 17:08 UTC, merged