[WFLY-7139] Handle "Component is stopped" exception better on undeploy for EJB client.
wildfly/wildfly pull request #9203
Opened 2016-09-19 20:54 UTC by rachmatowicz

This PR addresses: https://issues.jboss.org/browse/WFLY-7139

2016-09-20 19:20 UTC, rhusar commented on ee/src/main/java/org/jboss/as/ee/component/ComponentIsStoppedException.java
> +package org.jboss.as.ee.component;
Missing copyright header.

2016-09-20 19:21 UTC, rhusar commented on ee/src/main/java/org/jboss/as/ee/component/ComponentIsStoppedException.java
> +     * Constructs a <tt>ComponentIsStoppedException</tt> with no detail message.
IIUC the < tt > html element is deprecated, you can use < code > instead.

2016-09-20 19:21 UTC, rhusar commented on ee/src/main/java/org/jboss/as/ee/component/ComponentIsStoppedException.java
> +     * Constructs a <tt>ComponentIsStoppedException</tt> with the specified
Same as above.

2016-09-20 19:22 UTC, rhusar requested changes

2016-09-22 14:27 UTC, jfclere commented
It is https://issues.jboss.org/browse/JBEAP-5764.

2016-09-23 16:03 UTC, rachmatowicz commented on ee/src/main/java/org/jboss/as/ee/component/ComponentIsStoppedException.java
> +package org.jboss.as.ee.component;
Fixed.

2016-09-23 16:04 UTC, rachmatowicz commented on ee/src/main/java/org/jboss/as/ee/component/ComponentIsStoppedException.java
> +     * Constructs a <tt>ComponentIsStoppedException</tt> with no detail message.
Fixed.

2016-09-23 16:04 UTC, rachmatowicz commented on ee/src/main/java/org/jboss/as/ee/component/ComponentIsStoppedException.java
> +     * Constructs a <tt>ComponentIsStoppedException</tt> with the specified
Fixed.

2016-09-23 16:16 UTC, rhusar commented
@jfclere more importantly, we need a downstream PR not just an acked EAP issue.

2016-09-30 14:26 UTC, merged