WFLY-7274 Decrease remote-timeout to prevent remote server shutdown from causing lock timeouts.
wildfly/wildfly pull request #9259
Opened 2016-10-07 12:39 UTC by pferraro

https://issues.jboss.org/browse/WFLY-7274

2016-10-11 09:02 UTC, rhusar requested changes

2016-10-11 09:02 UTC, rhusar commented on clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_4_0.xsd
> +                <xs:attribute name="remote-timeout" type="xs:long" default="10000">
We should actually change this in all the XSDs since whatever the XML schema version, the parsed default will be the new value.

2016-10-17 22:41 UTC, pferraro commented on clustering/infinispan/extension/src/main/resources/schema/jboss-as-infinispan_4_0.xsd
> +                <xs:attribute name="remote-timeout" type="xs:long" default="10000">
Done.

2016-10-18 17:11 UTC, rhusar approved these changes

2016-10-18 20:34 UTC, merged