[WFLY-6629]: Create test for [WFCORE-1479]: Jar sub deployment has as…
wildfly/wildfly pull request #9329
Opened 2016-11-03 11:53 UTC by simkam

… first dependency parent ear

adds test for WFCORE-1479
replaces deprecated DefaultHttpClient with HttpClientBuilder
replaces with hardcoded web context with injected

https://issues.jboss.org/browse/WFLY-6629

supersedes #8852

2016-11-03 14:01 UTC, simkam commented
don't merge it yet, the test is wrong, I'll fix it

2016-11-03 14:36 UTC, istudens commented
Martin, this will need another change, some of the new files are missing licence header, see
https://github.com/jbossas/jboss-eap7/pull/932/commits/df762ded9db9193fe134e0df692da7de3ed4674b

2016-11-03 14:58 UTC, simkam commented
PR updated

@istudens thanks, I didn't notice. Also I found why there was binary file in original PR, it wasn't clear to me at first look. It contains modified class javax.naming.Binding and test verifies that class from implicit module is instantiated instead of the modified one from that is included in ear

I'm not sure if it is best solution, of course we can add that class and create archive with shrinkwrap, but I think it would add mess to tests, having javax.naming package in src/test/..

2016-11-03 17:00 UTC, ctomc commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/subdeployments/SubDeploymentAvailableInClassPathTestCase.java
> +        final HttpClient httpClient = HttpClientBuilder.create().build();
try (final CloseableHttpClient httpClient HttpClients.createDefault()){...

if we are fixing this lets fix it properly...

2016-11-03 17:01 UTC, ctomc commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/deployment/classloading/ear/subdeployments/servlet/EjbInvokeToStringServlet.java
> +        } catch (ClassNotFoundException cnfe) {
multicatch?

2016-11-03 17:01 UTC, ctomc requested changes
This needs to be fixed.
The worst offender is adding binary artifact "javax-naming-test-impl.jar" to source tree.

2016-11-04 11:53 UTC, simkam commented
fixed, I hope

2016-11-07 15:23 UTC, merged