WFLY-5227 - move security-manager to wildfly-core
wildfly/wildfly pull request #9443
Opened 2016-12-01 16:51 UTC by luck3y

2016-12-01 16:56 UTC, bstansberry requested changes

2016-12-01 16:56 UTC, bstansberry commented on pom.xml
> +                        <groupId>org.wildfly.core</groupId>
This is a different artifact -- it's the actual security manager, not the subsystem.

2016-12-01 17:01 UTC, luck3y commented on pom.xml
> +                        <groupId>org.wildfly.core</groupId>
Fixed, below, I'll squash the additional ones at the end.

2016-12-01 17:34 UTC, luck3y commented
CI Run: https://ci.wildfly.org/viewLog.html?buildId=36006&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

2016-12-01 23:08 UTC, luck3y commented
Hopefully successful run in CI, due to some confusion of -SNAPSHOT vs not  :(

https://ci.wildfly.org/viewLog.html?buildId=36033&tab=buildResultsDiv&buildTypeId=WF_WildFlyCoreIntegrationExperiments

2016-12-01 23:36 UTC, luck3y commented
@bstansberry This is all set now, -SNAPSHOT removed and CI passed.

2016-12-02 02:12 UTC, bstansberry commented
retest this please

2016-12-02 02:22 UTC, bstansberry commented
retest this please

2016-12-02 02:23 UTC, bstansberry approved these changes

2016-12-02 02:35 UTC, luck3y commented
retest this please

2016-12-02 02:55 UTC, luck3y commented
retest this please

2016-12-02 04:11 UTC, merged