[WFLY-8109] Improve timeouts in AS TS
wildfly/wildfly pull request #9648
Opened 2017-02-15 09:46 UTC by marekkopecky

Improve timeouts in AS TS
* JMSMessageDrivenBeanTestCase should use TimeoutUtil for timeout
* increase timeout in PassivationTestCase
* JspCompilerTestCase should use TimeoutUtil for timeout
* increase timeout in MDBTestCase
* increase the default forked process timeout for basic module to hour, same timeout is used in clustering module, see https://github.com/wildfly/wildfly/blob/master/testsuite/integration/clustering/pom.xml#L24

This stabilizes TS on slower machines.

2017-02-15 19:07 UTC, bstansberry requested changes

2017-02-15 19:07 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/JMSMessageDrivenBeanTestCase.java
> +                .addClass(TimeoutUtil.class);
The deployment will now need a system property read permission for this test to work with a security manager. MDBTestCase has an example of that setup.

2017-02-15 19:07 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/JMSMessageDrivenBeanTestCase.java
> +                .addClass(TimeoutUtil.class);
This deployment will now need a security manager permission to read the system property for it to pass in a security-manager enabled run. MDBTestCase has an example of setting that up.

2017-02-15 19:07 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/wildfly/test/integration/jsp/JspCompilerTestCase.java
> +        HttpRequest.get(url + "index.jsp", TimeoutUtil.adjust(15), TimeUnit.SECONDS);
This one shouldn't need the security manager permission because the test is @RunAsClient so the property isn't read in the server process.

2017-02-15 20:03 UTC, bstansberry commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/ejb/mdb/JMSMessageDrivenBeanTestCase.java
> +                .addClass(TimeoutUtil.class);
Note this is the same comment as my last one. github made it disappear for a while so i retyped it. :)

2017-02-20 13:55 UTC, marekkopecky commented
@bstansberry Thank you for your review.

I fixed JMSMessageDrivenBeanTestCase as requested.

I also remove usage of TimeoutUtil from TxTestUtil, because this causes fail of MessageDrivenTimeoutTestCase if -Dts.timeout.factor=200 is used. More information is in description of https://issues.jboss.org/browse/WFLY-8109

Can you please review this again?

2017-02-20 14:14 UTC, bstansberry approved these changes

2017-02-20 14:16 UTC, bstansberry commented
@marekkopecky This looks good, but will need a JBEAP equivalent before it can be merged for WF 11.

2017-02-20 16:39 UTC, marekkopecky commented
@bstansberry Sure, 
JBEAP jira: https://issues.jboss.org/browse/JBEAP-8966
JBEAP PR: https://github.com/jbossas/jboss-eap7/pull/1373

2017-02-20 21:56 UTC, merged