WFLY-8184 Singleton deployment not stopped on the previous singleton …
wildfly/wildfly pull request #9686
Opened 2017-02-21 23:52 UTC by rhusar

…provider after new provider is elected

Jira
https://issues.jboss.org/browse/WFLY-8184

2017-02-22 13:14 UTC, bstansberry commented
@pferraro Please approve.

2017-02-27 13:42 UTC, pferraro requested changes
The fundamental fix is sound.  Requested changes are minor.

2017-02-27 13:42 UTC, pferraro commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ClusterAbstractTestCase.java
> +    protected void executeOnNodes(String cli, ManagementClient... clients) throws Exception {
This can be static, and maybe more appropriate in the ClusterTestUtil class?

2017-02-27 13:42 UTC, pferraro commented on clustering/server/src/main/java/org/wildfly/clustering/server/singleton/DistributedSingletonService.java
>          this.backupController = target.addService(this.serviceName.append("backup"), this.backupService.orElse(new PrimaryProxyService<>(this))).setInitialMode(ServiceController.Mode.PASSIVE).install
Tangentially, we should likewise install the backup service as ACTIVE, so that it toggles to NEVER instead of ON_DEMAND as well.

2017-02-27 18:40 UTC, rhusar commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/ClusterAbstractTestCase.java
> +    protected void executeOnNodes(String cli, ManagementClient... clients) throws Exception {
True, moved.

2017-02-27 18:40 UTC, rhusar commented on clustering/server/src/main/java/org/wildfly/clustering/server/singleton/DistributedSingletonService.java
>          this.backupController = target.addService(this.serviceName.append("backup"), this.backupService.orElse(new PrimaryProxyService<>(this))).setInitialMode(ServiceController.Mode.PASSIVE).install
Agreed, done.

2017-02-27 18:42 UTC, rhusar commented on testsuite/integration/clustering/src/test/java/org/jboss/as/test/clustering/cluster/singleton/SingletonDeploymentTestCase.java
> +        executeOnNodes("/subsystem=singleton/singleton-policy=default/election-policy=simple:write-attribute(name=position,value=1)", client1, client2);
Ah, absolutely. Fixed.

2017-02-27 22:50 UTC, merged