[WFLY-8010] Test for Datasource/Elytron integration
wildfly/wildfly pull request #9687
Opened 2017-02-22 13:15 UTC by sguilhen

2017-02-24 14:51 UTC, simkam requested changes

2017-02-24 14:51 UTC, simkam commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/DsWithElytronSecurityDomainTestCase.java
> +            addOperation.get("connection-url").set("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
Hi Stefan, 
please change database name to something unique for this test

2017-02-24 14:51 UTC, simkam commented on testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jca/security/DsWithElytronSecurityDomainTestCase.java
> +            connection = DriverManager.getConnection("jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE", "sa", DATABASE_PASSWORD);
the same

2017-02-26 09:24 UTC, kabir commented
Retest this please

2017-02-26 11:24 UTC, merged