WFLY-8315 JGroups protocols collect statistics by default
wildfly/wildfly pull request #9789
Opened 2017-03-13 15:05 UTC by rhusar

Jiras
https://issues.jboss.org/browse/WFLY-8315
https://issues.jboss.org/browse/WFLY-2453
https://issues.jboss.org/browse/WFLY-8317

2017-03-13 15:29 UTC, pferraro requested changes

2017-03-13 15:29 UTC, pferraro commented on clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/ForkChannelFactory.java
> +            protocol.enableStats(protocolConfiguration.isStatisticsEnabled() != null ? protocolConfiguration.isStatisticsEnabled() : this.parentFactory.getProtocolStackConfiguration().isStatisticsEna
Why not a separate .map(...) function?

2017-03-13 15:29 UTC, pferraro commented on clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/JChannelFactory.java
> +        stack.addProtocols(Stream.of(
Stream.concat(...) would be much more efficient here.

2017-03-13 15:29 UTC, pferraro commented on clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/JChannelFactory.java
> +            protocol.enableStats(protocolConfiguration.isStatisticsEnabled() != null ? protocolConfiguration.isStatisticsEnabled() : this.configuration.isStatisticsEnabled());
.map(protocol -> protocol.enableStats(...)) ?

2017-03-13 15:29 UTC, pferraro commented on clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/JChannelFactory.java
> +        fork.enableStats(configuration.isStatisticsEnabled());
Probably easier to add () -> new FORK() to the stream created above.

2017-03-13 15:29 UTC, pferraro commented on clustering/jgroups/extension/src/main/java/org/jboss/as/clustering/jgroups/subsystem/AbstractProtocolConfigurationBuilder.java
> +        this.statisticsEnabled = STATISTICS_ENABLED.resolveModelAttribute(context, model).asBooleanOrNull();
Nice.

2017-03-13 15:31 UTC, pferraro commented on clustering/jgroups/spi/src/main/java/org/wildfly/clustering/jgroups/spi/ProtocolConfiguration.java
> +    static Function<ProtocolConfiguration<? extends Protocol>, Protocol> creator(ProtocolStackConfiguration stackConfiguration) {
I just vomited in my mouth a little...

2017-03-13 15:31 UTC, pferraro commented on clustering/jgroups/spi/src/main/java/org/wildfly/clustering/jgroups/spi/ProtocolConfiguration.java
> +    static Function<ProtocolConfiguration<? extends Protocol>, Protocol> creator(ProtocolStackConfiguration stackConfiguration) {
:)

2017-03-13 16:44 UTC, pferraro approved these changes

2017-03-20 23:43 UTC, rhusar commented
retest this please

2017-03-21 11:35 UTC, kabir commented
Retest this please

2017-03-23 12:30 UTC, merged