Cleaning servers artefacts in test suite after test execution
wildfly/wildfly pull request #9839
Opened 2017-03-22 10:06 UTC by ehsavoie

Removing the tests artefacts to reduce the filesystem usage of the test suite

2017-03-22 14:48 UTC, rhusar requested changes
-1

These are used to investigate test failures after the tests run and this doesn't even seem to be opt-in.

2017-03-22 14:49 UTC, pferraro commented
:-1: This execution should not be enabled by default.  The general concept is fine (e.g. for CI runs), but IMO, it should be explicitly enabled via a property.

2017-03-23 08:54 UTC, ehsavoie commented
In case of failure in the test the server directories wouldn't be deleted except if using -fae as the build would stop before the clean is called so I didn't think opt-in was required.
Adding a profile for this cleanup

2017-03-27 19:47 UTC, bstansberry commented on testsuite/domain/pom.xml
> +                    <name>cleanup</name>
How about ci-cleanup? The term "cleanup" is pretty generic.

2017-03-27 19:47 UTC, bstansberry commented on testsuite/domain/pom.xml
> +                                <id>clean-manual-mode-servers</id>
This id is repeated in all the poms, so if it's not going to be unique per pom it shouldn't mention manual-mode.

2017-03-27 19:56 UTC, bstansberry commented
Our CI jobs all use --fae, so we can't count on this not running in the case of CI failure. And in the case of failure we can't be deleting the log files. The reason we archive log files in CI (for example see https://ci.wildfly.org/viewLog.html?buildId=52414&buildTypeId=WF_MasterLinux&tab=artifacts) is to make them available when analyzing failed runs.

2017-04-25 12:28 UTC, bstansberry commented
@ehsavoie Adding this to each fileset should address my concern about the logs:

```
          <excludes>
            <exclude>**/*.log</exclude>
          </excludes>
```

2017-05-19 09:39 UTC, ehsavoie commented
retest this please

2017-05-24 14:35 UTC, closed without merging