WFLY-6616 fix clobbering of slave host.xml after we set ignore-unused-configuration="false".
wildfly/wildfly pull request #9905
Opened 2017-04-05 03:36 UTC by luck3y

99% of this was Kabir's from  https://github.com/kabir/wildfly/tree/WFLY-6616

2017-04-05 03:54 UTC, luck3y commented
Custom integration run for mixed domain here: https://ci.wildfly.org/viewLog.html?buildId=53748

2017-04-05 13:11 UTC, luck3y commented
retest this please

2017-04-05 18:24 UTC, luck3y commented
retest this please

2017-04-05 19:04 UTC, luck3y commented
retest this please

2017-04-05 20:24 UTC, luck3y commented
retest this please

2017-04-05 22:15 UTC, luck3y commented
retest this please

2017-04-12 14:35 UTC, luck3y commented
retest this please

2017-04-13 21:12 UTC, bstansberry requested changes
Looks good other than the one minor comment. Please clone the JIRA to JBEAP and send up a 7.x, and ping me when ready.

2017-04-13 21:12 UTC, bstansberry commented on testsuite/mixed-domain/src/test/java/org/jboss/as/test/integration/domain/mixed/eap700/DomainHostExcludes700TestCase.java
> +        setup(DomainHostExcludes700TestCase.class, /*"EAP7.0" Is not in KnownReleases yet */null, ModelVersion.create(4, 1));
/*"EAP7.0" Is not in KnownReleases yet */

^^^ is not true an more.

2017-04-13 21:50 UTC, luck3y commented
@bstansberry Done & JBEAP & 7.x PR sent.

2017-04-18 12:39 UTC, merged